#!/usr/bin/env python3
"""NOOR Content Graph: rebuild assets/reel-sources.json from the graph.

    python3 derive_reel_sources.py [--graph build/graph/noor-content-graph.json] [--out assets/reel-sources.json]

api/_package.js (the Content Factory, masterplan step 6) needs to know,
for a Light, a verse, a word, a prophet, a companion, a place, a chapter,
a surah or a Name, which reel cards and which "short" films the shelf
already carries for it, so a package's derivatives are the graph's own
answer rather than a handful of exact-id guesses (a Light card shares its
id with the Light, a word card is "word-<id>", and so on; a Did you know
card's own id carries no trace of the Light it was written from at all).
The graph already carries this, build_graph.py's `reel_of` edges (every
one of the 1,565 planned cards, plus the 34 traced "short" films), each
with its own confidence; this script reads them once, here, where the
graph already exists, and writes one small file so api/package.js never
has to open build/graph/noor-content-graph.json itself (7 MB, git ignored,
never deployed: .vercelignore's /build/).

A reel node's own `kind` field (build_graph.py, add_node's `kind=r.get(
'kind')` for a manifest row) tells an ordinary reel card apart from a
"short" film: `kind == "short"` is a film, everything else (light, know,
word, name, verse, day, dua) is an ordinary reel. Both kinds are written
under the content_id they were cut from; api/_package.js reads "reels" and
"films" straight off that, no id-matching left to guess at.

The 99 Names carry two ids for the one room: the graph's own content_id is
`name:<slug>` (build_graph.py's own slug() of the transliteration, with a
position suffix on the two that collide, Al-Majid at 48 and 65,
content-004), and the room the site renders it at is `/name/<position>`,
1 to 99 -- the only place the two are translated into each other is this
graph, off the node's own `url` field. So this file also carries a small
`names` map, position to content_id, read off exactly that, rather than
letting api/_package.js reconstruct a slug of its own that might one day
drift from the graph's.

Rerun scripts/graph/run.sh whenever the shelf (reels/index.json), the
plan (tools/reels/plan.json) or the briefs (tools/films/briefs/) change;
do not hand edit the output.
"""
import argparse, json, os, re

HERE = os.path.dirname(os.path.abspath(__file__))
REPO_DEFAULT = os.path.normpath(os.path.join(HERE, '..', '..'))

ap = argparse.ArgumentParser()
ap.add_argument('--graph', default=os.path.join(REPO_DEFAULT, 'build', 'graph', 'noor-content-graph.json'))
ap.add_argument('--out', default=os.path.join(REPO_DEFAULT, 'assets', 'reel-sources.json'))
args = ap.parse_args()

g = json.load(open(args.graph, encoding='utf-8'))
nodes = {n['id']: n for n in g['nodes']}

sources = {}
for e in g['edges']:
    if e.get('rel') != 'reel_of':
        continue
    reel_nid, target = e['from'], e['to']
    if target not in nodes or not reel_nid.startswith('reel:'):
        continue
    reel_node = nodes.get(reel_nid) or {}
    card_id = reel_nid[len('reel:'):]
    row = {'id': card_id, 'confidence': e.get('confidence', 1.0)}
    bucket = sources.setdefault(target, {'reels': [], 'films': []})
    key = 'films' if reel_node.get('kind') == 'short' else 'reels'
    bucket[key].append(row)

# stable order: strongest confidence first, then the card id, on both
# machines, both runs, so a diff only ever shows a real change
for bucket in sources.values():
    for key in ('reels', 'films'):
        bucket[key].sort(key=lambda r: (-r['confidence'], r['id']))
    # a target with a film but no reel, or the other way round, still
    # loses the empty list: a missing key already reads as "none" the same
    # way assets/entity-graph.json's own missing keys do
    if not bucket['reels']: del bucket['reels']
    if not bucket['films']: del bucket['films']

names = {}
for nid, n in nodes.items():
    if not nid.startswith('name:'):
        continue
    m = re.match(r'^/name/(\d+)$', str(n.get('url') or ''))
    if m:
        names[m.group(1)] = nid

out = {
    '_about': "Generated by scripts/graph/derive_reel_sources.py from build/graph/noor-content-graph.json's "
              "own reel_of edges. Do not hand edit; rerun scripts/graph/run.sh. Read by api/_package.js so a "
              "package's derivatives (which reel, which film) are the graph's own answer, and so a Name's "
              "content_id uses the graph's own slug rather than a second, invented one.",
    'sources': {k: sources[k] for k in sorted(sources)},
    'names': {k: names[k] for k in sorted(names, key=int)}
}
os.makedirs(os.path.dirname(args.out), exist_ok=True)
with open(args.out, 'w', encoding='utf-8') as f:
    json.dump(out, f, indent=1, ensure_ascii=False)
    f.write('\n')
n_reels = sum(len(b.get('reels', [])) for b in sources.values())
n_films = sum(len(b.get('films', [])) for b in sources.values())
print(f"wrote {args.out}: {len(sources)} content objects, {n_reels} reel edges, {n_films} film edges, {len(names)} Names")
