#!/usr/bin/env python3
"""NOOR Content Graph: rebuild assets/person-words.json from same-as.json.

    python3 derive_person_words.py [--same-as scripts/graph/same-as.json] [--out assets/person-words.json]

api/page.js's relatedWords() drops a dictionary word from a room's shelf
when every sighting of it in the room's own prose reads as part of a
person's name rather than the term itself: "al-Hasan ibn Ali" is a man, not
the hadith grade Hasan. That guard must not then strip the very word that
names a person the dictionary word already IS -- khadijah, fatimah, mahdi
and the rest of scripts/graph/same-as.json's curated word: pairs -- or a
Light that writes "Khadijah bint Khuwaylid" loses her own word the moment
her father's name follows "bint".

scripts/graph/ never deploys (.vercelignore's /scripts/), so api/page.js
cannot read same-as.json itself on the live site; this script is the one
step between the two, run by scripts/graph/run.sh, writing the one small
file (assets/person-words.json) that does deploy (api/page.js's own
includeFiles already covers assets/*.json). Every word: key in same-as.json
becomes one entry, sorted, so the file is the same on every machine that
runs this script over the same same-as.json.
"""
import argparse, json, os

HERE = os.path.dirname(os.path.abspath(__file__))
REPO_DEFAULT = os.path.normpath(os.path.join(HERE, '..', '..'))

ap = argparse.ArgumentParser()
ap.add_argument('--same-as', default=os.path.join(HERE, 'same-as.json'))
ap.add_argument('--out', default=os.path.join(REPO_DEFAULT, 'assets', 'person-words.json'))
args = ap.parse_args()

same_as = json.load(open(args.same_as, encoding='utf-8')).get('same_as', {})
words = sorted(k[len('word:'):] for k in same_as if k.startswith('word:'))

out = {
    "_about": "Generated by scripts/graph/derive_person_words.py from scripts/graph/same-as.json's "
              "own word: pairs. Do not hand edit; rerun scripts/graph/run.sh. Read by api/page.js's "
              "relatedWords() (personWords()) since scripts/ itself never deploys.",
    "words": words
}
os.makedirs(os.path.dirname(args.out), exist_ok=True)
with open(args.out, 'w', encoding='utf-8') as f:
    json.dump(out, f, indent=1, ensure_ascii=False)
    f.write('\n')
print(f"wrote {args.out}: {len(words)} words")
