// NOOR Words of the Path, generated by scripts/build.mjs
const WORDS = {
verses: [
{id:"w-hasbunallah",titleEn:"Hasbunallahu wa ni'mal-wakil",titleAr:"حَسْبُنَا اللَّهُ وَنِعْمَ الْوَكِيلُ",translit:"Hasbunallahu wa ni'mal-wakil",meaning:"Allah is sufficient for us, and the best Disposer of affairs",role:"The word of the outnumbered",summary:"Said by Ibrahim flying toward the fire, and by Muhammad ﷺ facing the gathered confederates.",pattern:"pl-word",
details:`One sentence, two prophets, twenty-five centuries apart. Ibn Abbas certified the chain: "{{n:9|Ibrahim}} said it when he was cast into the fire, and Muhammad ﷺ said it when they said: the people have gathered against you, so fear them; and it only increased them in faith" (Bukhari 4563). It is the believer's response to superior force: not a denial of the odds, but a change of accountant. The fire was commanded to cool; the confederates were scattered by wind.

The Prophet ﷺ prescribed it forward as well: when {{c:a-israfil|the bearer of the Horn}} was described inclined and waiting, the companions asked what they could possibly say in the face of that; he answered: "say: hasbunallahu wa ni'mal-wakil" (Tirmidhi 2431). The sentence scales from a burning pyre to the end of the universe without modification.`,
whenNow:["At any news that outnumbers you: gathered enemies, bad diagnoses, impossible odds",
 "When fear is being marketed to you: the verse's own context (3:173)",
 "Facing the unknown scale of the Last Day, by his ﷺ instruction"],
facts:[{"label":"First said by","value":"Ibrahim, mid-air"},
 {"label":"Repeated by","value":"Muhammad ﷺ at the gathering"},
 {"label":"Effect then","value":"Fire cooled · confederates broken"},
 {"label":"Verse","value":"3:173"}],
quran:[{"ref":"3:173","ar":"الَّذِينَ قَالَ لَهُمُ النَّاسُ إِنَّ النَّاسَ قَدْ جَمَعُوا لَكُمْ فَاخْشَوْهُمْ فَزَادَهُمْ إِيمَانًا وَقَالُوا حَسْبُنَا اللَّهُ وَنِعْمَ الْوَكِيلُ","en":"Those to whom people said: the people have gathered against you, so fear them; but it increased them in faith, and they said: Allah is sufficient for us, and the best Disposer of affairs."}],
hadith:[{"text":"Ibrahim said it when he was thrown into the fire, and Muhammad ﷺ said it when they said: the people have gathered against you.","source":"Bukhari 4563"}]},

{id:"w-dhunnun",titleEn:"The Call of Dhun-Nun",titleAr:"لَا إِلَٰهَ إِلَّا أَنتَ سُبْحَانَكَ إِنِّي كُنتُ مِنَ الظَّالِمِينَ",translit:"La ilaha illa anta, subhanaka, inni kuntu minaz-zalimin",meaning:"None has the right to be worshipped but You; glory be to You; I have been of the wrongdoers",role:"The key that opens from inside the whale",summary:"Three clauses in triple darkness; the Prophet ﷺ guaranteed the formula for every Muslim who uses it.",pattern:"pl-word",
details:`Inside {{c:an-yunus|the whale}}, in the darkness of night, sea, and belly, {{n:23|Yunus}} built the only exit that existed: tawhid, tanzih, and confession, in that order. None but You; You are perfect; the fault is mine. The Qur'an states the mechanism and generalizes it in the same breath: "so We responded to him and saved him from the distress; and thus do We save the believers" (21:88). Thus: the same way, every time.

The Prophet ﷺ turned the verse's promise into an explicit guarantee: "the supplication of Dhun-Nun when he called in the belly of the whale... no Muslim ever supplicates with it for anything except that Allah answers him" (Tirmidhi 3505, sahih). The scholars noted the engineering: the du'a contains no request at all. It repairs the relationship, and the rescue follows as a consequence. Whoever cannot find words for what he needs can say the three clauses that need no customization.`,
whenNow:["In any distress, by the explicit guarantee of Tirmidhi 3505",
 "When guilt blocks asking: the formula confesses first and asks nothing",
 "In the personal darknesses: grief, debt, illness, the closed room"],
facts:[{"label":"Said in","value":"Triple darkness"},
 {"label":"Contains","value":"Zero requests"},
 {"label":"Mechanism","value":"“Thus do We save the believers”"},
 {"label":"Guarantee","value":"Answered, for any Muslim"}],
quran:[{"ref":"21:87-88","ar":"فَنَادَىٰ فِي الظُّلُمَاتِ أَن لَّا إِلَٰهَ إِلَّا أَنتَ سُبْحَانَكَ إِنِّي كُنتُ مِنَ الظَّالِمِينَ فَاسْتَجَبْنَا لَهُ","en":"He called out in the darknesses: none has the right to be worshipped but You; glory be to You; I have been of the wrongdoers. So We responded to him."}],
hadith:[{"text":"No Muslim supplicates with it for anything except that Allah answers him.","source":"Tirmidhi 3505 (sahih)"}]},

{id:"w-rabbana-zalamna",titleEn:"The Words Adam Received",titleAr:"رَبَّنَا ظَلَمْنَا أَنفُسَنَا وَإِن لَّمْ تَغْفِرْ لَنَا وَتَرْحَمْنَا لَنَكُونَنَّ مِنَ الْخَاسِرِينَ",translit:"Rabbana zalamna anfusana wa il-lam taghfir lana wa tarhamna lanakunanna minal-khasirin",meaning:"Our Lord, we have wronged ourselves; if You do not forgive us and have mercy on us, we will surely be among the losers",role:"Mankind's first repentance",summary:"The sentence Adam and Hawwa said together at the bottom of the first fall; the template of every tawbah since.",pattern:"pl-word",
details:`After the slip in the Garden, "{{n:2|Adam}} received from his Lord words, and He accepted his repentance" (2:37): heaven did not only forgive the first sin, it supplied the vocabulary for its confession. The words themselves stand in 7:23, spoken in the dual, by {{n:3|both of them together}}: no blame traded, no whisperer scapegoated, though the whisperer was real.

The anatomy is the permanent template. Ownership first: we wronged ourselves. Dependence second: if You do not forgive us. Realism third: we will surely be among the losers; no plan B is proposed. Compare it, the scholars say, with {{c:j-iblis|Iblis's}} response to his own fall in the same surah: argument, blame, and a request for respite to harm others. Two falls, two scripts, two destinies. Every child of Adam re-enacts one of them after every sin, and the Codex keeps the winning script exactly where a reader in the middle of a bad night can copy it.`,
whenNow:["Immediately after any sin: the first words, before the mood hardens",
 "In sujud and between the adhan and iqamah, the hours of acceptance",
 "Together with a spouse after shared wrong: the original was said in the dual"],
facts:[{"label":"Speakers","value":"Adam & Hawwa, together"},
 {"label":"Supplied by","value":"Allah Himself (2:37)"},
 {"label":"Structure","value":"Ownership · dependence · realism"},
 {"label":"Anti-script","value":"Iblis's blame, same surah"}],
quran:[{"ref":"7:23","ar":"قَالَا رَبَّنَا ظَلَمْنَا أَنفُسَنَا وَإِن لَّمْ تَغْفِرْ لَنَا وَتَرْحَمْنَا لَنَكُونَنَّ مِنَ الْخَاسِرِينَ","en":"They both said: our Lord, we have wronged ourselves; if You do not forgive us and have mercy on us, we will surely be among the losers."}]},

{id:"w-bismillah-majreha",titleEn:"The Word that Sailed the Ark",titleAr:"بِسْمِ اللَّهِ مَجْرَاهَا وَمُرْسَاهَا",translit:"Bismillahi majraha wa mursaha",meaning:"In the name of Allah is its course and its anchorage",role:"The bismillah of departures",summary:"Nuh's boarding announcement over waves like mountains: journeys run on the Name, not the hull.",pattern:"pl-word",
details:`As the water rose and the animals filed aboard, {{n:6|Nuh}} declared the ship's operating system: "board it; in the name of Allah is its course and its anchorage" (11:41). Course and anchorage: the going and the stopping, both filed under the Name before the first wave hit. The hull was gopher-wood and pitch; the seaworthiness was bismillah. {{n:7|Waves like mountains}} tested exactly that claim and confirmed it.

The ummah inherited the physics. The Prophet ﷺ taught the mount-boarding du'a from the same theology, "glory to Him who subjected this to us, and we could not have subdued it" (43:13), and the tradition kept Nuh's own formula alive for embarkations. The scholars read the verse wide: every project is a vessel, every beginning a boarding. Whoever launches a marriage, a business, a book, or a hijrah has a flood-tested checklist of one item. The Codex files this word beside its counter-example from the same deck: the son who chose {{n:7|a mountain instead of the Name}}, and the verse's cold arithmetic of that choice.`,
whenNow:["Boarding any vehicle: car, ship, plane; the sunnah's travel dhikr family",
 "Launching any undertaking: the course and the anchorage assigned in advance",
 "Teaching children their first travel word: the ummah's oldest boarding pass"],
facts:[{"label":"Said at","value":"Boarding, before the flood"},
 {"label":"Covers","value":"Course and anchorage both"},
 {"label":"Tested by","value":"Waves like mountains"},
 {"label":"Counter-case","value":"The son and the mountain"}],
quran:[{"ref":"11:41","ar":"وَقَالَ ارْكَبُوا فِيهَا بِسْمِ اللَّهِ مَجْرَاهَا وَمُرْسَاهَا ۚ إِنَّ رَبِّي لَغَفُورٌ رَّحِيمٌ","en":"He said: board it; in the name of Allah is its course and its anchorage. Indeed my Lord is Forgiving, Merciful."}]},

{id:"w-rabbi-inni",titleEn:"The Beggar's Masterpiece",titleAr:"رَبِّ إِنِّي لِمَا أَنزَلْتَ إِلَيَّ مِنْ خَيْرٍ فَقِيرٌ",translit:"Rabbi inni lima anzalta ilayya min khayrin faqir",meaning:"My Lord, I am, for whatever good You send down to me, in need",role:"The du'a of the emptied-out",summary:"Musa at the well of Madyan: no money, no country, no request line, and everything granted within the hour.",pattern:"pl-word",
details:`A fugitive with a death warrant behind him and a desert ahead, {{n:16|Musa}} watered two strangers' flock, walked to the shade, and produced the most dignified request for help ever recorded: a description of himself, addressed to his Lord, with the request line left blank (28:24). Whatever good You send: food, work, family, safety; the applicant declines to narrow the field.

The response staffed his whole life within the scene: employment, a household, a decade of training in {{p:p-madyan|Madyan}}, all walking toward him behind one shy woman. The scholars extract the adab: he named his poverty, not his preferences; he asked the Owner, not the crowd; and he had just worked for free, so his ask stood on service, not entitlement. The Codex files this word for everyone at the bottom of a move, a loss, or a restart: the Path's proof that heaven reads unfinished sentences, and prefers them.`,
whenNow:["At any restart from nothing: new city, lost job, emptied savings",
 "After serving someone with no wage in sight: the du'a stands on service",
 "When you no longer know what to ask for: leave the field open, as he did"],
facts:[{"label":"Setting","value":"The shade after the well"},
 {"label":"Assets at the time","value":"None"},
 {"label":"Request line","value":"Left open on purpose"},
 {"label":"Fulfilled","value":"Within the scene"}],
quran:[{"ref":"28:24","ar":"رَبِّ إِنِّي لِمَا أَنزَلْتَ إِلَيَّ مِنْ خَيْرٍ فَقِيرٌ","en":"My Lord, I am, for whatever good You send down to me, in need."}]},

{id:"w-rabbishrah",titleEn:"The Commissioning Du'a",titleAr:"رَبِّ اشْرَحْ لِي صَدْرِي وَيَسِّرْ لِي أَمْرِي",translit:"Rabbi-shrah li sadri, wa yassir li amri, wahlul uqdatan min lisani, yafqahu qawli",meaning:"My Lord, expand for me my chest, ease for me my affair, and untie the knot from my tongue, that they may understand my speech",role:"The prayer before the impossible task",summary:"Assigned to Pharaoh at the burning tree, Musa asked for capacity, ease, clarity, and a partner; all granted in one sentence.",pattern:"pl-word",
details:`The assignment at {{p:p-tuwa|Tuwa}} was four words: go to Pharaoh (20:24). The response is the believer's template for every oversized task: not refusal, not bravado, but a requisition list. Capacity: expand my chest. Logistics: ease my affair. Communication: untie my tongue. Personnel: {{n:17|Harun}}, my brother, as partner. Heaven's reply compressed all grants into one line: "you have been given your request, O Musa" (20:36).

The Prophet ﷺ stood in this du'a's lineage; the expansion Musa asked for, his ummah's founder was given as surgery and as verse: "did We not expand for you your chest?" (94:1). Teachers, khatibs, parents, and anyone walking into a room bigger than their courage have used the four clauses since. The Codex notes the deep adab: Musa did not ask for the task to shrink; he asked for himself to be enlarged. The mission stayed the same size. He grew.`,
whenNow:["Before any speech, class, interview, or hard conversation",
 "On receiving an assignment beyond your size: ask to be enlarged, not excused",
 "When bringing a partner into your work, on Musa's precedent"],
facts:[{"label":"Assigned","value":"Pharaoh, at the tree"},
 {"label":"Asked for","value":"Capacity · ease · clarity · a partner"},
 {"label":"Answer","value":"“You have been given your request”"},
 {"label":"Not asked","value":"That the task shrink"}],
quran:[{"ref":"20:25-28","ar":"رَبِّ اشْرَحْ لِي صَدْرِي وَيَسِّرْ لِي أَمْرِي وَاحْلُلْ عُقْدَةً مِّن لِّسَانِي يَفْقَهُوا قَوْلِي","en":"My Lord, expand for me my chest, ease for me my affair, and untie the knot from my tongue, that they may understand my speech."}]},

{id:"w-inna-maiya",titleEn:"“My Lord Is With Me”",titleAr:"كَلَّا ۖ إِنَّ مَعِيَ رَبِّي سَيَهْدِينِ",translit:"Kalla, inna ma'iya rabbi, sayahdin",meaning:"No indeed; my Lord is with me; He will guide me",role:"Certainty at the dead end",summary:"Sea ahead, army behind, a nation panicking: Musa's answer arrived one verse before the road did.",pattern:"pl-word",
details:`At {{p:p-parted-sea|the water's edge}} the two companies sighted each other, and Bani Israel ran the numbers aloud: "we are surely overtaken" (26:61). {{n:18|Musa's}} reply is the Qur'an's cleanest specimen of iman under pressure: one refusal, one fact, one forecast. Kalla: no indeed, the premise itself rejected. Inna ma'iya rabbi: the fact that redraws every map. Sayahdin: He will guide me, future tense, spoken before any road existed. The next verse issued the road.

The Codex pairs it with its twin from {{n:33|the cave}}: "do not grieve, indeed Allah is with us" (9:40). Two dead ends, two sentences of ma'iyyah, two impossible exits: the sea stood up, and the searchers went blind at the cave mouth. The scholars distinguish the two intimacies: the general withness of knowledge over all creation, and this special withness of help for whoever stands where obedience put him. The word is for the second: whoever is cornered on the road of obedience may say the sentence with its full warranty.`,
whenNow:["At the cornered moment when the numbers are simply true and still not final",
 "Against the crowd's panic arithmetic: kalla is a complete sentence",
 "Waiting for a road that does not exist yet: sayahdin is future tense on purpose"],
facts:[{"label":"Setting","value":"Sea ahead, army behind"},
 {"label":"Structure","value":"Refusal · fact · forecast"},
 {"label":"Twin","value":"9:40, at the cave"},
 {"label":"The road","value":"Issued one verse later"}],
quran:[{"ref":"26:62","ar":"قَالَ كَلَّا ۖ إِنَّ مَعِيَ رَبِّي سَيَهْدِينِ","en":"He said: no indeed; my Lord is with me; He will guide me."}]},

{id:"w-la-tahzan",titleEn:"“Do Not Grieve”",titleAr:"لَا تَحْزَنْ إِنَّ اللَّهَ مَعَنَا",translit:"La tahzan, innallaha ma'ana",meaning:"Do not grieve; indeed Allah is with us",role:"The sentence of the cave",summary:"Whispered to one frightened friend under a hundred hunting feet, then bequeathed to every afraid believer since.",pattern:"pl-word",
details:`In {{p:p-thawr|the cave}}, with the search party's feet visible from the dark, {{c:c-abubakr|Abu Bakr's}} fear was for his companion, not himself. The reassurance he received became scripture: "do not grieve; indeed Allah is with us" (9:40), and in Bukhari's wording a question that ended the mathematics of danger: "what do you think, O Abu Bakr, of two, Allah is their third?"

The grammar rewards attention: la tahzan addresses grief, not the enemy; the danger is not denied, it is outranked. And the basis is not a prediction ("we will escape") but a presence ("Allah is with us"): true even if they had been found, which is why the sentence never expires. The Codex keeps it beside {{w:w-inna-maiya|Musa's kalla}} as the second of the two great ma'iyyah sentences, and notes where else the Book deploys the phrase: to the Prophet at large, "do not grieve over them" (16:127), and to every believer against the whisperer's sorrow-campaigns, "grief is only from shaytan... and in Allah let the believers put their trust" (58:10).`,
whenNow:["To a frightened friend: its original use, secondhand comfort with a warranty",
 "In hiding, waiting, or pursuit of any kind: the third of every two is unchanged",
 "Against engineered sadness: 58:10 names grief as a weapon; this word disarms it"],
facts:[{"label":"Setting","value":"Thawr, feet overhead"},
 {"label":"Addresses","value":"The grief, not the enemy"},
 {"label":"Basis","value":"Presence, not prediction"},
 {"label":"The arithmetic","value":"Two, Allah their third"}],
quran:[{"ref":"9:40","ar":"إِذْ يَقُولُ لِصَاحِبِهِ لَا تَحْزَنْ إِنَّ اللَّهَ مَعَنَا","en":"When he said to his companion: do not grieve; indeed Allah is with us."}],
hadith:[{"text":"What do you think, O Abu Bakr, of two, Allah is their third?","source":"Bukhari 3653 · Muslim 2381"}]},

{id:"w-taif-dua",titleEn:"The Complaint of the Weak",titleAr:"اللَّهُمَّ إِلَيْكَ أَشْكُو ضَعْفَ قُوَّتِي",translit:"Allahumma ilayka ashku da'fa quwwati, wa qillata hilati, wa hawani 'alan-nas",meaning:"O Allah, to You I complain of my weakness, my scarcity of means, and my insignificance before people",role:"The prayer of the worst day",summary:"Bleeding outside Ta'if's wall, the Prophet ﷺ audited only one thing: whether his Lord was displeased.",pattern:"pl-word",
details:`After {{n:30|the stoning at Ta'if}}, in Utbah's orchard with blood reaching his sandals, the Prophet ﷺ raised the complaint the sirah has preserved as the ummah's property in catastrophe. Its clauses take inventory honestly: weakness, scarcity, insignificance. Its pivot is the question that reorders every disaster: "if You are not angry with me, I do not care." And its refuge is total: "I seek refuge in the light of Your Face... to You belongs all appeal until You are pleased."

The report reaches us through the sirah literature (at-Tabarani; the chain is graded weak by the muhaddithin, and the Codex says so), but its acceptance among the scholars of the heart is ancient, and the day itself is anchored in the Sahih: Aisha asked about the hardest day, and he named {{n:30|the day of Ta'if}}, answered at last by {{c:a-mountains|the Angel of the Mountains}} (Bukhari 3231). Heaven's reply to this complaint is on the record: an angel awaiting orders, and a prophet choosing mercy. Whoever prays these words is in the safest lineage of the broken.`,
whenNow:["On the day people's contempt is the wound: hawani 'alan-nas names it",
 "When strength, means, and status all fail at once: the honest inventory",
 "When one question matters more than rescue: are You pleased with me?"],
facts:[{"label":"Day","value":"The hardest, by his ﷺ word"},
 {"label":"Pivot","value":"“If You are not angry, I do not care”"},
 {"label":"Chain","value":"Sirah; graded weak, noted"},
 {"label":"Answered by","value":"The Angel of the Mountains"}],
hadith:[{"text":"Aisha asked: was there a day harder than Uhud? He said: I met from your people what I met, and the hardest was the day of Aqabah (Ta'if).","source":"Bukhari 3231 · Muslim 1795"}]},

{id:"w-sallim",titleEn:"“Allahumma Sallim, Sallim”",titleAr:"اللَّهُمَّ سَلِّمْ سَلِّمْ",translit:"Allahumma sallim, sallim",meaning:"O Allah, bring them through safely, bring them through",role:"The prophets' entire vocabulary at the bridge",summary:"On the Sirat, over the Fire, the messengers who split seas will be saying two words on behalf of the crossers.",pattern:"pl-word",
details:`When {{n:63|the bridge}} is laid over Jahannam's back, sharper than a sword, hooked with sa'dan thorns, crossed at the speed of deeds, the sound tradition records the only speech on it: "none speaks that day but the messengers, and the du'a of the messengers is: Allahumma sallim, sallim" (Bukhari 806, Muslim 182). The men who stood before Pharaoh, cooled in the fire, and fed multitudes from a handful are reduced, at that crossing, to two words, repeated, for others.

The Codex keeps this word for two disciplines. First, proportion: whoever wants to know the Sirat's gravity should weigh what it does to the vocabulary of prophets. Second, direction: even at the rail of the Fire, the prophetic instinct is intercession, sallim for the crossers, not commentary on the falling. The ummah rehearses the word every time it prays for safety in this world's crossings; the full performance is scheduled over the Fire, and the wise pack light for it: light is earned now, "their light running before them" (57:12).`,
whenNow:["At every dangerous crossing of this world: roads, surgeries, verdicts",
 "Praying for others in peril: the prophetic instinct at the rail",
 "Remembering the bridge in comfort: the word keeps the crossing real"],
facts:[{"label":"Where","value":"On the Sirat itself"},
 {"label":"Speakers","value":"Only the messengers"},
 {"label":"Full text","value":"Two words, repeated"},
 {"label":"Direction","value":"For others, always"}],
hadith:[{"text":"None speaks that day but the messengers, and the du'a of the messengers is: O Allah, bring through, bring through.","source":"Bukhari 806 · Muslim 182"}]},

{id:"w-subhan",titleEn:"The Two Light-Heavy Words",titleAr:"سُبْحَانَ اللَّهِ وَبِحَمْدِهِ سُبْحَانَ اللَّهِ الْعَظِيمِ",translit:"Subhanallahi wa bihamdih, subhanallahil-azim",meaning:"Glory to Allah and praise Him; glory to Allah the Magnificent",role:"The best-priced deed in existence",summary:"Light on the tongue, heavy on the Scale, beloved to the Most Merciful: the closing hadith of Sahih al-Bukhari.",pattern:"pl-word",
details:`Imam al-Bukhari sealed his entire Sahih, seven thousand hadith of law, war, and revelation, with this one: "two words, light on the tongue, heavy on the Scale, beloved to the Most Merciful: subhanallahi wa bihamdih, subhanallahil-azim" (Bukhari 7563, Muslim 2694). The scholars read the placement as the muhaddith's last word on what a life is for.

At {{n:62|the Mizan}}, where a mustard seed is admissible evidence, density matters more than volume, and these clauses are the tradition's densest alloy: tanzih (He is beyond flaw) fused with hamd (He is owed praise), twice, in different registers. The price list around them is published: whoever says subhanallahi wa bihamdih a hundred times a day has his sins removed though they be like the sea's foam (Bukhari 6405); a palm is planted in Jannah for each saying (Tirmidhi 3464). The Codex files this word where the reader can reach it in traffic: the highest-yield real estate on the Scale costs four seconds of tongue.`,
whenNow:["A hundred times a day: sea-foam clause (Bukhari 6405)",
 "In the dead minutes: queues, traffic, kettle-time; the deed fits anywhere",
 "As a settled morning-evening anchor with the other adhkar"],
facts:[{"label":"Weight class","value":"Heavy on the Scale"},
 {"label":"Cost","value":"Light on the tongue"},
 {"label":"Beloved to","value":"The Most Merciful"},
 {"label":"Placement","value":"Bukhari's final hadith"}],
hadith:[{"text":"Two words, light on the tongue, heavy on the Scale, beloved to the Most Merciful: subhanallahi wa bihamdih, subhanallahil-azim.","source":"Bukhari 7563 · Muslim 2694"}]},

{id:"w-shahada",titleEn:"The Word Itself",titleAr:"لَا إِلَٰهَ إِلَّا اللَّهُ مُحَمَّدٌ رَسُولُ اللَّهِ",translit:"La ilaha illallah, Muhammadur-rasulullah",meaning:"None has the right to be worshipped but Allah; Muhammad is the Messenger of Allah",role:"The sentence the Codex orbits",summary:"The best thing said by him ﷺ and the prophets before him; the card that outweighs ninety-nine scrolls.",pattern:"pl-word",
details:`Every node of the Path is this sentence in costume. It is what {{n:9|Ibrahim}} argued from the stars, what {{n:29|Iqra's}} garment-wrapped man rose to announce, what {{n:41|the Opening}} installed over the emptied idols, and what {{c:c-bilal|Bilal}} compressed under the boulder into Ahad, Ahad. The Prophet ﷺ ranked it at {{p:p-arafat|Arafat}}: "the best of what I and the prophets before me have said is: la ilaha illallah, alone, without partner" (Muwatta; Tirmidhi 3585).

Its performance at {{n:62|the Scale}} is documented in the bitaqa hadith: ninety-nine scrolls of sin against one card bearing the two testimonies, "and the scrolls fly up, and the card outweighs; nothing outweighs the name of Allah" (Tirmidhi 2639, sahih). Its performance at the deathbed is commissioned in advance: "whoever's last words are la ilaha illallah enters Jannah" (Abu Dawud 3116). The Codex's whole architecture, sixty-four tiles and every seal, is commentary; this word is the text.`,
whenNow:["Renewing iman in the ordinary afternoon: the best dhikr outright",
 "Teaching it as the first sentence and praying it as the last",
 "One hundred times daily in the tahlil formula: Muslim 2691's fortress"],
facts:[{"label":"Rank","value":"Best said by all prophets"},
 {"label":"At the Scale","value":"Outweighs 99 scrolls"},
 {"label":"At the end","value":"Last words: Jannah"},
 {"label":"In the Codex","value":"Every tile is its commentary"}],
hadith:[{"text":"The scrolls fly up and the card outweighs; nothing outweighs the name of Allah.","source":"Tirmidhi 2639 (sahih)"}]},

{id:"w-adhan-dua",titleEn:"The Du'a After the Adhan",titleAr:"اللَّهُمَّ رَبَّ هَذِهِ الدَّعْوَةِ التَّامَّةِ",translit:"Allahumma rabba hadhihid-da'watit-tammah... ab'ath-hu maqamam-mahmudan alladhi wa'adtah",meaning:"O Allah, Lord of this perfect call... raise him to the praised station You promised him",role:"A daily ballot for the Great Intercession",summary:"Thirty seconds after every adhan, the ummah nominates its Prophet for the station he will hold on the Day.",pattern:"pl-word",
details:`Five times daily the call ends, and the sunnah opens a thirty-second window with an eternal payout: "whoever says, when he hears the call: O Allah, Lord of this perfect call and the established prayer, give Muhammad the wasilah and the excellence, and raise him to the praised station You promised him; my intercession becomes lawful for him on the Day of Rising" (Bukhari 614).

The praised station is {{n:60|al-Maqam al-Mahmud}} of 17:79: the Great Intercession, when the species' file passes from prophet to prophet and stops at "I am for it." The du'a's mechanism moves in two directions at once: the sayer asks elevation for the Prophet ﷺ, and the Prophet's intercession is secured for the sayer. The wasilah itself, he explained, is a rank in Jannah fitting only one servant, "and I hope that I am he" (Muslim 384): even at the summit, the grammar of hope. The Codex files this word as its most practical link: one tile of the Nihaya, wired to a habit five minutes from now.`,
whenNow:["After every adhan: the window is short and the clause is explicit",
 "Adding the salawat first, as Muslim 384 sequences it",
 "Teaching children the meaning: they are voting daily for their Prophet"],
facts:[{"label":"Window","value":"After each adhan"},
 {"label":"Secures","value":"His ﷺ intercession, by text"},
 {"label":"Refers to","value":"Maqam Mahmud (17:79)"},
 {"label":"His hope","value":"“I hope that I am he”"}],
hadith:[{"text":"Whoever says it when he hears the call, my intercession becomes lawful for him on the Day of Rising.","source":"Bukhari 614"}]},

{id:"w-sayyid-istighfar",titleEn:"Sayyid al-Istighfar",titleAr:"اللَّهُمَّ أَنْتَ رَبِّي لَا إِلَٰهَ إِلَّا أَنْتَ خَلَقْتَنِي وَأَنَا عَبْدُكَ",translit:"Allahumma anta rabbi, la ilaha illa ant, khalaqtani wa ana abduk...",meaning:"O Allah, You are my Lord; none has the right to be worshipped but You; You created me and I am Your servant...",role:"The master formula of forgiveness",summary:"Covenant renewed, blessing acknowledged, sin confessed: said with certainty, it prices a day at Jannah.",pattern:"pl-word",
details:`The Prophet ﷺ titled one du'a himself: sayyid al-istighfar, the master of seeking forgiveness. Its clauses move like a legal renewal: identity (You are my Lord, I am Your servant), covenant (I am upon Your promise and pledge as I am able), refuge (from the evil of what I have made), audit (I acknowledge Your blessing upon me, and I acknowledge my sin), and the closing that names the monopoly: "forgive me, for none forgives sins but You" (Bukhari 6306).

The guarantee attached is timed like a shift schedule: whoever says it in the day with certainty and dies before evening is of the people of Jannah, and whoever says it at night with certainty and dies before morning, the same. Certainty is the active ingredient; the words are its carrier. The scholars loved its balance: no despair (blessing acknowledged first) and no delusion (sin acknowledged next). The Codex sets it beside {{w:w-rabbana-zalamna|Adam's words}} as the matured form of the same species: mankind's first confession, grown into a daily covenant.`,
whenNow:["Morning and evening, with certainty: the shift-schedule guarantee",
 "As the day's reset after the audit clauses: blessing, then sin, in order",
 "Memorized once, owned for life: the master key stays cut"],
facts:[{"label":"Titled by","value":"Him ﷺ: the master"},
 {"label":"Guarantee","value":"Jannah, by shift"},
 {"label":"Active ingredient","value":"Certainty (muqin)"},
 {"label":"Structure","value":"Covenant renewal"}],
hadith:[{"text":"Whoever says it during the day, certain of it, and dies that day before evening, he is of the people of Jannah.","source":"Bukhari 6306"}]},

{id:"w-hawqala",titleEn:"La Hawla wa la Quwwata illa Billah",titleAr:"لَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللَّهِ",translit:"La hawla wa la quwwata illa billah",meaning:"There is no power to change and no strength except by Allah",role:"A treasure from the treasures of Jannah",summary:"The Prophet ﷺ stopped Abu Musa on the road to hand him this sentence and name its vault.",pattern:"pl-word",
details:`On a journey, as the companions' takbir rose loud on the climbs, the Prophet ﷺ first taught volume ("you are not calling upon someone deaf or absent"), then pulled Abu Musa al-Ash'ari close for a private transfer: "shall I not point you to a treasure from the treasures of Jannah? La hawla wa la quwwata illa billah" (Bukhari 4205, Muslim 2704).

The sentence is a complete audit of causality: no shifting of any state and no force to sustain one, except by Him. The scholars unpack its uses along that line: said at the muadhdhin's "hayya alas-salah" because even walking to prayer needs His power; said at overwhelming tasks because it disclaims self-sufficiency before asking; said at helplessness because it relocates the levers. A treasure of Jannah, Ibn Hajar notes, means a reward stored where nothing spoils. The Codex banks it beside {{w:w-subhan|the two light-heavy words}}: the tradition's liquid assets, available to any tongue, in any traffic, at zero cost and vault-grade yield.`,
whenNow:["Answering the muadhdhin at the two hayya clauses",
 "At the too-heavy task and at the immovable circumstance",
 "As stored treasure: said now, banked where nothing spoils"],
facts:[{"label":"Named","value":"A treasure of Jannah"},
 {"label":"Given to","value":"Abu Musa, on the road"},
 {"label":"Discipline","value":"Complete causality audit"},
 {"label":"Cost","value":"One breath"}],
hadith:[{"text":"Shall I not point you to a treasure from the treasures of Jannah? La hawla wa la quwwata illa billah.","source":"Bukhari 4205 · Muslim 2704"}]},

{id:"w-salawat",titleEn:"As-Salat al-Ibrahimiyyah",titleAr:"اللَّهُمَّ صَلِّ عَلَىٰ مُحَمَّدٍ وَعَلَىٰ آلِ مُحَمَّدٍ كَمَا صَلَّيْتَ عَلَىٰ إِبْرَاهِيمَ",translit:"Allahumma salli 'ala Muhammadin wa 'ala ali Muhammad, kama sallayta 'ala Ibrahim...",meaning:"O Allah, send Your salat upon Muhammad and the family of Muhammad, as You sent it upon Ibrahim...",role:"The bridge between the two Friends",summary:"Every tashahhud joins the final Prophet to the first Khalil; one saying returns ten from Allah.",pattern:"pl-word",
details:`When the companions asked how to send salat upon him ﷺ, the answer he taught wove {{n:9|Ibrahim}} into every prayer of this ummah until the end of time (Bukhari 3370): the Friend who built {{p:p-kaaba|the House}} and asked for {{n:11|a messenger from his descendants}}, invoked in the very worship of the community that answered his du'a. The Codex reads the salawat as the Path folded into a sentence: from Khalil to Habib, one line of light.

The economics are published: "whoever sends salat upon me once, Allah sends salat upon him ten times" (Muslim 408). The nearest people to him on the Day are those who said it most (Tirmidhi 484); Fridays carry a standing order for increase; and du'a itself is taught to travel wrapped in it. One meeting of the tradition prices a whole portfolio: a man offered his entire du'a time as salawat, and was told: "then your concern will be sufficed and your sin forgiven" (Tirmidhi 2457, hasan). The Codex files this word as its own signature: the reader who finishes any tile has one obvious next deed.`,
whenNow:["In every tashahhud: the appointed place",
 "Fridays, abundantly: the day of increase",
 "Wrapping any du'a: it travels accepted company"],
facts:[{"label":"Joins","value":"Muhammad ﷺ & Ibrahim"},
 {"label":"Exchange rate","value":"1 → 10 from Allah"},
 {"label":"Nearest on the Day","value":"The most frequent sayers"},
 {"label":"Friday","value":"Standing order of increase"}],
hadith:[{"text":"Whoever sends salat upon me once, Allah sends salat upon him ten times.","source":"Muslim 408"}]},

{id:"w-rabbana-atina",titleEn:"The Balanced Request",titleAr:"رَبَّنَا آتِنَا فِي الدُّنْيَا حَسَنَةً وَفِي الْآخِرَةِ حَسَنَةً وَقِنَا عَذَابَ النَّارِ",translit:"Rabbana atina fid-dunya hasanah, wa fil-akhirati hasanah, wa qina 'adhaban-nar",meaning:"Our Lord, give us good in this world and good in the Hereafter, and protect us from the punishment of the Fire",role:"The Prophet's ﷺ most frequent du'a",summary:"Both worlds in one breath, revealed among the rites of Hajj as the correction of one-world asking.",pattern:"pl-word",
details:`The verse arrived as a correction of scope: among the pilgrims of {{n:44|the Hajj}} were those who asked only, "our Lord, give us in this world," and the Book noted their balance sheet: "and he has no share in the Hereafter" (2:200). The believers' formula follows in the next verse, and Anas testified to its rank in the Prophet's ﷺ own usage: "the most frequent supplication of the Prophet was: our Lord, give us good in this world and good in the Hereafter, and protect us from the punishment of the Fire" (Bukhari 6389, Muslim 2690).

Its genius is its refusal to itemize: hasanah in this world covers health, spouse, provision, and every unnamed need, the mufassirun say, and hasanah in the next covers everything from the grave to {{n:64|the Vision}}. He ﷺ used it as the pilgrims' litany between the Corner and the Corner, and as the summary when a wasted man asked for his punishment early (Muslim 2688): do not ask for the load, ask for the balance. The Codex closes its Words section on this one because the Path itself is its shape: a dunya walked well, an akhirah reached safe, and the Fire skipped.`,
whenNow:["As the backbone du'a of every sitting: his ﷺ most frequent",
 "Between the Yemeni Corner and the Black Stone, its tawaf station",
 "Whenever asking feels too complicated: two goods and one protection"],
facts:[{"label":"Rank","value":"His most frequent du'a ﷺ"},
 {"label":"Scope","value":"Both worlds + the Fire skipped"},
 {"label":"Revealed among","value":"The rites of Hajj (2:200-201)"},
 {"label":"Tawaf station","value":"Corner to Corner"}],
quran:[{"ref":"2:201","ar":"رَبَّنَا آتِنَا فِي الدُّنْيَا حَسَنَةً وَفِي الْآخِرَةِ حَسَنَةً وَقِنَا عَذَابَ النَّارِ","en":"Our Lord, give us good in this world and good in the Hereafter, and protect us from the punishment of the Fire."}]},

{id:"w-inna-lillah",titleEn:"The Words of Loss",titleAr:"إِنَّا لِلَّهِ وَإِنَّا إِلَيْهِ رَاجِعُونَ",translit:"Inna lillahi wa inna ilayhi raji'un",meaning:"Indeed we belong to Allah, and indeed to Him we return",role:"Ownership, stated at the moment of loss",summary:"Umm Salamah said it over her husband's death, added the taught du'a, and was compensated with the Prophet ﷺ himself.",pattern:"pl-word",
details:`The Qur'an assigns these words to one moment: "who, when calamity strikes them, say: indeed we belong to Allah, and indeed to Him we return" (2:156), and prices them in the next verse: salawat from their Lord, and mercy, "and it is they who are guided." The sentence is not resignation; it is a title deed read aloud: the lost thing was never owned, and the destination was never in doubt.

{{c:c-umm-salamah|Umm Salamah}} ran the experiment at the hardest bench. Her husband, wounded at {{n:38|Uhud}}, died; she said the istirja and the addition the Prophet ﷺ had taught: "O Allah, reward me in my calamity and replace it for me with better." She admitted her own doubt in the narration: who could be better than Abu Salamah? "Then Allah replaced him for me with the Messenger of Allah ﷺ" (Muslim 918). The Codex keeps her file attached to the formula permanently: the words work above the sayer's imagination, and the replacement clause is signed by the One who owns both what left and what arrives.`,
whenNow:["At every loss, large or small: the deed is read aloud, then the heart follows",
 "With the addition: “reward me in it and replace it with better” (Muslim 918)",
 "Teaching it before the losses come: the sentence is learned in calm"],
facts:[{"label":"Verse","value":"2:156, with its price"},
 {"label":"Nature","value":"A title deed, not resignation"},
 {"label":"Case study","value":"Umm Salamah (Muslim 918)"},
 {"label":"Replacement","value":"Above imagination"}],
quran:[{"ref":"2:156-157","ar":"الَّذِينَ إِذَا أَصَابَتْهُم مُّصِيبَةٌ قَالُوا إِنَّا لِلَّهِ وَإِنَّا إِلَيْهِ رَاجِعُونَ","en":"Who, when calamity strikes them, say: indeed we belong to Allah, and indeed to Him we return."}],
hadith:[{"text":"O Allah, reward me in my calamity and replace it for me with better. Then Allah replaced him for me with the Messenger of Allah ﷺ.","source":"Muslim 918"}]}
]
};
