// NOOR Characters v2 (A): rewrite the 13 original Companions to flagship standard + 20 new Companions.
// No em dashes anywhere. Every hadith carries its collection.
export default {

replaceCharacters:{

"c-abubakr":{
role:"As-Siddiq · First caliph · Companion of the cave",
summary:"The first free man to believe, the second of two in the cave, and the hand that held the ummah together on its hardest morning.",
details:`Abu Bakr Abdullah ibn Abi Quhafah heard the message and did not negotiate with it. The Prophet ﷺ said of him: "I never invited anyone to Islam but he had some hesitation, except Abu Bakr." His belief pulled a generation behind him: {{c:c-uthman|Uthman}}, {{c:c-talha|Talha}}, {{c:c-zubayr|Zubayr}}, {{c:c-saad|Sa'd}}, and {{c:c-abdurrahman|Ibn Awf}} all entered Islam at his hands. When Makkah mocked {{n:31|the Night Journey}}, he answered with the sentence that earned his title: "If he said it, he has told the truth." From that day he was as-Siddiq.

He bought and freed the tortured, {{c:c-bilal|Bilal}} first among them. He was the companion of {{n:33|the cave}}, the second of two when Allah was the third. He led the prayer in the Prophet's final illness, and when {{n:45|the hardest morning}} came, he held the community upright with two sentences about the Living God. As caliph for two years he fought the riddah, sent Usama's army as commanded, and began gathering the Qur'an after Yamamah. The Prophet ﷺ said: "If I were to take an intimate friend other than my Lord, I would take Abu Bakr." He died asking to be buried beside his beloved, and he was.`,
facts:[{label:"Title",value:"As-Siddiq, after the Isra"},{label:"The cave",value:"Second of two (9:40)"},{label:"Freed",value:"Bilal and the tortured"},{label:"Caliphate",value:"2 years: riddah, Qur'an gathered"}],
quran:[{ref:"9:40",ar:"ثَانِيَ اثْنَيْنِ إِذْ هُمَا فِي الْغَارِ إِذْ يَقُولُ لِصَاحِبِهِ لَا تَحْزَنْ إِنَّ اللَّهَ مَعَنَا",en:"The second of two, when they were in the cave, when he said to his companion: do not grieve, indeed Allah is with us."}],
hadith:[{text:"If I were to take an intimate friend (khalil) other than my Lord, I would take Abu Bakr.",source:"Bukhari 3656 · Muslim 2382"}]},

"c-umar":{
role:"Al-Faruq · Second caliph",
summary:"His Islam was a conquest, his justice a proverb, and shaytan took the other road when he walked.",
details:`Umar ibn al-Khattab set out one day to kill the Prophet ﷺ and arrived instead at his sister's house, where Surah Ta-Ha was being recited in the home of {{c:c-said-zayd|Sa'id ibn Zayd}}. He read, trembled, and walked to the house of al-Arqam to pledge. The Muslims prayed openly at the Kaaba for the first time behind his shoulders. The Prophet named him al-Faruq, the one who splits truth from falsehood, and said: "By the One in whose hand is my soul, shaytan never meets you traveling on a road but he takes a road other than yours."

At {{n:44|the Farewell Hajj}} he understood the verse of completion and wept. After {{n:45|the Passing}} his drawn grief was steadied by {{c:c-abubakr|Abu Bakr}}, whom he served, then succeeded. His ten years opened al-Quds, Persia, Egypt and Sham; he took the title Amir al-Mu'minin, established the diwan and the Hijri calendar, patrolled Madinah at night carrying flour on his own back, and fixed {{n:33|the Hijrah}} as year one. He asked Allah for martyrdom in the Prophet's city and received both: struck at Fajr in his own mihrab, buried beside the two he loved.`,
facts:[{label:"Title",value:"Al-Faruq · Amir al-Mu'minin"},{label:"Converted at",value:"Ta-Ha, his sister's house"},{label:"Opened",value:"Al-Quds · Persia · Egypt · Sham"},{label:"Calendar",value:"Hijrah = year one"},{label:"End",value:"Martyred at Fajr, buried with the two"}],
hadith:[{text:"Shaytan never meets you traveling on a road but he takes a road other than yours.",source:"Bukhari 3683 · Muslim 2396"},{text:"In the nations before you there were inspired men (muhaddathun); if there is one in my ummah, it is Umar.",source:"Bukhari 3689 · Muslim 2398"}]},

"c-uthman":{
role:"Dhun-Nurayn · Third caliph",
summary:"Married two daughters of the Prophet ﷺ, financed the hard hours, and gave the ummah one written Qur'an.",
details:`Uthman ibn Affan was wealth wedded to shyness. The Prophet ﷺ said: "Shall I not feel shy before a man before whom the angels feel shy?" He married Ruqayyah, led an emigration to Abyssinia with her, and after her death married her sister Umm Kulthum: two lights, Dhun-Nurayn. His money moved the story at its hinges: he bought the well of Rumah and made it public water, and he equipped {{n:43|the army of hardship}} until the Prophet said nothing would harm him after that day. At {{n:40|Hudaybiyyah}} he was the envoy into Makkah, and the false report of his death triggered the Pledge under the tree; the Prophet pledged for him with his own left hand, calling it Uthman's hand.

As third caliph he expanded the two sanctuaries and, when recitation disputes spread with the conquests, commissioned the single written mushaf from the compilation kept since {{c:c-abubakr|Abu Bakr}}, sending copies to the garrison cities. Every printed Qur'an on earth descends from that decision. Besieged in his house in the first fitnah, he refused to shed Muslim blood in his defense and was killed while reciting; the tradition remembers his blood on the Book he unified.`,
facts:[{label:"Title",value:"Dhun-Nurayn, two lights"},{label:"Tabuk",value:"Financed the hardship army"},{label:"Hudaybiyyah",value:"The envoy; pledge made for him"},{label:"Legacy",value:"The single written mushaf"}],
hadith:[{text:"Shall I not feel shy before a man before whom the angels feel shy?",source:"Muslim 2401"},{text:"Nothing will harm Uthman after what he has done today.",source:"Tirmidhi 3701 (hasan)"}]},

"c-ali":{
role:"Fourth caliph · Gate of the city of knowledge",
summary:"Raised in the Prophet's ﷺ house, slept in his bed on the night of the knives, carried the banner at Khaybar.",
details:`Ali ibn Abi Talib grew up in the household of the Prophet ﷺ and believed as a boy, among the very first. On the night of {{n:33|the Hijrah}} he lay in the Prophet's bed under the green cloak while the swordsmen watched the door, then stayed behind to return Makkah's deposits: the assassins' own valuables, held in trust by the man they wanted dead. He fought at {{n:37|Badr}} and {{n:38|Uhud}}, and at Khaybar the Prophet said: "Tomorrow I will give the banner to a man who loves Allah and His Messenger, and whom Allah and His Messenger love," then gave it to Ali. At {{n:43|Tabuk}} he heard the words that fixed his rank: "You are to me as Harun was to Musa, except that there is no prophet after me."

He married {{c:c-fatimah|Fatimah}}; from them came {{c:c-hasan|al-Hasan}} and {{c:c-husayn|al-Husayn}}, the two masters of the youth of Jannah. His judgments made Umar seek him; his sermons trained the Arabic tongue. As fourth caliph he carried the community through its bitterest years, and was struck by a Kharijite's blade at Fajr in Kufa. Sunni and Shi'i memory both orbit him; the Codex records the love and the rank on which all agree.`,
facts:[{label:"First",value:"Among the first to believe, as a boy"},{label:"Hijrah night",value:"The decoy in the bed"},{label:"Khaybar",value:"The banner given to him"},{label:"Rank",value:"As Harun to Musa (Bukhari 4416)"}],
hadith:[{text:"Tomorrow I will give the banner to a man who loves Allah and His Messenger, and whom Allah and His Messenger love.",source:"Bukhari 3702 · Muslim 2407"}]},

"c-khadijah":{
role:"First believer · Umm al-Mu'minin",
summary:"She believed before anyone, spent everything, and received salam from her Lord and a house of qasab in Jannah.",
details:`Khadijah bint Khuwaylid ran her own caravans in a city that buried daughters. She hired the young Muhammad ﷺ for trade, read his character, and proposed. For twenty-five years she was his only wife and the mother of every child of his except Ibrahim. When he came down from {{n:29|Hira}} trembling, she wrapped him and argued from evidence: Allah would never disgrace a man who keeps ties, carries the weak, earns for the destitute, honors the guest, and helps against the blows of truth. Then she took him to {{c:c-waraqah|Waraqah}}. She was the first human being to believe.

Her wealth absorbed the boycott years; her certainty absorbed the doubt. In {{n:30|the Year of Sorrow}} she died, and Makkah's roof over the message fell with her. Years later the Prophet ﷺ would still send gifts to her friends, and when her sister's voice reached him at the door his heart shook. {{c:a-jibril|Jibril}} came to him once with word from heaven: give Khadijah salam from her Lord, and give her glad tidings of a house in Jannah of qasab, in which there is no noise and no fatigue.`,
facts:[{label:"Rank",value:"First to believe"},{label:"Marriage",value:"25 years, his only wife"},{label:"Greeted by",value:"Her Lord, through Jibril"},{label:"In Jannah",value:"A house of qasab"}],
hadith:[{text:"Give Khadijah glad tidings of a house in Jannah of qasab, in which there is no noise and no fatigue.",source:"Bukhari 3820 · Muslim 2432"}]},

"c-aisha":{
role:"Umm al-Mu'minin · Jurist of the ummah",
summary:"The most knowledgeable woman of this ummah; a third of the household rulings of the religion reach us through her.",
details:`Aisha bint Abi Bakr, daughter of {{c:c-abubakr|as-Siddiq}}, was the most beloved of the Prophet's ﷺ wives after Khadijah's era. Asked publicly who was dearest to him, he answered: "Aisha," and of men, "her father." Revelation came to him under no wife's blanket but hers, and he ﷺ said: "The superiority of Aisha over women is like the superiority of tharid over other food." When the slanderers attacked her honor in the affair of the ifk, heaven itself acquitted her: verses of Surah an-Nur recited until the Day of Judgment.

Her chamber was the classroom of the ummah. More than two thousand hadith reach us through her; the great companions returned to her for inheritance law, for the Prophet's night prayer, for the description of his character, which she summarized in four words: his character was the Qur'an. He ﷺ died with his head against her chest, in her turn, in {{n:45|her room}}, and was buried there. She lived on for decades as teacher and corrector of the ummah's memory, and her regret over the day of the Camel deepened her students' love. The Codex records her as the proof that the transmission of this religion stands on a woman's scholarship.`,
facts:[{label:"Hadith",value:"2,200+ narrations"},{label:"Acquitted by",value:"Revelation (24:11-20)"},{label:"His answer",value:"Dearest: Aisha; of men: her father"},{label:"His last hour",value:"Against her chest, in her room"}],
hadith:[{text:"The superiority of Aisha over women is like the superiority of tharid over other food.",source:"Bukhari 3770 · Muslim 2446"}]},

"c-hamza":{
role:"Asadullah · Master of the martyrs",
summary:"The Prophet's ﷺ uncle and shield, killed at Uhud; the Lion of Allah and of His Messenger.",
details:`Hamza ibn Abd al-Muttalib, uncle of the Prophet ﷺ and his milk-brother, was Makkah's hunter and strongest arm. The day Abu Jahl abused the Prophet at Safa, Hamza came back from the hunt, struck Abu Jahl with his bow before the assembly, and declared himself on his nephew's religion; the persecutors recalculated that week. He fought at {{n:37|Badr}} with a distinction the enemy remembered by the ostrich feather he wore, and at {{n:38|Uhud}} he fell: {{c:c-wahshi|Wahshi's}} javelin, thrown for a bounty set by {{c:c-hind|Hind}}, whose men of Badr he had helped cut down.

What was done to his body after death grieved the Prophet ﷺ beyond any other loss of the day, and revelation and his own mercy sealed the response at {{n:41|the Opening}}: no revenge, and mutilation forbidden in this ummah forever. He was buried at Uhud with the martyrs, where his grave is greeted to this day. The Prophet called him Sayyid ash-Shuhada, the master of the martyrs, and the Lion of Allah. In the Codex he stands where courage and restraint meet: the man whose death taught the ummah how not to avenge.`,
facts:[{label:"Title",value:"Lion of Allah · Sayyid ash-Shuhada"},{label:"Islam",value:"Declared with a bowstrike at Safa"},{label:"Fell at",value:"Uhud, 3 AH"},{label:"Legacy",value:"Mutilation forbidden forever"}],
hadith:[{text:"The master of the martyrs is Hamza ibn Abd al-Muttalib.",source:"al-Hakim (hasan) · cf. Bukhari 4072 for his death"}]},

"c-bilal":{
role:"First mu'adhdhin of Islam",
summary:"Tortured under the rock saying Ahad, Ahad; his footsteps were heard in Jannah before he died.",
details:`Bilal ibn Rabah, an Abyssinian slave, believed early and paid immediately. Umayyah ibn Khalaf staked him on the burning sand under a boulder, demanding he curse the Prophet ﷺ; the whole theology of Islam compressed into his two-word answer: Ahad, Ahad. One. One. {{c:c-abubakr|Abu Bakr}} bought him and freed him for Allah.

In Madinah the Prophet chose his voice for the first adhan, and for a decade Bilal called the ummah to prayer, stood at the Prophet's door, and carried his short spear before him at the Eids. On the day of {{n:41|the Opening}} the Prophet ordered him up onto the roof of the Kaaba itself, and the freed slave gave the adhan over the heads of the aristocracy that had tortured him. The Prophet ﷺ asked him once: "Tell me the deed you hope in most, for I heard the sound of your footsteps ahead of me in Jannah." He answered: I never purify myself, night or day, except that I pray with that purification what was written for me. After {{n:45|the Passing}} the adhan broke him; he could not finish it, and left for Sham as a soldier, giving one last adhan in his life that made Madinah weep.`,
facts:[{label:"Trial",value:"The boulder: Ahad, Ahad"},{label:"Freed by",value:"Abu Bakr"},{label:"Office",value:"First mu'adhdhin"},{label:"Heard in Jannah",value:"His footsteps, before death"}],
hadith:[{text:"I heard the sound of your footsteps ahead of me in Jannah.",source:"Bukhari 1149 · Muslim 2458"}]},

"c-salman":{
role:"The Seeker · Counsel of the Trench",
summary:"Sold into slavery searching for one man; found him, freed himself by planting three hundred palms, and saved a city with a ditch.",
details:`Salman al-Farisi began as a Persian nobleman's son keeping the sacred fire, and left it for a church, then for teacher after teacher across Syria and Anatolia, each dying master pointing him onward, the last one telling him the signs: a prophet of the final religion, arising among the Arabs, who accepts the gift but not the charity, with the seal of prophethood between his shoulders. Kidnapped and sold into slavery in Yathrib, he was pruning palms when Madinah rang with the arrival of {{n:36|the emigrant}}. He tested the three signs one by one; at the third, he wept and embraced Islam. The Prophet ﷺ arranged his freedom: three hundred palm shoots, planted by the Prophet's own hands, and every one of them took root.

At {{n:39|the Trench}} his Persian engineering met Arabia's crisis: dig, he said, and the ummah dug. The Muhajirun and Ansar each claimed him, and the Prophet closed the auction with the sentence that ended ethnicity as rank: "Salman is from us, the People of the House." He governed al-Mada'in in Persia, the land of his birth, on a stipend he gave away, weaving palm leaves for his bread. The seeker's file is the Codex's proof that whoever walks toward the truth, the truth walks toward him.`,
facts:[{label:"Journey",value:"Persia → churches of Sham → slavery → Madinah"},{label:"Freedom price",value:"300 palms, planted by him ﷺ"},{label:"The Trench",value:"His counsel"},{label:"Verdict",value:"“From us, Ahl al-Bayt” (per hadith)"}],
hadith:[{text:"Salman is from us, the People of the House.",source:"al-Hakim 3/598 (classical; graded variably)"}]},

"c-zayd":{
role:"The beloved · Only companion named in the Qur'an",
summary:"Chose slavery with the Prophet ﷺ over freedom with his father; heaven wrote his name into the Book forever.",
details:`Zayd ibn Harithah was stolen as a boy, sold in Makkah, gifted to {{c:c-khadijah|Khadijah}}, and given by her to the Prophet ﷺ, who freed him. When Zayd's grieving father tracked him down with ransom, the Prophet offered Zayd the choice; Zayd chose the man who had never been anything but light to him: I have seen from this man what makes me choose him over everyone. The Prophet adopted him at the Kaaba, and Makkah called him Zayd ibn Muhammad until revelation ended adoption's fictions and restored lineages: call them by their fathers. To compensate that loss with an honor no companion shares, Allah named him in the Qur'an itself: "when Zayd had concluded from her what he needed" (33:37).

He was the Prophet's most trusted commander, leading expedition after expedition, and the only man beside whose name love is recorded twice: the beloved, and son of the beloved, said of {{c:c-usama|Usama}} his son. He accompanied the Prophet to {{n:30|Ta'if}} and bled shielding him. At Mu'tah he held the banner first of the three, and fell first, a freed slave commanding the nobles of Quraysh by appointment of heaven's Messenger.`,
facts:[{label:"Unique honor",value:"Named in the Qur'an (33:37)"},{label:"The choice",value:"The Prophet over his own father"},{label:"Rank",value:"Most trusted commander"},{label:"Fell at",value:"Mu'tah, first of the three"}],
quran:[{ref:"33:37",ar:"فَلَمَّا قَضَىٰ زَيْدٌ مِّنْهَا وَطَرًا زَوَّجْنَاكَهَا",en:"So when Zayd had concluded from her what he needed, We married her to you."}]},

"c-zubayr":{
role:"The Disciple · Ten promised Paradise",
summary:"First sword drawn for Islam; the Prophet ﷺ said every prophet has a disciple, and mine is az-Zubayr.",
details:`Az-Zubayr ibn al-Awwam, son of the Prophet's ﷺ aunt Safiyyah and husband of {{c:c-asma|Asma}}, believed as a youth. When a rumor flew through Makkah that the Prophet had been seized, the boy came down the streets with a drawn blade, the first sword unsheathed for Islam. He emigrated to Abyssinia and then Madinah, fought at {{n:37|Badr}} in a yellow turban that the reports say the angels matched that day, and stood at {{n:39|the Trench}} where the Prophet said three times: "Every prophet has a disciple (hawari), and my disciple is az-Zubayr," after Zubayr alone volunteered thrice to scout Banu Qurayza.

One of the ten promised Paradise and one of the six of the shura, his body was a map of the battles; his son counted the scars. In the fitnah he marched toward the Camel, then withdrew from the field when {{c:c-ali|Ali}} reminded him of a word from the Prophet; he was murdered while praying by a man who thought he had done a service, and Ali told the killer to expect the Fire. His estate paid its debts and still overflowed: the trader of Paradise trusted with the trusts of Madinah.`,
facts:[{label:"Rank",value:"Ashara mubashara · the Hawari"},{label:"First",value:"First sword drawn for Islam"},{label:"Trench",value:"Volunteered thrice"},{label:"Family",value:"Husband of Asma, son of Safiyyah"}],
hadith:[{text:"Every prophet has a disciple, and my disciple is az-Zubayr.",source:"Bukhari 3719 · Muslim 2415"}]},

"c-saad":{
role:"First arrow of Islam · Answered du'a",
summary:"The Prophet ﷺ ransomed his parents for him at Uhud; Persia fell to his command at Qadisiyyah.",
details:`Sa'd ibn Abi Waqqas believed at seventeen, third or fourth of all mankind, and shot the first arrow ever loosed in defense of this religion. His mother swore hunger to death to break his faith; he answered that were she to die a hundred deaths he would not leave it, and revelation enshrined the balance: obey parents in everything except shirk (31:15). At {{n:38|Uhud}} the Prophet ﷺ emptied his quiver for him with the words no other companion received: "Shoot, may my father and mother be ransomed for you."

The Prophet prayed: "O Allah, make his aim true and answer his supplication," and the ummah learned to fear Sa'd's du'a like a weapon. Under {{c:c-umar|Umar}} he commanded al-Qadisiyyah, the battle that broke the Sassanid empire, and founded Kufa. One of the ten promised Paradise and of the six of the shura, he withdrew from the fitnah entirely, saying: bring me a sword that knows the believer from the disbeliever. He was the last of the ten to die, on his farm outside Madinah, in the woolen cloak he had worn at Badr, kept for his shroud.`,
facts:[{label:"Rank",value:"Ashara mubashara · shura"},{label:"First",value:"First arrow of Islam"},{label:"Uhud",value:"“May my parents be your ransom”"},{label:"Command",value:"Qadisiyyah: Persia broken"},{label:"Feared",value:"His answered du'a"}],
hadith:[{text:"O Allah, make his aim true and answer his supplication.",source:"Tirmidhi 3751 (hasan)"}]},

"c-fatimah":{
role:"Az-Zahra · Leader of the women of Jannah",
summary:"A piece of the Prophet ﷺ; first of his house to follow him, mistress of the women of Paradise.",
details:`Fatimah bint Muhammad, youngest daughter of the Prophet ﷺ and {{c:c-khadijah|Khadijah}}, grew up inside the siege years of Makkah; as a girl she lifted the camel filth from her father's back at the Kaaba while Quraysh laughed. He ﷺ said of her: "Fatimah is a piece of me; whoever angers her angers me." When she entered his room he would rise, take her hand, kiss her, and seat her in his place; the courtesy between them is its own chapter of the sunnah.

She married {{c:c-ali|Ali}} on a dowry of a shield, kept a house of handmill and waterskin, and asked her father for a servant; he taught her instead the tasbih of thirty-three that the ummah still recites at every bedtime. She bore {{c:c-hasan|al-Hasan}}, {{c:c-husayn|al-Husayn}}, Zaynab and Umm Kulthum: every descendant of the Prophet on earth passes through her. In his final illness he ﷺ whispered to her twice; she wept, then laughed. The secret, told later: he informed her he was dying, then that she would be the first of his house to follow him, and the leader of the women of the people of Jannah. She followed him within six months.`,
facts:[{label:"Rank",value:"Leader of the women of Jannah"},{label:"His word",value:"“A piece of me” (Bukhari 5230)"},{label:"Dowry",value:"A shield"},{label:"The tasbih",value:"33 · 33 · 34, her gift"},{label:"Followed him",value:"Within six months"}],
hadith:[{text:"Fatimah is a piece of me; whoever angers her angers me.",source:"Bukhari 5230 · Muslim 2449"}]}
},

addCharacters:{ companions:[

{id:"c-abuhurayrah",titleEn:"Abu Hurayrah",titleAr:"أبو هريرة",role:"The vessel of hadith",summary:"Four years of companionship, a spread cloak, and the largest memory in the history of the sunnah.",pattern:"pattern-sahaba",
details:`Abd ar-Rahman ibn Sakhr ad-Dawsi came to Madinah around Khaybar, poor, unmarried, and unencumbered, and made a decision that shaped the religion: while others traded and farmed, he attached himself to the mosque and to the Prophet's ﷺ heels on a full stomach or an empty one. He complained once of forgetting; the Prophet told him to spread his cloak, made a motion into it, and said gather it to yourself. "I never forgot anything after it." More than five thousand narrations reach the ummah through him; the daily architecture of a Muslim's worship, dhikr, and manners leans on his memory everywhere.

He mothered his mother in da'wah, weeping to the Prophet when she insulted the message, returning with the du'a "O Allah, guide the mother of Abu Hurayrah" to find her behind the door saying the shahadah. The cat-father nickname came from a kitten he carried; the scholars' title came later: the imam of the huffaz. Under {{c:c-umar|Umar}} he governed Bahrain, under the ummah's need he governed nothing but the transmission, teaching in {{p:p-madinah-masjid|the Prophet's mosque}} until his death near sixty years after the Hijrah.`,
facts:[{label:"Companionship",value:"~4 years, total devotion"},{label:"Narrations",value:"5,300+"},{label:"The cloak",value:"“I never forgot after it”"},{label:"His mother",value:"Guided by his ﷺ du'a"}],
hadith:[{text:"He spread his garment, and the Prophet ﷺ made a motion with his hands into it, then said: gather it. I gathered it, and I never forgot anything after it.",source:"Bukhari 119 · Muslim 2492"}]},

{id:"c-anas",titleEn:"Anas ibn Malik",titleAr:"أنس بن مالك",role:"The servant of ten years",summary:"His mother gave him to the Prophet ﷺ as a gift; ten years of service, and never once the word 'uff'.",pattern:"pattern-sahaba",
details:`When {{n:36|the Prophet ﷺ entered Madinah}}, Umm Sulaym brought her ten-year-old son and said: O Messenger of Allah, Anas will serve you. For ten years he did, and his testimony is the finest character reference ever recorded: "He never said to me about anything I did, why did you do it, nor about anything I left, why did you not do it. And he never once said to me: uff." He carried the Prophet's water, his secrets, and his sandals, and grew up inside the household of revelation.

The Prophet ﷺ prayed for him: "O Allah, increase his wealth and his children, and bless what You give him, and admit him to Jannah." Anas lived to bury, by his own count, over a hundred of his descendants, his orchards fruited twice a year, and he died past a hundred years old in Basra, the last companion to die there, still narrating: over two thousand hadith, the childhood memories of the ummah. His nephew asked him about the fourth part of the du'a; Anas said: I have seen three, and I await the fourth.`,
facts:[{label:"Service",value:"10 years, no “uff”"},{label:"Du'a for him",value:"Wealth · children · Jannah"},{label:"Narrations",value:"2,200+"},{label:"Died",value:"Basra, 93 AH, past 100"}],
hadith:[{text:"I served the Prophet ﷺ for ten years, and he never said to me: uff.",source:"Bukhari 6038 · Muslim 2309"}]},

{id:"c-muadh",titleEn:"Mu'adh ibn Jabal",titleAr:"معاذ بن جبل",role:"The scholar of halal and haram",summary:"Sent to Yemen with the ummah's mission statement; will walk ahead of the scholars on the Day of Rising.",pattern:"pattern-sahaba",
details:`Mu'adh ibn Jabal of the Ansar pledged at {{n:32|Aqabah}} as a teenager and became the young man the Prophet ﷺ seated behind him on the mount to teach tawhid: do you know the right of Allah upon His servants? He ﷺ said: "The most knowledgeable of my ummah in halal and haram is Mu'adh ibn Jabal," and told him plainly: "O Mu'adh, by Allah I love you; do not leave off saying after every prayer: O Allah, help me to remember You, to thank You, and to worship You well." The ummah still says it.

Sent as judge and teacher to Yemen, he received at his departure the methodology of Islamic law in three questions: by what will you judge? The Book of Allah. If you do not find it? The Sunnah. If you do not find it? I will strive with my own reasoning, and the Prophet struck his chest with approval. On the road the Prophet gave him the summary of the whole path: the head of the matter is Islam, its pillar is the prayer, and its peak is jihad; then he held his tongue: restrain this. Mu'adh died young in the plague of Amwas in Sham, asking his Lord for his family's share of the epidemic like a bride's gift.`,
facts:[{label:"Expertise",value:"Halal & haram, by his ﷺ word"},{label:"Mission",value:"Judge & teacher of Yemen"},{label:"The dhikr",value:"Help me remember, thank, worship"},{label:"End",value:"Plague of Amwas, ~33 yrs old"}],
hadith:[{text:"O Mu'adh, by Allah I love you. Do not leave off saying after every prayer: O Allah, help me to remember You, to thank You, and to worship You well.",source:"Abu Dawud 1522 · Nasa'i (sahih)"}]},

{id:"c-abudharr",titleEn:"Abu Dharr al-Ghifari",titleAr:"أبو ذر الغفاري",role:"The truth-teller who walked alone",summary:"Believed before the mosque existed, shouted tawhid at the Kaaba, and died alone as promised.",pattern:"pattern-sahaba",
details:`Jundub ibn Junadah of Ghifar, a highway tribe, was a monotheist before he ever heard of the message. When rumor of a prophet reached him he sent his brother, then came himself, sleeping in the mosque precinct until {{c:c-ali|Ali}} smuggled him to the Prophet ﷺ. He believed on the spot, and refused the counsel of secrecy: he stood at the Kaaba and shouted the shahadah into the faces of Quraysh, was beaten to the ground twice, and went home to convert half his tribe.

The Prophet ﷺ said: "The sky has not shaded, nor the earth carried, anyone more truthful of tongue than Abu Dharr." That tongue priced him. His asceticism hardened after {{n:45|the Passing}} into public rebuke of hoarded wealth, quoting the verse of the treasurers of gold; the friction ended with his withdrawal to the desert of ar-Rabadhah, where he died with no one beside him but his family, exactly as the Prophet had foretold at {{n:43|Tabuk}}: "May Allah have mercy on Abu Dharr; he walks alone, dies alone, and will be raised alone." A caravan of Iraq, Ibn Mas'ud at its head, buried him weeping.`,
facts:[{label:"Believed",value:"Among the first five"},{label:"First act",value:"Public shahadah at the Kaaba"},{label:"His ﷺ word",value:"Most truthful under the sky"},{label:"End",value:"Alone at ar-Rabadhah, as foretold"}],
hadith:[{text:"The sky has not shaded, nor the earth carried, anyone more truthful of tongue than Abu Dharr.",source:"Tirmidhi 3801 (hasan)"}]},

{id:"c-ibnmasud",titleEn:"Abdullah ibn Mas'ud",titleAr:"عبد الله بن مسعود",role:"First public reciter · The two thin shins",summary:"A shepherd boy who became the ummah's Qur'an; heavier on the Scale than Uhud.",pattern:"pattern-sahaba",
details:`A slight shepherd of Makkah's outskirts, Ibn Mas'ud met two fugitives asking for milk and watched a dry udder fill at the Prophet's ﷺ touch; he asked to be taught, and became the sixth person in Islam. He was the first man after the Prophet to recite the Qur'an publicly at the Kaaba, taking the beating that followed and offering to do it again tomorrow. The Prophet told the ummah: "Whoever wishes to recite the Qur'an fresh as it was revealed, let him recite it upon the reading of Ibn Umm Abd," and counted him among the four from whom the Qur'an should be taken.

He carried the Prophet's sandals, siwak, and secrets, walked with him, and absorbed his manner until visitors mistook the household resemblance. When the wind lifted his garment from his thin shins and the companions laughed, the Prophet said: "By the One in whose hand is my soul, they are heavier on the Scale than Uhud." He taught Kufa its Qur'an and its fiqh; the school that became Iraq's jurisprudence begins in his mosque circle. He asked to recite for the Prophet once and wept him to tears at "how will it be when We bring from every nation a witness, and bring you over these as a witness."`,
facts:[{label:"Number",value:"Sixth in Islam"},{label:"First",value:"Public Qur'an at the Kaaba"},{label:"On the Scale",value:"Shins heavier than Uhud"},{label:"Legacy",value:"The school of Kufa"}],
hadith:[{text:"Whoever wishes to recite the Qur'an fresh as it was revealed, let him recite it upon the reading of Ibn Umm Abd.",source:"Ibn Majah 138 · Ahmad (sahih)"}]},

{id:"c-ubayy",titleEn:"Ubayy ibn Ka'b",titleAr:"أبي بن كعب",role:"Master of the reciters",summary:"Allah named him from above seven heavens to hear Surah al-Bayyinah, and he wept.",pattern:"pattern-sahaba",
details:`Ubayy ibn Ka'b of the Ansar, a scribe of revelation and one of the four collectors of the Qur'an in the Prophet's ﷺ lifetime, holds an honor that staggered him for the rest of his life. The Prophet said: "Allah has commanded me to recite to you: 'Those who disbelieved among the People of the Book...'" Ubayy asked: did He name me? "He named you." And Ubayy wept. The Lord of the worlds had specified one listener in Madinah by name.

The Prophet called him Abu al-Mundhir and tested him: which verse of the Book of Allah is greatest? Ayat al-Kursi, he answered, and the Prophet struck his chest: "May knowledge be pleasant to you, Abu al-Mundhir." He ﷺ ranked him aloud: "The best reciter of my ummah is Ubayy ibn Ka'b." Under {{c:c-umar|Umar}}, who called him the master of the Muslims, he led the first congregational tarawih of Ramadan; every Ramadan night prayer on earth since stands in a line he started. His mushaf readings remain a resource of tafsir; his fear of the fitnah of position remains a resource of sincerity: he asked Allah to be forgotten, and Allah preserved his name in every science of the Qur'an instead.`,
facts:[{label:"Named by",value:"Allah, for al-Bayyinah"},{label:"Rank",value:"Best reciter of the ummah"},{label:"Test won",value:"Ayat al-Kursi"},{label:"First",value:"Led congregational tarawih"}],
hadith:[{text:"Allah has commanded me to recite to you. He asked: did He name me? He said: He named you. And Ubayy wept.",source:"Bukhari 3809 · Muslim 799"}]},

{id:"c-zaydthabit",titleEn:"Zayd ibn Thabit",titleAr:"زيد بن ثابت",role:"Scribe of revelation · Collector of the Qur'an",summary:"Too young for Badr, chosen at twenty-one to gather the Book between two covers.",pattern:"pattern-sahaba",
details:`Turned away from {{n:37|Badr}} and {{n:38|Uhud}} for his age, Zayd ibn Thabit conquered by intellect instead: he arrived in Madinah with seventeen surahs memorized, and the Prophet ﷺ ordered him to learn the script of the Jews, which he mastered in half a month, becoming the Prophet's translator and foremost scribe of revelation. When the ayah of the mujahidin descended while his shoulder bore the Prophet's writing board, he felt the weight of revelation nearly crush his thigh; he wrote "not equal are the sitters" and then the exemption came for the excused, live, under his pen.

After Yamamah killed hundreds of reciters, {{c:c-abubakr|Abu Bakr}} and {{c:c-umar|Umar}} summoned him for the task he described as heavier than moving a mountain: collect the Qur'an. "You are a young man, intelligent, and beyond suspicion, and you used to write the revelation for the Messenger of Allah." He verified every verse against memory and written witness together, and years later chaired {{c:c-uthman|Uthman's}} committee that copied the single mushaf for the ummah. The judge and inheritance-jurist of Madinah for a generation, he is the quiet proof that the Book reached us through discipline, not accident.`,
facts:[{label:"Scribe",value:"Foremost writer of revelation"},{label:"Languages",value:"Learned Hebrew script in 15 days"},{label:"Task",value:"“Heavier than a mountain”"},{label:"Chaired",value:"Uthman's mushaf committee"}],
hadith:[{text:"You are a young man, intelligent, beyond suspicion, and you used to write the revelation. So pursue the Qur'an and collect it.",source:"Bukhari 4986"}]},

{id:"c-ibnabbas",titleEn:"Abdullah ibn Abbas",titleAr:"عبد الله بن عباس",role:"Interpreter of the Qur'an",summary:"The Prophet ﷺ pressed him to his chest and asked Allah to teach him ta'wil; tafsir begins with him.",pattern:"pattern-sahaba",
details:`Son of {{c:c-abbas|al-Abbas}}, born in the boycott years, Ibn Abbas was about thirteen at {{n:45|the Passing}}, and yet no name stands taller in the interpretation of the Book. The reason is a du'a: the Prophet ﷺ embraced him and said, "O Allah, teach him the Book," and in the narration of the ablution night, "O Allah, give him understanding in the religion and teach him the interpretation." The boy who set out water for the Prophet's wudu received in exchange the keys of tafsir.

His method built the science: he chased the companions door to door with a pillow under his arm, waiting at thresholds while they napped, answering when asked why the cousin of the Prophet begged knowledge at doors: knowledge is not attained with the body at rest. {{c:c-umar|Umar}} seated the youth with the elders of Badr and proved his rank with the tafsir of Surah an-Nasr: the announcement of the Messenger's approaching death, which only Ibn Abbas saw. Hibr al-ummah, the learned of the nation, and its tarjuman al-Qur'an, he taught at Makkah until blindness, and died at Ta'if with the community's knowledge multiplied through his students for every century after.`,
facts:[{label:"The du'a",value:"“Teach him the Book”"},{label:"Titles",value:"Hibr al-ummah · Tarjuman al-Qur'an"},{label:"Method",value:"A pillow at the doors of the elders"},{label:"Proof",value:"The tafsir of an-Nasr before Umar"}],
hadith:[{text:"The Prophet ﷺ embraced me and said: O Allah, teach him the Book.",source:"Bukhari 75 · Muslim 2477"}]},

{id:"c-ibnumar",titleEn:"Abdullah ibn Umar",titleAr:"عبد الله بن عمر",role:"The meticulous follower",summary:"“What a good man Abdullah would be, if he prayed at night.” He never left the night prayer again.",pattern:"pattern-sahaba",
details:`Son of {{c:c-umar|al-Faruq}}, Ibn Umar was rejected at Badr and Uhud for youth and accepted at {{n:39|the Trench}} at fifteen. As a young man he dreamed of two angels showing him the Fire and a rescuer saying you will not be harmed; his sister {{c:c-hafsah|Hafsah}} relayed it, and the Prophet ﷺ answered with the sentence that programmed his life: "What a good man Abdullah is, if only he prayed at night." From that day he barely slept the last third.

He became the ummah's specialist in following: he prayed where the Prophet prayed, halted his mount where the Prophet's halted, and transmitted the pilgrim's rites step for step. In the fitnah he sheathed his sword entirely and became the reference both armies trusted; offered the caliphate more than once, he refused it unless every Muslim agreed, which is to say he refused it. He gave away fortunes of Umar's estate while patching his own garment, freed slaves by the thousand, and narrated with a terror of misquoting the Prophet that made his precision proverbial. He died in Makkah past eighty, the last of the elder school, having fulfilled one sentence for sixty years.`,
facts:[{label:"Admitted",value:"The Trench, at 15"},{label:"The sentence",value:"“…if he prayed at night”"},{label:"Specialty",value:"Exact following (ittiba')"},{label:"Fitnah",value:"Sword sheathed entirely"}],
hadith:[{text:"What a good man Abdullah is, if only he prayed at night. After that he slept only a little at night.",source:"Bukhari 1122 · Muslim 2479"}]},

{id:"c-usama",titleEn:"Usama ibn Zayd",titleAr:"أسامة بن زيد",role:"The beloved, son of the beloved",summary:"Commander at eighteen over the elders of Badr; the Prophet's ﷺ last army marched under him.",pattern:"pattern-sahaba",
details:`Son of {{c:c-zayd|Zayd}} and of Umm Ayman the Prophet's ﷺ nurse, Usama grew up on the Prophet's knee, paired there with {{c:c-hasan|al-Hasan}}: "O Allah, love them both, for I love them." Makkah's measure of him is the intercession story: when a noblewoman's theft case sought a favorite to soften the law, they chose Usama, the beloved, son of the beloved, and his request drew the Prophet's most famous statement of equality: peoples before you were destroyed because they excused the noble and punished the weak; by Allah, if Fatimah the daughter of Muhammad stole, I would cut off her hand.

In his final days the Prophet ﷺ tied the banner of the Sham expedition for Usama, eighteen years old, with {{c:c-umar|Umar}} in his ranks; the murmurs about his youth were answered from the minbar: he is worthy of command, as his father was. {{c:c-abubakr|Abu Bakr's}} first act as caliph was to dispatch that army unchanged, walking beside the mounted teenager he refused to outrank. Usama had one scar he carried from a battlefield misjudgment, a shahadah spoken under his raised sword that he did not accept as sincere; the Prophet's rebuke, did you split open his heart, made Usama wish he had entered Islam only that day, and made the ummah's rules of engagement forever.`,
facts:[{label:"Loved",value:"With al-Hasan, on his ﷺ knee"},{label:"Command",value:"18, over the elders"},{label:"The rebuke",value:"“Did you split open his heart?”"},{label:"Abu Bakr",value:"Walked beside his mount"}],
hadith:[{text:"If Fatimah the daughter of Muhammad stole, I would cut off her hand.",source:"Bukhari 3475 · Muslim 1688"}]},

{id:"c-abuayyub",titleEn:"Abu Ayyub al-Ansari",titleAr:"أبو أيوب الأنصاري",role:"Host of the Messenger ﷺ",summary:"The camel knelt at his door; he died a soldier under the walls of Constantinople.",pattern:"pattern-sahaba",
details:`Khalid ibn Zayd of Banu Najjar won the lottery every house in Madinah wanted: when {{n:36|al-Qaswa knelt}}, it was at his door, and the Prophet ﷺ lodged with him seven months while the mosque rose. The householder's adab became legend: he and his wife could not bear walking on the floor above the Messenger of Allah, cornering themselves at the room's edge by night, until the Prophet moved upstairs for his hosts' peace. When a dish returned untouched because it carried garlic, Abu Ayyub asked in alarm if it was haram; no, said the Prophet, but I converse with One you do not converse with.

He fought at Badr, Uhud, and every field, and refused to retire: an old man jihad-bound every fighting season under whichever banner marched. Past eighty he joined the first campaign against Constantinople, fell ill under its walls, and asked for the most forward grave in the army's reach: carry me as far as you can into their land. There he lies to this day, the host of Madinah buried at the edge of Byzantium, teaching the Codex's readers that hospitality and striving were one temperament, not two.`,
facts:[{label:"The lottery",value:"Al-Qaswa chose his door"},{label:"Host",value:"Seven months"},{label:"Habit",value:"A campaign every season"},{label:"Grave",value:"Beneath Constantinople's walls"}],
hadith:[{text:"He asked about the garlic: is it haram? He ﷺ said: No, but I converse with One you do not converse with.",source:"Muslim 2053"}]},

{id:"c-ibnsalam",titleEn:"Abdullah ibn Salam",titleAr:"عبد الله بن سلام",role:"The rabbi who recognized him",summary:"Looked once at his face and knew it was not the face of a liar; promised Jannah by name.",pattern:"pattern-sahaba",
details:`Al-Husayn ibn Salam was the rabbi of Banu Qaynuqa, a man who knew the awaited prophet's description the way he knew his own son. When {{n:36|the Messenger entered Madinah}} he went to look, and his verdict entered the sunan: "When I saw his face, I knew it was not the face of a liar." He tested him with questions whose answers only a prophet would know: the first sign of the Hour, the first meal of the people of Jannah, the resemblance of the child. Then he asked the Prophet ﷺ to conceal him and summon the Jewish leaders; they praised Abdullah as their best and their master, until he stepped out with the shahadah, and became in one minute their worst and the son of their worst. He asked for shelter in the verdict of revelation: "a witness from the Children of Israel testified to its like" (46:10) is read of him.

The Prophet renamed him Abdullah; the sunnah records for him what it records for barely anyone: a promise of Jannah by name while walking the earth, and a dream of a firm handhold interpreted by the Prophet as his dying upon the rope of Islam. He did, decades later, having spent his knowledge translating the two scriptures for the ummah of the last one.`,
facts:[{label:"Verdict",value:"“Not the face of a liar”"},{label:"Test",value:"Questions only a prophet answers"},{label:"Verse",value:"46:10, read of him"},{label:"Promise",value:"Jannah, by name"}],
hadith:[{text:"Spread salam, feed food, keep the ties, and pray at night while people sleep: you will enter Jannah in peace.",source:"Tirmidhi 2485 · Ibn Majah 1334 (his first hearing ﷺ)"}]},

{id:"c-amr",titleEn:"Amr ibn al-As",titleAr:"عمرو بن العاص",role:"The mind that opened Egypt",summary:"Came to Islam between Khalid and Uthman ibn Talha in one caravan; Egypt entered Islam through his.",pattern:"pattern-sahaba",
details:`Quraysh's sharpest diplomat, sent to Abyssinia to drag the emigrants home, Amr watched {{c:c-jafar|Ja'far's}} defense defeat him in front of the Negus and carried the splinter of that day for years. After {{n:40|Hudaybiyyah}} the calculation completed itself: he rode north and met {{c:c-khalid|Khalid}} and {{c:c-uthman-talha|Uthman ibn Talha}} on the same errand. At his pledge he demanded a clause, that his past be forgiven, and learned the rule the ummah recites to every convert since: "Do you not know that Islam demolishes what was before it?"

The Prophet ﷺ used the new instrument immediately: command of Dhat as-Salasil, with Abu Bakr and Umar under his flag, and the young general asked the question every ambitious heart asks, who is most beloved to you, expecting his own name; the answer, Aisha, and of men her father, taught him where love actually ranked. Under Umar he opened Egypt with four thousand men and founded Fustat with its mosque, first in Africa; his deathbed scene in Sahih Muslim, weeping through the three chapters of his life, ends with the tawhid of hope: none but the Most Merciful for what remains.`,
facts:[{label:"Converted",value:"With Khalid, one caravan"},{label:"The rule",value:"“Islam demolishes what was before it”"},{label:"Opened",value:"Egypt · founded Fustat"},{label:"Deathbed",value:"Muslim 121, the three chapters"}],
hadith:[{text:"Do you not know that Islam demolishes what was before it?",source:"Muslim 121"}]},

{id:"c-ikrimah",titleEn:"Ikrimah ibn Abi Jahl",titleAr:"عكرمة بن أبي جهل",role:"Son of this ummah's Pharaoh, martyr of Yarmuk",summary:"He fled the Opening by sea; the storm's tawhid brought him back to the gate of mercy.",pattern:"pattern-sahaba",
details:`Son of Abu Jahl, raised at the furnace of his father's hatred, Ikrimah commanded a flank against the Muslims at {{n:38|Uhud}} and fought on at {{n:41|the Opening}} after resistance collapsed. Excluded from the amnesty, he fled for Abyssinia by sea, and in the storm heard the sailors say: nothing avails here but calling on Allah alone. He said to himself: if none avails at sea but Him, none avails on land but Him, and turned around on the strength of a wave's theology. His wife Umm Hakim had already taken his pardon from the Prophet ﷺ, who received him with joy and forbade the Muslims to curse his dead father, for cursing the dead wounds the living.

He spent himself like a man paying arrears: Qur'an pressed to his face, saying the Book of my Lord, the Book of my Lord. At Yarmuk he dismounted with the pledge-unto-death band and fell covered in wounds; the tradition sets his death among the wounded brothers passing the water cup down the line, each refusing it for the next, all dying before it returned. From first enemy's son to that cup is the whole distance Islam's door can cover.`,
facts:[{label:"Father",value:"Abu Jahl"},{label:"Turned by",value:"The storm's tawhid"},{label:"Etiquette",value:"His dead father not to be cursed"},{label:"End",value:"Yarmuk, the passed cup"}],
hadith:[{text:"Do not curse the dead, for thereby you hurt the living.",source:"cf. Tirmidhi 1982 · Bukhari 1393 (principle)"}]},

{id:"c-ummayman",titleEn:"Umm Ayman (Barakah)",titleAr:"أم أيمن بركة",role:"The mother after his mother",summary:"She carried him ﷺ as an orphan and wept after him for the revelation that had ceased.",pattern:"pattern-sahaba",
details:`Barakah al-Habashiyyah belonged to the Prophet's ﷺ father and was the young widow Aminah's companion on the journey where she died; the six-year-old rode back to Makkah in Barakah's arms, and she never left him. He freed her, called her "my mother after my mother," and married her to {{c:c-zayd|Zayd}}; their son was {{c:c-usama|Usama}}, the beloved son of the beloved. She made both hijrahs, Abyssinia and Madinah, on foot and fasting until, the reports say, heaven sent down a bucket to her thirst.

She appears at the seams of the story: bandaging at Uhud, carrying water, scolding the routed at Hunayn with her accented Arabic the Prophet gently corrected. After {{n:45|the Passing}}, {{c:c-abubakr|Abu Bakr}} and {{c:c-umar|Umar}} visited her as he used to, and found her weeping. Do you not know that what is with Allah is better for His Messenger? I know, she said: I weep because revelation from heaven has ceased. Her tears defined the loss for the whole ummah, and the two caliphs wept with her. Every prophet's story hides a woman who carried it before it could walk; the Codex names this one.`,
facts:[{label:"Carried him",value:"From his mother's grave"},{label:"His word",value:"“My mother after my mother”"},{label:"Family",value:"Wife of Zayd, mother of Usama"},{label:"Her tears",value:"For the ceased revelation"}],
hadith:[{text:"She said: I weep because the revelation from heaven has ceased. And she moved them both to weeping with her.",source:"Muslim 2454"}]},

{id:"c-hafsah",titleEn:"Hafsah bint Umar",titleAr:"حفصة بنت عمر",role:"Umm al-Mu'minin · Keeper of the mushaf",summary:"The fasting, praying wife to whom the ummah entrusted the only master copy of the Qur'an.",pattern:"pattern-sahaba",
details:`Daughter of {{c:c-umar|Umar}}, widowed young after Badr, Hafsah was offered by her anxious father to Abu Bakr and Uthman before heaven resolved the matter better: the Prophet ﷺ married her, and Jibril himself testified for her when a divorce nearly proceeded: "Take Hafsah back, for she is given to much fasting and much prayer, and she is your wife in Jannah."

Her rank in the ummah's history is custodial and immense. When the first collection of the Qur'an was completed under her father's counsel, the sheets passed from Abu Bakr to Umar, and from Umar not to a caliph but to Hafsah: the master copy of the Book of Allah lived in a wife's room. Years later {{c:c-uthman|Uthman}} borrowed those sheets to copy the unified mushaf and returned them to her hand. She fasted the day she died, as Jibril had described her. Between her keeping and {{c:c-aisha|Aisha's}} narrating, the two young widows of the Prophet's house held the Book and the Sunnah for the generations, and no shelf in Islam is more honored than the chest where her sheets lay.`,
facts:[{label:"Father",value:"Umar al-Faruq"},{label:"Jibril's word",value:"Fasting, praying, his wife in Jannah"},{label:"Custody",value:"The master sheets of the Qur'an"},{label:"Lent to",value:"Uthman's committee, then returned"}],
hadith:[{text:"Take Hafsah back, for she fasts much and prays much, and she is your wife in Jannah.",source:"al-Hakim (sahih isnad) · cf. Abu Dawud 2283"}]},

{id:"c-safiyyah",titleEn:"Safiyyah bint Huyayy",titleAr:"صفية بنت حيي",role:"Umm al-Mu'minin · Daughter of Harun's line",summary:"“My father is Harun and my uncle is Musa.” The Prophet ﷺ taught her the answer that silenced every taunt.",pattern:"pattern-sahaba",
details:`Daughter of Huyayy ibn Akhtab, chief of Banu Nadir of the line of Harun, Safiyyah dreamed before Khaybar of a moon falling into her lap, and carried the slap-mark her husband gave her for it into the day the dream landed. Widowed at Khaybar, she was freed by the Prophet ﷺ, who made her emancipation her dowry and married her, seating her on his own mount with his knee for her step.

Madinah's tongues tested the newcomer's lineage; one day she came to the Prophet weeping from a taunt of Jewish daughterhood. His reply armed her forever: "Why did you not say: my father is Harun, my uncle is Musa, and my husband is Muhammad?" In his final illness she said before the wives: I wish it were I in your place, and when some smiled he ﷺ defended her sincerity: by Allah, she is truthful. She lived into the fitnah lowering food by rope to besieged {{c:c-uthman|Uthman}}, and died in Madinah, a bridge of the two covenants in one woman: prophet's daughter by blood, prophet's wife by choice, buried in al-Baqi among the mothers of the believers.`,
facts:[{label:"Lineage",value:"The line of Harun"},{label:"Dowry",value:"Her freedom"},{label:"The answer",value:"Harun · Musa · Muhammad"},{label:"Fitnah",value:"Fed Uthman by rope"}],
hadith:[{text:"Why did you not say: my father is Harun, my uncle is Musa, and my husband is Muhammad?",source:"Tirmidhi 3892 (hasan)"}]},

{id:"c-zaynab",titleEn:"Zaynab bint Jahsh",titleAr:"زينب بنت جحش",role:"Umm al-Mu'minin · Married by revelation",summary:"“Allah married me from above seven heavens.” The longest hand in charity among the wives.",pattern:"pattern-sahaba",
details:`Cousin of the Prophet ﷺ, first married to {{c:c-zayd|Zayd}} in a match arranged to demolish class pride, then divorced, Zaynab became the center of the verse that ended adoption's marriage fictions: "We married her to you" (33:37). Her wedding contract was dictated by revelation, and she knew what she held: to the other wives she would say, your families gave you in marriage; Allah married me from above seven heavens.

Aisha, her rival in rank, gave her the testimony that settles her portrait: "I have never seen a woman better in religion than Zaynab, more fearing of Allah, more truthful in speech, more attentive to kinship, greater in sadaqah." She worked leather with her own hands and gave the earnings away. When the wives asked which of them would follow him ﷺ first, he answered: the one with the longest hand. They measured wrists against the wall until the meaning arrived with her death: the longest hand was the most giving one. Zaynab followed him first, in Umar's caliphate, leaving nothing behind: she had already sent it ahead.`,
facts:[{label:"Contract",value:"Dictated by 33:37"},{label:"Her boast",value:"Married from above the heavens"},{label:"Aisha's word",value:"None better in religion"},{label:"The longest hand",value:"First to follow him"}],
hadith:[{text:"The quickest of you to join me is the one with the longest hand. It was Zaynab, for she worked with her hand and gave sadaqah.",source:"Muslim 2452 · cf. Bukhari 1420"}]},

{id:"c-hasan",titleEn:"Al-Hasan ibn Ali",titleAr:"الحسن بن علي",role:"Master of the youth of Jannah · The reconciler",summary:"“This son of mine is a sayyid; through him Allah will reconcile two great parties of the Muslims.”",pattern:"pattern-sahaba",
details:`Firstborn of {{c:c-ali|Ali}} and {{c:c-fatimah|Fatimah}}, named by the Prophet ﷺ himself, al-Hasan rode his grandfather's back in sujud and his shoulder in the streets, and carried his face: the most resembling of the household. From the minbar the Prophet issued the prophecy that became this man's biography: "This son of mine is a sayyid, and perhaps Allah will reconcile through him two great parties of the Muslims."

Forty years later he held the caliphate of Iraq with an army at his back and every incentive of blood and title to use it. He weighed the ummah against the throne and handed power to Mu'awiyah on terms, in the Year of the Jamaa, retiring to Madinah as the man who proved the Prophet's word by giving up what men kill for. With his brother {{c:c-husayn|al-Husayn}} he holds the shared title: the two masters of the youth of the people of Jannah. He was generous past accounting, twice splitting his entire wealth with the poor, and died in Madinah, asking burial beside his grandfather if it caused no conflict, and al-Baqi when it would have: peacemaking even in the grave.`,
facts:[{label:"Prophecy",value:"“Through him, two parties reconciled”"},{label:"Fulfilled",value:"Year of the Jamaa"},{label:"Title",value:"Sayyid of Jannah's youth"},{label:"Trait",value:"Split his wealth twice"}],
hadith:[{text:"This son of mine is a sayyid, and perhaps Allah will reconcile through him two great parties of the Muslims.",source:"Bukhari 2704"}]},

{id:"c-husayn",titleEn:"Al-Husayn ibn Ali",titleAr:"الحسين بن علي",role:"Master of the youth of Jannah · Martyr of Karbala",summary:"“Husayn is from me and I am from Husayn.” The grandson whose stand defined the price of principle.",pattern:"pattern-sahaba",
details:`Second son of {{c:c-ali|Ali}} and {{c:c-fatimah|Fatimah}}, al-Husayn was the other half of the pair the Prophet ﷺ called "my two sweet basils of this world," lengthening his sujud rather than hurry a grandson off his back, praying: "O Allah, I love them, so love them." Of him specifically he said: "Husayn is from me and I am from Husayn; Allah loves whoever loves Husayn."

He grew in his brother's counsel and outlived him into the hour when kingship asked the Prophet's grandson for its stamp. He refused the pledge he judged an injustice, answered Kufa's letters, and was intercepted at Karbala with his family: some seventy against thousands, cut off from the river. On Ashura of 61 AH he fell with his infant in his arms and his household around him, and the head of the man whom the Messenger of Allah kissed on the mouth was carried to a palace. The ummah's grief is not sectarian property; the Sunni canon itself carries his rank, and the Codex records both the love and the warning: whoever makes power absolute will meet the family of the Prophet in his ledger.`,
facts:[{label:"His ﷺ word",value:"“I am from Husayn”"},{label:"Title",value:"Sayyid of Jannah's youth"},{label:"Stand",value:"Refused the unjust pledge"},{label:"Karbala",value:"Ashura, 61 AH"}],
hadith:[{text:"Husayn is from me and I am from Husayn; Allah loves whoever loves Husayn.",source:"Tirmidhi 3775 · Ibn Majah 144 (hasan)"}]}
]}
};
