// NOOR Characters hub expansion — new seals + cross-link enrichment
// removeIds: an-abil is a duplicate of an-fil (same event, Surah al-Fil)
export default {

removeIds:["an-abil"],

// First plain-text occurrence of each key gets wrapped as a cross-link marker.
linkExisting:{
 "c-abubakr":{"cave of Thawr":"n:33","Isra":"n:31"},
 "c-umar":{"assassinated while leading the prayer":null,"conversion":null},
 "c-uthman":{"army of hardship (Tabuk)":"n:43"},
 "c-ali":{"night of the Hijrah":"n:33","Badr":"n:37","Uhud":"n:38"},
 "c-khadijah":{"first revelation came in Hira":"n:29","Waraqah ibn Nawfal":"c-waraqah","Year of Sorrow":"n:30"},
 "c-hamza":{"Badr":"n:37","Uhud":"n:38","Wahshi":"c-wahshi","Hind":"c-hind"},
 "c-bilal":{"Opening of Makkah":"n:41"},
 "c-salman":{"Battle of the Trench":"n:39"},
 "c-zayd":{"Zaynab":null},
 "c-zubayr":{"Badr":"n:37","Uhud":"n:38"},
 "c-saad":{"ten promised Paradise":null},
 "c-fatimah":{"Ali ibn Abi Talib":"c-ali"},
 "a-jibril":{"Isra and Mi'raj":"n:31"},
 "a-israfil":{"Trumpet (as-Sur)":"n:57"},
 "j-iblis":{"prostration to Adam":"n:2"},
 "an-salih":{},
 "an-fil":{"year of the Prophet's birth":"n:26"},
 "an-yunus":{},
 "e-dajjal":{"Isa ibn Maryam will descend":"n:49"},
 "e-dabba":{"major signs of the Hour":"n:52"},
 "e-yajuj":{"barrier built by Dhul-Qarnayn":"n:50"},
 "e-isa-return":{"white minaret east of Damascus":"n:49"}
},

addCharacters:{

companions:[
{id:"c-talha",titleEn:"Talha ibn Ubaydillah",titleAr:"طلحة بن عبيد الله",role:"The living martyr · Ten promised Paradise",summary:"Shielded the Prophet ﷺ at Uhud with his own hand until it was paralyzed.",pattern:"pattern-sahaba",
details:`At {{n:38|Uhud}}, when the lines broke, Talha stood between the Prophet ﷺ and the arrows and took them with his body; his hand was struck defending the Prophet's face and remained paralyzed for life. The Prophet said: "Whoever wishes to look at a martyr walking upon the earth, let him look at Talha ibn Ubaydillah." Among the earliest converts through {{c:c-abubakr|Abu Bakr}}, tortured for Islam, and one of the ten promised Paradise. Of him and his day at Uhud, Abu Bakr used to say: "That day belonged entirely to Talha." He fell at the Battle of the Camel, an old man still in the saddle.`,
facts:[{label:"Rank",value:"Ashara mubashara"},{label:"Uhud",value:"Hand paralyzed shielding him ﷺ"},{label:"Title",value:"The living martyr"}]},

{id:"c-musab",titleEn:"Mus'ab ibn Umayr",titleAr:"مصعب بن عمير",role:"First envoy of Islam · Banner of Uhud",summary:"Makkah's perfumed aristocrat who traded everything, taught Madinah, and died holding the flag.",pattern:"pattern-sahaba",
details:`The most pampered youth of Makkah — his mother's wealth dressed him in the finest cloth — until Islam cost him all of it. Sent after {{n:32|the First Aqabah}} as the first teacher-ambassador to Yathrib, his gentle recitation opened house after house, and chiefs like {{c:c-saad-muadh|Sa'd ibn Mu'adh}} entered Islam at his hands — a city converted by one man's adab before any army existed. He carried the banner at {{n:37|Badr}} and at {{n:38|Uhud}}, where both his arms were cut holding it before he fell. At his burial there was only one small cloak: cover the head and it left the feet bare; cover the feet and it left the head — the Prophet ﷺ ordered his head covered and grass upon his feet.`,
facts:[{label:"Mission",value:"First envoy — to Yathrib"},{label:"Banner",value:"Badr & Uhud"},{label:"Shroud",value:"One cloak — too short"}]},

{id:"c-saad-muadh",titleEn:"Sa'd ibn Mu'adh",titleAr:"سعد بن معاذ",role:"Chief of Aws · The Throne shook",summary:"Believed in one sitting, led his clan to Islam by nightfall, and died of the Khandaq wound.",pattern:"pattern-sahaba",
details:`Chief of the Aws in Madinah, he came to scold {{c:c-musab|Mus'ab}} and sat down to listen; by evening he told his clan: your speech to me is forbidden until you believe — and Banu Abd al-Ashhal entered Islam in a night. At {{n:37|Badr}} he spoke the Ansar's loyalty into history: "Proceed, O Messenger of Allah, for by Allah, if you plunged into this sea we would plunge with you." At {{n:39|the Khandaq}} an arrow cut his arm-vein; he asked Allah to keep him alive only until he saw judgment upon Banu Qurayza, gave it in accordance with Allah's ruling from above the seven heavens — as the Prophet ﷺ said — and died of the reopened wound. The Prophet said: "The Throne of the Most Merciful shook at the death of Sa'd ibn Mu'adh."`,
facts:[{label:"Converted",value:"His clan — in one night"},{label:"Wound",value:"Khandaq — the akhal vein"},{label:"Honor",value:"The Throne shook (Bukhari 3803)"}]},

{id:"c-hudhayfah",titleEn:"Hudhayfah ibn al-Yaman",titleAr:"حذيفة بن اليمان",role:"Keeper of the Secret · Scout of the Trench",summary:"The Prophet's confidant on the hypocrites, and the lone scout of the Confederates' camp.",pattern:"pattern-sahaba",
details:`The Prophet ﷺ entrusted Hudhayfah alone with the names of the hypocrites — Umar himself would ask him whether he was on the list. On the freezing night of {{n:39|the Khandaq}}, when the Prophet asked who would bring news of the enemy and the hunger-worn camp fell silent, he named Hudhayfah — who slipped among the Confederates as the storm tore their pots and tents, heard Abu Sufyan order the retreat, and returned with the news of the siege's collapse. He asked the Prophet about evil after good and the callers at the gates of Jahannam — the ummah's early-warning system in a single companion. He supervised Uthman's unification of the mushaf.`,
facts:[{label:"Trust",value:"Names of the hypocrites"},{label:"Khandaq",value:"Night scout of the camp"},{label:"Method",value:"Asked about evil, to avoid it"}]},

{id:"c-nuaym",titleEn:"Nu'aym ibn Mas'ud",titleAr:"نعيم بن مسعود",role:"The one-man stratagem of the Trench",summary:"Converted in secret mid-siege and unstitched the Confederate alliance with words alone.",pattern:"pattern-sahaba",
details:`A man of Ghatafan trusted by every faction, Nu'aym came to the Prophet ﷺ secretly during {{n:39|the Khandaq}}: my people do not know of my Islam — command me. The Prophet said: "You are among us one man; so divert from us what you can, for war is deception." Nu'aym went to Banu Qurayza and counseled them to demand hostages from Quraysh; then to Quraysh and Ghatafan, warning that Qurayza would hand them hostages to redeem their pact. When Quraysh tested Qurayza on the Sabbath and the hostage demand surfaced exactly as scripted, each side read betrayal — and the alliance seized. Then Allah sent the wind. One believer's precision was worth ten thousand men.`,
facts:[{label:"Cover",value:"Islam kept secret"},{label:"License",value:"“War is deception”"},{label:"Result",value:"The alliance unstitched"}]},

{id:"c-umm-salamah",titleEn:"Umm Salamah",titleAr:"أم سلمة",role:"Mother of the Believers · Counsel of Hudaybiyyah",summary:"Her one sentence at Hudaybiyyah saved the camp from the brink.",pattern:"pattern-sahaba",
details:`Hind bint Abi Umayyah — among the first emigrants to Abyssinia and then Madinah, widowed by the wounds of {{n:38|Uhud}}, then honored as a Mother of the Believers. Her fiqh entered history at {{n:40|Hudaybiyyah}}: when the companions, crushed by the treaty's terms, did not rise to the Prophet's ﷺ command to sacrifice and shave, he entered upon her in grief — and she counseled: go out, speak to no one, slaughter your own sacrifice and call your barber. He did; the camp leapt to follow; the crisis dissolved without a word of rebuke. Scholars count her counsel among the finest political judgments in the Seerah. She narrated hundreds of hadith and outlived nearly all the wives.`,
facts:[{label:"Rank",value:"Umm al-Mu'minin"},{label:"Hudaybiyyah",value:"The counsel that saved the camp"},{label:"Legacy",value:"Jurist & narrator"}]},

{id:"c-khalid",titleEn:"Khalid ibn al-Walid",titleAr:"خالد بن الوليد",role:"Sayfullah — the Drawn Sword of Allah",summary:"Broke the Muslims at Uhud; then never lost a battle for Islam.",pattern:"pattern-sahaba",
details:`The cavalry mind who saw the abandoned hill at {{n:38|Uhud}} and turned the day — against the Muslims. After {{n:40|Hudaybiyyah}} he weighed the road ahead and rode to Madinah; the Prophet ﷺ received him: "Praise be to Allah who has guided you — I always saw in you an intellect that I hoped would deliver you to good." He led a column at {{n:41|the Opening}}, took command at Mu'tah when three commanders fell — earning the name Sayfullah, the Drawn Sword of Allah — and later broke the ridda and opened Iraq and Sham at Yarmuk. Removed from command at his peak by {{c:c-umar|Umar}}, he obeyed without a murmur — proof the sword had no ego. He died in his bed, grieving that a man of his scars should not die in battle: "There is no rest for the Sword of Allah but Jannah."`,
facts:[{label:"Title",value:"Sayfullah"},{label:"Before Islam",value:"Architect of Uhud's turn"},{label:"After",value:"Undefeated — Mu'tah to Yarmuk"}]},

{id:"c-abbas",titleEn:"Al-Abbas ibn Abd al-Muttalib",titleAr:"العباس بن عبد المطلب",role:"Uncle of the Prophet · The voice of Hunayn",summary:"Guardian of Zamzam, secret ally before Fath, and the rally-cry that reversed a rout.",pattern:"pattern-sahaba",
details:`Uncle of the Prophet ﷺ and custodian of the pilgrims' water, Abbas attended {{n:32|the Second Aqabah}} as his nephew's guarantor before his own Islam, and served the believers from inside Makkah until he emigrated just before {{n:41|the Opening}} — where he escorted {{c:c-abusufyan|Abu Sufyan}} to safety and Islam. At {{n:42|Hunayn}}, when the army broke in the defile, the Prophet ordered Abbas — a man of mighty voice — to call: "O companions of the tree! O companions of Surat al-Baqarah!" and the Ansar wheeled back through their own rout: labbayk, labbayk. In the famine year, Umar sought rain by his du'a: "O Allah, we used to seek rain by Your Prophet, and we seek it by his uncle." The riba of Jahiliyya was abolished at {{n:44|the Farewell Hajj}} beginning with his own claims.`,
facts:[{label:"Office",value:"Siqayah — Zamzam"},{label:"Hunayn",value:"The rally voice"},{label:"Honor",value:"Umar's istisqa by him"}]},

{id:"c-abusufyan",titleEn:"Abu Sufyan ibn Harb",titleAr:"أبو سفيان بن حرب",role:"Commander of the enemy · then companion",summary:"Led Quraysh at Uhud and the Trench — and entered Islam the night before the Opening.",pattern:"pattern-sahaba",
details:`For two decades the manager of Makkah's war: the caravan that triggered {{n:37|Badr}}, command at {{n:38|Uhud}}, the grand alliance of {{n:39|the Khandaq}}. Yet his answers to Heraclius — recorded in Bukhari — testified to the Prophet's ﷺ truthfulness even while he fought him: "We have never known him to lie." On the eve of {{n:41|the Opening}}, brought in by {{c:c-abbas|Abbas}}, he submitted; and the Prophet honored the old chief's pride into safety: "Whoever enters the house of Abu Sufyan is safe." At {{n:42|Hunayn}} he stood firm holding the Prophet's stirrup, and at Ta'if and Yarmuk he gave his eyes in Allah's cause — the last chapters rewriting the first.`,
facts:[{label:"Before",value:"Uhud & Khandaq commander"},{label:"Testimony",value:"To Heraclius: “he does not lie”"},{label:"After",value:"Fought at Yarmuk, blinded"}]},

{id:"c-uthman-talha",titleEn:"Uthman ibn Talha",titleAr:"عثمان بن طلحة",role:"Keeper of the Kaaba's key",summary:"The key was taken from him at the Opening — and returned to him forever.",pattern:"pattern-sahaba",
details:`His house of Banu Abd ad-Dar held the hijabah — custody of the Kaaba's key — from the age of Qusayy. In Jahiliyya he once refused the Prophet ﷺ entry; the Prophet said: "O Uthman, perhaps you will one day see this key in my hand, to place it where I will." At {{n:41|the Opening}}, the Prophet took the key, entered, prayed — and as {{c:c-abbas|Abbas}} and {{c:c-ali|Ali}} each hoped the custody would pass to their house, the verse descended: "Allah commands you to render trusts to their owners" (4:58). He called Uthman back: "Take it, O Banu Talha — eternally, none shall take it from you except an oppressor." The key remains in that family's hands to this day — conquest, in Islam, restores trusts.`,
facts:[{label:"Trust",value:"Hijabah — the key"},{label:"Verse",value:"4:58 revealed"},{label:"Verdict",value:"“Eternally — Banu Talha”"}]},

{id:"c-suhayl",titleEn:"Suhayl ibn Amr",titleAr:"سهيل بن عمرو",role:"Negotiator of Hudaybiyyah · Orator of steadfastness",summary:"Struck out “Rasulullah” from the treaty — then held Makkah firm for Islam at the ridda.",pattern:"pattern-sahaba",
details:`Quraysh's finest orator, sent to negotiate {{n:40|Hudaybiyyah}}, where he refused the words "Messenger of Allah" on the document and pressed every hard clause — including the return of his own son Abu Jandal, dragged back in chains. {{c:c-umar|Umar}}, enraged that day, would later say: I kept giving charity and fasting for fear of that speech of mine. Suhayl accepted Islam at {{n:41|the Opening}}, and when the Prophet ﷺ died and Makkah swayed toward apostasy, the old negotiator stood at the Kaaba and delivered the speech that held the city: "Whoever worshipped Muhammad — Muhammad has died; whoever worships Allah — Allah is Living." The tongue once hired against Islam became its anchor — exactly as the Prophet had foretold to Umar: "Perhaps he will stand a station that will please you."`,
facts:[{label:"Hudaybiyyah",value:"Erased “Rasulullah”"},{label:"Foretold",value:"“A station that will please you”"},{label:"Ridda",value:"His speech held Makkah"}]},

{id:"c-jafar",titleEn:"Ja'far ibn Abi Talib",titleAr:"جعفر بن أبي طالب",role:"The two-winged · Voice of Abyssinia",summary:"Defended the muhajirin before the Negus, and traded two arms for two wings at Mu'tah.",pattern:"pattern-sahaba",
details:`Elder brother of {{c:c-ali|Ali}} and the Prophet's ﷺ look-alike in face and character — "you resemble my form and my manners." Before the Negus of Abyssinia he delivered the emigrants' defense: we were a people of ignorance — idols, dead flesh, the strong devouring the weak — until Allah sent us a messenger whose lineage and truthfulness we know… and he recited Maryam until the king wept into his beard. He returned the day {{n:41|Khaybar fell}}: "I do not know which delights me more — the conquest of Khaybar or the coming of Ja'far." At Mu'tah he held the banner until both arms were cut, and fell; the Prophet said Allah exchanged his arms for two wings, with which he flies in Jannah wherever he wills — Ja'far at-Tayyar.`,
facts:[{label:"Abyssinia",value:"The speech before the Negus"},{label:"Mu'tah",value:"Banner — both arms"},{label:"Title",value:"At-Tayyar — two wings"}]},

{id:"c-ammar",titleEn:"Ammar ibn Yasir",titleAr:"عمار بن ياسر",role:"Son of the first martyrs · Filled with faith",summary:"Tortured beside his parents; the Prophet promised his family Paradise.",pattern:"pattern-sahaba",
details:`Son of Yasir and {{c:c-sumayyah|Sumayyah}}, the household on whom Makkah tested its cruelty. The Prophet ﷺ would pass their torture and say: "Patience, family of Yasir — your appointed place is Paradise." Under torment that no flesh sustains, Ammar spoke words of relief with a heart at rest in faith, and revelation excused him by name-case: "except one who is compelled while his heart is secure in iman" (16:106). He dug {{n:39|the Trench}} with a double share of dust, and the Prophet said of him: "Ammar is filled with faith to his collarbones." The word he ﷺ gave him — "you will be killed by the transgressing party" — settled at Siffin, where the old man fell asking for milk, remembering his Prophet's sign.`,
facts:[{label:"Family",value:"First martyrs of Islam"},{label:"Verse",value:"16:106 — the excused heart"},{label:"Word",value:"“The transgressing party”"}]},

{id:"c-sumayyah",titleEn:"Sumayyah bint Khayyat",titleAr:"سمية بنت خياط",role:"First martyr of Islam",summary:"An enslaved old woman — the first soul to die for La ilaha illallah.",pattern:"pattern-sahaba",
details:`An elderly enslaved woman of Makkah with no clan to avenge her — which is precisely why Abu Jahl chose her family for public torture, and precisely why her stand mattered most. She refused to renounce, under the sun and the stones, and Abu Jahl killed her with a spear: the first person in the history of this ummah to die for the testimony of faith. The religion whose final ranks include kings was opened, in blood, by a woman society priced at nothing. Her husband Yasir died under the same torment; her son {{c:c-ammar|Ammar}} carried their banner for sixty more years. "Patience, family of Yasir — your appointed place is Paradise."`,
facts:[{label:"Rank",value:"First martyr"},{label:"Killer",value:"Abu Jahl"},{label:"Promise",value:"“Your place is Paradise”"}]},

{id:"c-anas-nadr",titleEn:"Anas ibn an-Nadr",titleAr:"أنس بن النضر",role:"“I smell Jannah beyond Uhud”",summary:"Missed Badr, vowed Allah would see what he would do — and was found with eighty wounds.",pattern:"pattern-sahaba",
details:`He missed {{n:37|Badr}} and it burned him: "If Allah grants me a battle with His Messenger, Allah will see what I do." At {{n:38|Uhud}}, when the lines collapsed and men sat down in despair, he walked forward past them — "O Sa'd, Jannah! By the Lord of an-Nadr, I smell its fragrance from beyond Uhud" — and fought until they found him with more than eighty wounds of sword, spear, and arrow, his body known only to his sister by his fingertips. The companions held that the verse descended about him and his like: "Among the believers are men true to what they pledged to Allah" (33:23). Uncle of Anas ibn Malik, and the standing definition of making up a missed opportunity.`,
facts:[{label:"Vow",value:"After missing Badr"},{label:"Wounds",value:"80+ — known by fingertips"},{label:"Verse",value:"33:23 — “men true to the pledge”"}]},

{id:"c-hanzala",titleEn:"Hanzala ibn Abi Amir",titleAr:"حنظلة بن أبي عامر",role:"Washed by the angels",summary:"Ran from his wedding night to Uhud — and the angels performed his ghusl.",pattern:"pattern-sahaba",
details:`Married the night before {{n:38|Uhud}}, he heard the call at dawn and left before the ritual bath, plunging into the battle until he was killed. The Prophet ﷺ told the companions: "I saw the angels washing Hanzala between the sky and the earth with the water of the clouds in vessels of silver." They asked his wife, who told of the night — and the ummah gave him his eternal name: Ghasil al-Mala'ikah, the one washed by the angels. Son of Madinah's chief enemy monk, he chose his own line. The report is carried in the classical sirah and graded sound by its collectors (Ibn Hibban, al-Hakim). No image of martyrdom in the Seerah is more tender: heaven completing the sunnah the groom had no time for.`,
facts:[{label:"Left from",value:"His wedding night"},{label:"Honor",value:"Ghusl by the angels"},{label:"Name",value:"Ghasil al-Mala'ikah"}]},

{id:"c-abdullah-jubayr",titleEn:"Abdullah ibn Jubayr",titleAr:"عبد الله بن جبير",role:"Commander of the fifty archers",summary:"Held the hill at Uhud with ten men after forty left — and died at his post.",pattern:"pattern-sahaba",
details:`The Prophet ﷺ set him over the fifty archers on the hill at {{n:38|Uhud}} with the order that decided the day: "Do not leave your position even if you see the birds snatching us." When victory glittered and forty of his men descended for the spoils, Abdullah ibn Jubayr stood in the gap quoting his orders — and held the ridge with ten, against {{c:c-khalid|Khalid's}} wheeling cavalry, until every one of them fell. He obeyed the letter of a command whose wisdom the disobedient learned within the hour. In the Codex he stands for every guardian of an unglamorous post: the reward of the hill is not measured by the crowd that left it.`,
facts:[{label:"Command",value:"50 archers — the hill"},{label:"Held with",value:"10 men"},{label:"Fate",value:"Died at the post"}]},

{id:"c-wahshi",titleEn:"Wahshi ibn Harb",titleAr:"وحشي بن حرب",role:"Killer of Hamza · then of Musaylimah",summary:"The spear that killed the best of men later killed the worst.",pattern:"pattern-sahaba",
details:`An Abyssinian slave promised freedom for one throw: at {{n:38|Uhud}} his javelin killed {{c:c-hamza|Hamza}}, and he watched {{c:c-hind|Hind}} mutilate the fallen lion. After {{n:41|the Opening}} he fled until the door of tawbah found him; he came to the Prophet ﷺ, testified, and was accepted — though the Prophet, in his humanity, asked him to keep his face from him, and Wahshi complied with a debtor's humility. At Yamamah he took his old spear hunting a new target and killed Musaylimah the arch-liar. His own summary survives in Bukhari's narration: "I killed the best of people in my ignorance and the worst of people in my Islam — and I hope one cancels the other." The Codex keeps him as tawbah's hardest test case, passed.`,
facts:[{label:"Uhud",value:"Killed Hamza"},{label:"Yamamah",value:"Killed Musaylimah"},{label:"File",value:"Tawbah's hardest case"}]},

{id:"c-hind",titleEn:"Hind bint Utbah",titleAr:"هند بنت عتبة",role:"Avenger of Badr · then believer of Fath",summary:"From mutilating Hamza to pledging allegiance — the fiercest reversal in the Seerah.",pattern:"pattern-sahaba",
details:`Daughter of Utbah, who fell at {{n:37|Badr}} with her brother and son — a grief she converted into the vengeance of {{n:38|Uhud}}, hiring {{c:c-wahshi|Wahshi}} against {{c:c-hamza|Hamza}} and mutilating the martyr. At {{n:41|the Opening}} she came veiled among the pledging women, and answered the Prophet's ﷺ terms with the sharp tongue that never left her: does a free woman commit zina? — and on theft, her husband {{c:c-abusufyan|Abu Sufyan}} pardoned in advance. Accepted, she said: "O Messenger of Allah, no household on earth was more hateful to me than yours — and now no household is more beloved." At Yarmuk she stood in the women's line breaking the retreat. Islam's door, the Codex notes, was wide enough for the woman of Uhud.`,
facts:[{label:"Uhud",value:"The vengeance"},{label:"Fath",value:"The pledge & the reversal"},{label:"Yarmuk",value:"In the women's line"}]},

{id:"c-abdurrahman",titleEn:"Abd ar-Rahman ibn Awf",titleAr:"عبد الرحمن بن عوف",role:"Merchant of Paradise · Ten promised",summary:"Refused half a fortune as a gift — “show me the market” — and gave caravans away.",pattern:"pattern-sahaba",
details:`Paired at the mu'akhah with Sa'd ibn ar-Rabi', who offered him half of everything; his answer founded Muslim commercial ethics: "May Allah bless your family and wealth for you — show me the market." From a borrowed nothing he rebuilt a fortune, then spent it in convoys: seven hundred camels' cargo given in a day. One of the ten promised Paradise, one of the six of Umar's shura, and the man behind whom the Prophet ﷺ himself prayed a raka'ah at Tabuk — the only such honor. He wept over abundance: "Mus'ab was better than me and was shrouded in one cloak… I fear our reward was hastened to us here." Wealth in his hand, never in his heart.`,
facts:[{label:"Ethic",value:"“Show me the market”"},{label:"Honor",value:"He ﷺ prayed behind him"},{label:"Rank",value:"Ashara mubashara · shura"}]},

{id:"c-abu-ubaydah",titleEn:"Abu Ubaydah ibn al-Jarrah",titleAr:"أبو عبيدة بن الجراح",role:"The Trustworthy of this Ummah",summary:"“Every nation has its trustworthy one — and ours is Abu Ubaydah.”",pattern:"pattern-sahaba",
details:`Early convert, emigrant to both hijrahs, veteran of {{n:37|Badr}} and every field after — at {{n:38|Uhud}} he drew the two helmet-rings from the Prophet's ﷺ cheek with his front teeth, losing them and gaining the most honorable gap in history. The Prophet fixed his title in the Sahihayn: "Every nation has its amin — and the amin of this ummah is Abu Ubaydah ibn al-Jarrah," and sent him when Najran asked for "a trustworthy man, truly trustworthy." One of the ten promised Paradise; commander of the armies of Sham; and when the plague of Amwas took its wages, he refused to flee his post — "shall we flee from the decree of Allah? — to the decree of Allah" — and was buried with his soldiers.`,
facts:[{label:"Title",value:"Amin of this ummah"},{label:"Uhud",value:"Drew the rings — lost teeth"},{label:"End",value:"Plague of Amwas, at post"}]},

{id:"c-said-zayd",titleEn:"Sa'id ibn Zayd",titleAr:"سعيد بن زيد",role:"Son of the hanif · Ten promised Paradise",summary:"His father sought Ibrahim's religion before revelation; the son found it in full.",pattern:"pattern-sahaba",
details:`Son of Zayd ibn Amr ibn Nufayl — the hanif of {{n:24|Jahiliyya}} who refused idols and searched for the religion of {{n:9|Ibrahim}}, of whom the Prophet ﷺ said he would be raised "a nation by himself." Sa'id and his wife Fatimah bint al-Khattab believed early; it was in their house that {{c:c-umar|Umar}} heard Surah Ta-Ha and turned from executioner to brother. Among the ten promised Paradise, present at every field after {{n:37|Badr}}'s season, and famously feared in du'a: when Arwa accused him falsely over land, he prayed — O Allah, if she is lying, blind her eye and kill her in her land — and Madinah watched it happen. Piety with teeth.`,
facts:[{label:"Father",value:"The hanif Zayd ibn Amr"},{label:"House",value:"Where Umar heard Ta-Ha"},{label:"Rank",value:"Ashara mubashara"}]},

{id:"c-asma",titleEn:"Asma bint Abi Bakr",titleAr:"أسماء بنت أبي بكر",role:"Dhat an-Nitaqayn — She of the Two Belts",summary:"Fed the Hijrah from her own waistband, and taught her son to die free.",pattern:"pattern-sahaba",
details:`When the two men hid in {{n:33|Thawr}}, the supply line was a young pregnant woman climbing a mountain by night. Lacking a rope for the provisions, she tore her waistband in two — and the Prophet ﷺ named her forever Dhat an-Nitaqayn, She of the Two Belts. She faced Abu Jahl's slap without surrendering the route, raised her son Abdullah ibn az-Zubayr — the first child born to the muhajirin in Madinah — and, nearly a century old and blind, delivered the Seerah's fiercest last counsel when he feared mutilation after death: "Does the flayed sheep feel the skinning? A clean death by the sword." Daughter of {{c:c-abubakr|as-Siddiq}}, sister of {{c:c-aisha|Aisha}} — the household that carried the Hijrah on its back.`,
facts:[{label:"Hijrah",value:"The supply line"},{label:"Name",value:"Dhat an-Nitaqayn"},{label:"Son",value:"First muhajir child"}]},

{id:"c-kab",titleEn:"Ka'b ibn Malik",titleAr:"كعب بن مالك",role:"Poet of the Prophet · The truthful of Tabuk",summary:"Fifty days of silence bought him a verse of forgiveness read until the end of time.",pattern:"pattern-sahaba",
details:`One of the Prophet's ﷺ three poets, present at {{n:32|Aqabah}} and every field except {{n:37|Badr}} and one more — {{n:43|Tabuk}}, which he missed with no excuse and refused to invent one: "By Allah, if I sit before anyone other than you I could escape his anger with an argument — but I know if I lie to you today, Allah will soon anger you against me." The boycott followed: fifty days, the earth narrowing "for all its vastness," the letter from Ghassan's king burned unread, his wife sent away — until forgiveness descended from above seven heavens (9:118) and the mosque rose to congratulate him. His own verdict: "Allah never blessed me after Islam with anything greater than my truthfulness that day." The Codex files him beside every easy excuse never made.`,
facts:[{label:"Trial",value:"50 days of silence"},{label:"Refused",value:"The easy lie"},{label:"Verse",value:"9:118 — his forgiveness"}]},

{id:"c-waraqah",titleEn:"Waraqah ibn Nawfal",titleAr:"ورقة بن نوفل",role:"The scholar of the interval",summary:"The first outside witness of the revelation — “this is the Namus of Musa.”",pattern:"pattern-sahaba",
details:`Cousin of {{c:c-khadijah|Khadijah}}, one of the hunafa' of {{n:24|Jahiliyya}} who had refused the idols, become Christian, and learned the earlier scriptures until age took his sight. When Khadijah brought her trembling husband after {{n:29|Hira}}, the old scholar listened and identified the visitor from the books he knew: "This is the Namus whom Allah sent down upon Musa." He read the road ahead — expulsion, enmity, war — from the pattern of every prophet before, and pledged the support he would never live to give: "If your day reaches me, I will help you with a strength unimaginable." He died within days. The Prophet ﷺ saw him in a dream in white garments — a believer of the interval, first ally of the final revelation.`,
facts:[{label:"Learning",value:"The earlier scriptures"},{label:"Verdict",value:"“The Namus of Musa”"},{label:"Seen",value:"In white — a good end"}]}
],

angels:[
{id:"a-malakalmawt",titleEn:"Malak al-Mawt — Angel of Death",titleAr:"ملك الموت",role:"Entrusted with every soul",summary:"“Say: the angel of death, who has been entrusted with you, will take you.”",pattern:"pattern-angel",
details:`The Qur'an names his office, not his name: "Say: the angel of death, entrusted with you, will take you in full — then to your Lord you are returned" (32:11). The name "Azra'il," widespread in later books, does not occur in the Qur'an or the authentic Sunnah — the Codex records the office as revelation records it. He commands hosts: the angels of mercy who draw out the fragrant soul of the believer gently "as a drop from the waterskin's mouth," and the angels of punishment for the other extraction — both scenes detailed in the sound hadith of al-Bara'. And he obeys limits: sent to {{n:20|Musa}}, he was struck by the prophet who did not wish to die, returned to his Lord, and came back with a bargain of years measured in the hairs of a bull's hide — Bukhari and Muslim carry the account. At {{n:57|the first blast}}, his office completes itself and closes.`,
facts:[{label:"Named in",value:"32:11 — by office"},{label:"“Azra'il”",value:"Not in Qur'an/sahih"},{label:"Hosts",value:"Angels of mercy & punishment"}],
quran:[{ref:"32:11",ar:"قُلْ يَتَوَفَّاكُم مَّلَكُ الْمَوْتِ الَّذِي وُكِّلَ بِكُمْ ثُمَّ إِلَىٰ رَبِّكُمْ تُرْجَعُونَ",en:"Say: the angel of death, who has been entrusted with you, will take you — then to your Lord you will be returned."}]},

{id:"a-kiraman",titleEn:"Kiraman Katibin — The Noble Scribes",titleAr:"كرام كاتبين",role:"Recorders on the right and left",summary:"“Not a word does he utter but with him is an observer ready.”",pattern:"pattern-angel",
details:`Two on every human: "When the two receivers receive, seated on the right and on the left — not a word does he utter but with him is an observer ready" (50:17-18). The right records the good; the left, the tradition reports, is instructed toward patience — held back while the servant is given time to repent. Deeds are lifted in shifts: "angels of the night and angels of the day succeed one another among you, meeting at Fajr and Asr" — and the ascending shift is questioned about how they left His servants: praying, they answer, and praying we found them. The Codex sets them beside {{n:62|the Hisab}}: the ledgers opened on the Day are being written in this sentence, by readers of it. "And indeed, over you are keepers — noble, writing — they know whatever you do" (82:10-12).`,
facts:[{label:"Posts",value:"Right & left"},{label:"Precision",value:"Every word — 50:18"},{label:"Shifts",value:"Meet at Fajr & Asr"}],
quran:[{ref:"82:10-12",ar:"وَإِنَّ عَلَيْكُمْ لَحَافِظِينَ كِرَامًا كَاتِبِينَ يَعْلَمُونَ مَا تَفْعَلُونَ",en:"Indeed, over you are keepers — noble, writing — they know whatever you do."}]},

{id:"a-hamalat",titleEn:"Hamalat al-Arsh — Bearers of the Throne",titleAr:"حملة العرش",role:"Carriers of the greatest creation",summary:"They carry the Throne, glorify their Lord — and pray for the believers below.",pattern:"pattern-angel",
details:`Above every rank of angel stand the bearers of the {{n:1|Throne}}. Their scale defies the page: the Prophet ﷺ was given leave to speak of one of them — "between his earlobe and his shoulder is the journey of seven hundred years" (Abu Dawud, sahih). On the Day, "eight will bear the Throne of your Lord above them" (69:17). But the Qur'an's longest look at them is not at their size — it is at their occupation: "Those who carry the Throne and those around it glorify the praise of their Lord, believe in Him, and seek forgiveness for those who believe: Our Lord, You encompass all things in mercy and knowledge — so forgive those who repent and follow Your way, and spare them the punishment of Hellfire" (40:7). The mightiest creatures in existence spend their strength making du'a for the weakest believers on earth. The Codex files them as the Path's highest comfort: you are being prayed for, from directly beneath the Throne.`,
facts:[{label:"On the Day",value:"Eight — 69:17"},{label:"Scale",value:"700 years, ear to shoulder"},{label:"Occupation",value:"Du'a for the believers"}],
quran:[{ref:"40:7",ar:"الَّذِينَ يَحْمِلُونَ الْعَرْشَ وَمَنْ حَوْلَهُ يُسَبِّحُونَ بِحَمْدِ رَبِّهِمْ وَيَسْتَغْفِرُونَ لِلَّذِينَ آمَنُوا",en:"Those who carry the Throne and those around it glorify the praise of their Lord and seek forgiveness for those who believe."}]},

{id:"a-mountains",titleEn:"The Angel of the Mountains",titleAr:"ملك الجبال",role:"Offered to crush Ta'if — and was declined",summary:"“If you wish, I will bring the two mountains down upon them.”",pattern:"pattern-angel",
details:`He appears once in the record, on the worst day of the Seerah. After {{n:30|Ta'if's}} stones, {{c:a-jibril|Jibril}} called to the Prophet ﷺ: "Allah has heard what your people said to you — and He has sent you the Angel of the Mountains, to command as you will." The angel gave his greeting and made history's most terrifying offer with a servant's courtesy: "If you wish, I will bring the two Akhshabayn down upon them." The bleeding Prophet's answer defines the mission the Codex documents: "Rather, I hope that Allah will bring forth from their loins those who will worship Allah alone, associating nothing with Him." The angel of demolition met the prophet of mercy, and mercy commanded. Ta'if's grandchildren filled the mosques.`,
facts:[{label:"Appears",value:"After Ta'if — Bukhari 3231"},{label:"The offer",value:"The two Akhshabayn"},{label:"The answer",value:"“I hope from their loins…”"}]}
],

jinn:[
{id:"j-qarin",titleEn:"The Qarin — Assigned Companion",titleAr:"القرين",role:"The whisperer attached to every human",summary:"“Even me,” he ﷺ said — “but Allah helped me against him, and he submitted.”",pattern:"pattern-jinn",
details:`"There is no one among you but a companion from the jinn has been assigned to him." They said: Even you, O Messenger of Allah? He said: "Even me — but Allah helped me against him, and he aslama (submitted / I am safe from him), so he commands me with nothing but good" (Muslim 2814). The qarin is the whisper's local office: on the Day he disowns his client — "Our Lord, I did not make him transgress; he was himself in far error" (50:27) — and the two arrive as file and prosecutor: "his qarin will say: this is what is ready with me" (50:23). The defense the Prophet ﷺ prescribed is not exorcism but dhikr: the whisperer "shrinks when Allah is remembered." The Codex sets this seal beside {{c:j-iblis|Iblis}}: the general has a soldier stationed on every heart — and the heart holds the high ground with two words of remembrance.`,
facts:[{label:"Coverage",value:"Every human — one each"},{label:"His own ﷺ",value:"Submitted — only good"},{label:"On the Day",value:"Disowns the client — 50:27"}],
quran:[{ref:"50:27",ar:"قَالَ قَرِينُهُ رَبَّنَا مَا أَطْغَيْتُهُ وَلَٰكِن كَانَ فِي ضَلَالٍ بَعِيدٍ",en:"His companion will say: Our Lord, I did not make him transgress — he was himself in far error."}]}
],

animals:[
{id:"an-buraq",titleEn:"Al-Buraq",titleAr:"البراق",role:"Mount of the Night Journey",summary:"White, beyond the mule and below the donkey — its stride lands at the edge of its sight.",pattern:"pattern-animal",
details:`"I was brought al-Buraq — a white beast, taller than the donkey and shorter than the mule, whose stride lands at the farthest point of its sight" (Muslim 162). On its back the Prophet ﷺ crossed from Makkah to al-Aqsa in a night — {{n:31|the Isra}} — where he tethered it at the ring, the reports say, where the prophets tethered before him: revelation's own relay animal, serving the caravan of prophethood across the ages. Jibril accompanied; at al-Aqsa the prophets assembled behind their final brother in prayer; then the ascent went up beyond any mount's road. The Codex keeps al-Buraq among the animals of the signs as the tradition keeps it: a creature of light-speed obedience, proof that every scale of creation — beast, angel, heaven — was staged for the journey of one rider.`,
facts:[{label:"Form",value:"White — mule > it > donkey"},{label:"Stride",value:"To the edge of sight"},{label:"Tethered",value:"At the prophets' ring"}]},

{id:"an-ram",titleEn:"The Ram of the Sacrifice",titleAr:"كبش الفداء",role:"The great ransom of Mina",summary:"“And We ransomed him with a great sacrifice” — the animal that ended human sacrifice.",pattern:"pattern-animal",
details:`At the instant {{n:10|Ibrahim's}} knife had nothing left to prove, heaven substituted a ram: "And We ransomed him with a great sacrifice" (37:107). The Qur'an calls the animal azim — great — because of what it carried: the abolition, inside the very story that seemed to demand it, of offering human beings to God. Every Eid al-Adha since is that morning re-enacted; the Prophet ﷺ sacrificed two horned, black-and-white rams with his own hand, saying the takbir and setting his foot on their sides (Bukhari 5565). The Codex files the ram where the tradition files it: the most consequential animal in the history of worship — one creature standing in, forever, for every child of Adam laid on every altar of false devotion.`,
facts:[{label:"Verse",value:"37:107 — dhibh azim"},{label:"Abolished",value:"Human sacrifice"},{label:"Living rite",value:"Eid al-Adha"}],
quran:[{ref:"37:107",ar:"وَفَدَيْنَاهُ بِذِبْحٍ عَظِيمٍ",en:"And We ransomed him with a great sacrifice."}]},

{id:"an-staff",titleEn:"The Serpent of the Staff",titleAr:"حية العصا",role:"Musa's sign — “a manifest serpent”",summary:"A shepherd's tool by day, a devourer of illusions before Pharaoh.",pattern:"pattern-animal",
details:`"What is that in your right hand, O Musa?" — a staff: I lean on it, I bring down leaves for my sheep. "Throw it down." And it became a rushing serpent — {{n:17|at Tuwa}} a training in fearlessness ("take it and do not fear; We will return it to its former state"), and before Pharaoh "a manifest serpent" (7:107) that swallowed the ropes and rods of the magicians' theater. The professionals fell in prostration first — they alone knew the difference between trick and creation. The Codex lists the serpent among the sign-creatures with a jurist's note: the animal existed at Allah's command inside a tool, the way every "solid" thing in the Path exists — {{n:9|fire that cools}}, {{n:18|sea that stands}} — matter awaiting instructions.`,
facts:[{label:"First shown",value:"Tuwa — 20:20"},{label:"Before Pharaoh",value:"“Manifest serpent” 7:107"},{label:"Convinced first",value:"The magicians themselves"}]}
],

endtime:[
{id:"e-mahdi",titleEn:"Al-Mahdi",titleAr:"المهدي",role:"The rightly-guided ruler of the last days",summary:"Of Fatimah's line, name matching the Prophet's — seven years of justice before the end.",pattern:"pattern-beast",
details:`A man of the Prophet's ﷺ house — "of the sons of {{c:c-fatimah|Fatimah}}," his name matching the Prophet's name — whom Allah rectifies in a night and sends when the earth is full of wrong: "he will fill it with fairness and justice as it was filled with oppression and wrong, and rule seven years" (Abu Dawud). Wealth in his days is given without counting. He is not named "Mahdi" in Bukhari and Muslim — the Codex says so plainly — but he stands described there: the imam of the believers behind whom {{c:e-isa-return|Isa ibn Maryam}} prays at Fajr in Damascus, and the man at the House against whom an army marches and is swallowed at al-Bayda (Muslim 2882). His full file is at Path node {{n:47|Al-Mahdi}}. His counterfeits — thirty dajjals claiming his cloak across history — are themselves one of the signs he was promised.`,
facts:[{label:"Line",value:"Sons of Fatimah"},{label:"Rule",value:"Seven years"},{label:"Honor",value:"Isa prays behind him"}]},

{id:"e-jassasa",titleEn:"Al-Jassasah",titleAr:"الجساسة",role:"The spy-beast of the island",summary:"“I am al-Jassasah — go to that monastery, for a man there longs for your news.”",pattern:"pattern-beast",
details:`The strangest witness statement in the canon — told by Tamim ad-Dari, a Christian sailor who became Muslim, and then retold by the Prophet ﷺ from the minbar because it confirmed what he had been teaching (Muslim 2942). Storm-driven for a month, Tamim's crew landed on an island where "a beast of abundant hair, they knew not front from back" met them: "I am al-Jassasah" — the gatherer of news — and it directed them to the monastery, where a shackled giant interrogated them: do the palms of Baysan still fruit? does the lake of Tiberias still hold water? has the prophet of the unlettered emerged? Then the declaration: "I am {{c:e-dajjal|al-Masih (ad-Dajjal)}} — and I am about to be given leave to emerge." The Codex keeps the Jassasah as the file's eeriest exhibit: the last fitnah already exists, already chained, already asking about the water levels.`,
facts:[{label:"Source",value:"Muslim 2942 — from the minbar"},{label:"Function",value:"Gathers news for the chained one"},{label:"The questions",value:"Baysan · Tiberias · the Prophet"}]}
]
}
};
