// NOOR Places hub: the geography of the Codex. 35 places, five sections.
// Every claim sourced; no em dashes; links to nodes {{n:}}, characters {{c:}}, places {{p:}}, words {{w:}}.
export default {

sanctuaries:[
{id:"p-kaaba",titleEn:"The Kaaba & al-Masjid al-Haram",titleAr:"الكعبة والمسجد الحرام",role:"The First House · Qiblah of mankind",summary:"Raised by Ibrahim and Isma'il, ringed by idols, purified at the Opening: the axis every prayer on earth turns toward.",pattern:"pl-sanctuary",
details:`"The first House established for mankind was that at Bakkah, blessed, and a guidance for the worlds" (3:96). {{n:11|Ibrahim and Isma'il raised its foundations}} begging acceptance; forty centuries of pilgrims have answered {{n:11|the proclamation}} made from its hill. One prayer within the surrounding mosque outweighs a hundred thousand elsewhere (Ibn Majah 1406, sahih).

Its biography is the Path in miniature: ringed with {{n:24|360 idols}} in the long forgetting, defended by {{n:25|birds}} when no believer could defend it, circled secretly by the persecuted, set as {{n:36|the qiblah}} in the second year of the Hijrah, purified by {{n:41|the Opening}} while {{c:c-bilal|Bilal}} stood on its roof, and destined, after the last believer is taken, for {{c:e-suwayqatayn|the thin-legged demolisher}}. Its key rests with {{c:c-uthman-talha|Banu Talha}} by the verse of trusts. The Black Stone at its corner descended, the Prophet ﷺ said, whiter than milk, and the sins of the children of Adam darkened it (Tirmidhi 877, hasan). Whoever cannot reach it turns toward it: five times daily, the planet quietly agrees on one point.`,
facts:[{label:"Rank",value:"First House (3:96)"},{label:"Prayer value",value:"100,000×"},{label:"Builders",value:"Ibrahim & Isma'il"},{label:"Purified",value:"8 AH, the Opening"},{label:"Key",value:"Banu Talha, forever"}],
quran:[{ref:"3:96",ar:"إِنَّ أَوَّلَ بَيْتٍ وُضِعَ لِلنَّاسِ لَلَّذِي بِبَكَّةَ مُبَارَكًا وَهُدًى لِّلْعَالَمِينَ",en:"The first House established for mankind was that at Bakkah, blessed, and a guidance for the worlds."}],
hadith:[{text:"One prayer in this mosque of mine is better than a thousand prayers elsewhere, except al-Masjid al-Haram.",source:"Bukhari 1190 · Muslim 1394"}]},

{id:"p-madinah-masjid",titleEn:"Al-Masjid an-Nabawi & the Rawdah",titleAr:"المسجد النبوي والروضة",role:"His mosque ﷺ · A garden of Paradise",summary:"Built by his own hands on the orphans' lot; between his house and his minbar lies a garden of Jannah.",pattern:"pl-sanctuary",
details:`When {{n:36|al-Qaswa knelt}}, the Prophet ﷺ bought the drying-yard of two orphans at a fair price and built, with his own hands in the brick-line, the headquarters of the religion: mosque, school, court, shelter for the poor of as-Suffah, and along its wall the rooms of his household. One prayer in it is better than a thousand elsewhere, except {{p:p-kaaba|the Sacred Mosque}} (Bukhari 1190).

Inside it lies the most precisely surveyed real estate in the tradition: "between my house and my minbar is a garden from the gardens of Jannah" (Bukhari 1195, Muslim 1390), the Rawdah, where the ummah still crowds shoulder to shoulder to stand momentarily in a plot heaven has annexed. Here {{n:44|the pilgrims' rites were taught}}, here {{c:c-abubakr|Abu Bakr}} led the prayer of the final illness, and here, in {{c:c-aisha|Aisha's}} room on its edge, {{n:45|the Prophet was buried}} where he died. Visiting greetings are given to him and his two companions to this day. The mosque of the emigrant grew into the ummah's second sanctuary; its minbar, he said, stands over his Basin.`,
facts:[{label:"Land",value:"Bought from two orphans"},{label:"Prayer value",value:"1,000×"},{label:"The Rawdah",value:"A garden of Jannah"},{label:"Holds",value:"His grave ﷺ, Abu Bakr, Umar"}],
hadith:[{text:"Between my house and my minbar is a garden from the gardens of Jannah, and my minbar is upon my Basin.",source:"Bukhari 1195 · Muslim 1390"}]},

{id:"p-aqsa",titleEn:"Al-Masjid al-Aqsa",titleAr:"المسجد الأقصى",role:"First qiblah · Station of the Isra",summary:"Second mosque ever placed on earth, terminus of the Night Journey, prayer-hall of all the prophets for one night.",pattern:"pl-sanctuary",
details:`Abu Dharr asked which mosque was placed on earth first; the Prophet ﷺ answered al-Masjid al-Haram, then al-Aqsa, "and between them forty years" (Bukhari 3366, Muslim 520). The Qur'an's single most concentrated sentence of geography binds the two forever: "Glory to Him who took His servant by night from al-Masjid al-Haram to al-Masjid al-Aqsa, whose surroundings We have blessed" (17:1).

On {{n:31|the night of the Isra}}, {{c:an-buraq|al-Buraq}} was tethered at its ring and the prophets assembled behind their final brother in prayer: the transfer of the imamate of mankind, performed in the building's own liturgy. It was the first qiblah of this ummah, faced for sixteen or seventeen months in Madinah until {{n:36|the verse of turning}}. It is one of only three mosques to which journeys may be set out (Bukhari 1189), and its opening to the ummah came bloodlessly under {{c:c-umar|Umar}}, who cleaned its rock with his own cloak. The end of time keeps appointments here too: the file of {{n:50|the hordes}} and the era of {{n:49|Isa's justice}} run through this land, "whose surroundings We have blessed."`,
facts:[{label:"Placed",value:"2nd on earth, +40 years"},{label:"First qiblah",value:"16-17 months"},{label:"Isra",value:"All prophets prayed behind him ﷺ"},{label:"Journeys",value:"One of the three mosques"}],
quran:[{ref:"17:1",ar:"سُبْحَانَ الَّذِي أَسْرَىٰ بِعَبْدِهِ لَيْلًا مِّنَ الْمَسْجِدِ الْحَرَامِ إِلَى الْمَسْجِدِ الْأَقْصَى الَّذِي بَارَكْنَا حَوْلَهُ",en:"Glory to Him who took His servant by night from the Sacred Mosque to the Furthest Mosque, whose surroundings We have blessed."}]},

{id:"p-quba",titleEn:"Masjid Quba",titleAr:"مسجد قباء",role:"Founded on taqwa from the first day",summary:"The first mosque this ummah ever built; a Saturday habit of the Prophet ﷺ, and an umrah's reward for two rak'ahs.",pattern:"pl-sanctuary",
details:`On the southern approach to Madinah, {{n:35|the first free Muslim building}} rose before the city itself was reached: the Prophet ﷺ halted among Banu Amr ibn Awf, laid stones with his own hands, and prayed in the mosque whose certificate came down from heaven: "a mosque founded on taqwa from the first day is more worthy that you stand within it; in it are men who love to purify themselves" (9:108).

The attachment never faded: "the Prophet ﷺ used to come to Quba every Saturday, riding or walking, and pray two rak'ahs" (Bukhari 1193, Muslim 1399), and he priced the visit for the rest of history: "whoever purifies himself in his house, then comes to the mosque of Quba and prays in it, has the reward of an umrah" (Ibn Majah 1412, sahih). The Qur'an contrasted it explicitly with the mosque of harm built {{n:43|near Tabuk's season}} to divide the believers: identical architecture, opposite foundations. Quba stands in the Codex as the standing proof that a building is judged by its founding intention, and that the cheapest umrah on earth is two rak'ahs and a short ride away for the people of one city.`,
facts:[{label:"Rank",value:"First mosque of the ummah"},{label:"Certificate",value:"9:108, taqwa from day one"},{label:"His habit ﷺ",value:"Every Saturday"},{label:"Reward",value:"An umrah, for two rak'ahs"}],
quran:[{ref:"9:108",ar:"لَّمَسْجِدٌ أُسِّسَ عَلَى التَّقْوَىٰ مِنْ أَوَّلِ يَوْمٍ أَحَقُّ أَن تَقُومَ فِيهِ",en:"A mosque founded on taqwa from the first day is more worthy that you stand within it."}]}
],

mountains:[
{id:"p-hira",titleEn:"Cave of Hira · Jabal an-Nur",titleAr:"غار حراء · جبل النور",role:"Where the sky first spoke",summary:"A rock cell above Makkah, facing the Kaaba, where five verses re-aimed history.",pattern:"pl-mountain",
details:`The Mountain of Light earns its name from one small hollow near its summit: a cell of rock barely a man's length, its mouth aimed at {{p:p-kaaba|the Kaaba}}. Here the man Makkah called al-Amin practiced {{n:28|tahannuth}}, provisioned by {{c:c-khadijah|Khadijah}}, climbing away from a city of idols night after night for years.

In Ramadan of his fortieth year the visitor came. {{c:a-jibril|Jibril}} filled the cell, pressed him three times to the limit of endurance, and released into the world the first words of the final Book: {{n:29|Iqra}}. "Read, in the name of your Lord who created" (96:1). The mountain held the weight of that night once more in the tradition's memory: Hira trembled beneath the Prophet ﷺ and his companions years later, and he stilled it: "be firm, Hira, for upon you are none but a prophet, a siddiq, and martyrs" (Muslim 2417). No shrine stands there and none is prescribed; the summit's honor is textual, not ritual. The Codex maps it as the exact coordinates where heaven resumed contact with the earth.`,
facts:[{label:"Mountain",value:"Jabal an-Nur, Makkah"},{label:"The cell",value:"Faces the Kaaba"},{label:"The night",value:"Ramadan, year 40"},{label:"First words",value:"Iqra (96:1-5)"}],
hadith:[{text:"Be firm, Hira: upon you are none but a prophet, a siddiq, and martyrs.",source:"Muslim 2417"}]},

{id:"p-thawr",titleEn:"Cave of Thawr",titleAr:"غار ثور",role:"Shelter of the second of two",summary:"Three nights, two men, and a verse that made a rock cavity part of the creed.",pattern:"pl-mountain",
details:`South of Makkah, opposite the road anyone would watch, the mountain of Thawr hides the cavity where {{n:33|the Hijrah}} held its breath for three nights. Inside: the Prophet ﷺ and {{c:c-abubakr|Abu Bakr}}, whose fear was not for himself; outside: a hundred-camel bounty and search parties close enough to be seen by their feet.

The exchange inside entered the Qur'an and the creed together. Abu Bakr whispered that a glance downward would discover them; the answer became {{w:w-la-tahzan|a permanent sentence of the religion}}: "do not grieve, indeed Allah is with us" (9:40), and in Bukhari's wording: "what do you think, O Abu Bakr, of two, Allah is their third?" The logistics were a family's quiet heroism: {{c:c-asma|Asma}} climbing with food by night, her brother carrying the city's gossip, a freedman's flock erasing footprints. The popular spider and dove at the entrance rest on weak chains, and the Codex says so plainly; the Qur'an credits the concealment to "soldiers you did not see." Thawr's teaching stands opposite {{p:p-hira|Hira's}}: one cave received revelation, the other proved reliance on it.`,
facts:[{label:"Nights",value:"Three"},{label:"Occupants",value:"Two; Allah the third"},{label:"Supply line",value:"Asma, She of the Two Belts"},{label:"Spider story",value:"Weak chains, noted honestly"}],
quran:[{ref:"9:40",ar:"إِذْ يَقُولُ لِصَاحِبِهِ لَا تَحْزَنْ إِنَّ اللَّهَ مَعَنَا",en:"When he said to his companion: do not grieve, indeed Allah is with us."}]},

{id:"p-uhud-mount",titleEn:"Mount Uhud",titleAr:"جبل أحد",role:"“A mountain that loves us”",summary:"Red granite over Madinah's north: battlefield, graveyard of seventy martyrs, and the only mountain with a certified friendship.",pattern:"pl-mountain",
details:`Uhud walls Madinah's north in red granite, and carries a testimonial no other landform holds: "this is a mountain that loves us, and we love it" (Bukhari 4083, Muslim 1365). The Prophet ﷺ said it returning from campaign, when the sight of Uhud meant home.

At its feet the ummah took {{n:38|its bitterest early lesson}}: the archers' hill abandoned, {{c:c-hamza|Hamza}} and seventy martyrs buried where they fell, in the graves the city still visits with salam. On its slopes the Prophet bled, and his tooth broke, and {{c:c-talha|Talha's}} hand took the arrows meant for his face. Once, the mountain itself shook beneath the four it carried, and was told: "be firm, Uhud, for upon you are a prophet, a siddiq, and two martyrs" (Bukhari 3675), a sentence that quietly foretold how {{c:c-umar|Umar}} and {{c:c-uthman|Uthman}} would die. The Prophet fixed its size as the ummah's unit of moral measure: gold equal to Uhud would not settle what a companion's handful of deeds weighs, and {{c:c-ibnmasud|Ibn Mas'ud's}} two shins outweigh it on the Scale.`,
facts:[{label:"Certified",value:"Mutual love, Bukhari 4083"},{label:"Holds",value:"Hamza & the seventy"},{label:"Trembled under",value:"Prophet, siddiq, two martyrs"},{label:"Unit of measure",value:"“Gold like Uhud…”"}],
hadith:[{text:"This is a mountain that loves us, and we love it.",source:"Bukhari 4083 · Muslim 1365"}]},

{id:"p-tur",titleEn:"Mount at-Tur (Sinai)",titleAr:"طور سيناء",role:"The mountain Allah swears by",summary:"Site of the burning tree, the forty nights, and the manifestation that turned rock to dust.",pattern:"pl-mountain",
details:`Only a handful of created things receive the honor of a divine oath; this mountain opens a surah with one: "By at-Tur" (52:1), and stands inside another: "by the fig and the olive, and Mount Sinin" (95:1-2). At its side {{n:17|Musa saw the fire}} and heard, in the valley of {{p:p-tuwa|Tuwa}}, the address every muwahhid memorizes: "indeed, I am Allah; there is no god but Me" (20:14).

Here he returned for {{n:20|the forty nights}}, received the Tablets "in whose inscription is guidance and mercy," and made the request that measured all requests: show me. "You will not see Me; but look at the mountain." The manifestation came to the summit and leveled it, and Musa fell unconscious (7:143). The mount kept later appointments too: raised over Bani Israel as a canopy for the covenant (2:63), and appointed in Muslim 2937 as the refuge where {{n:49|Isa}} will shelter the believers while {{n:50|the hordes}} pass. {{n:64|What Sinai could not withstand}}, the Codex notes at its final tile, the people of Jannah will be granted at home.`,
facts:[{label:"Divine oath",value:"52:1 · 95:2"},{label:"The address",value:"20:14, at its valley"},{label:"7:143",value:"Leveled by the manifestation"},{label:"End times",value:"Isa's refuge (Muslim 2937)"}],
quran:[{ref:"7:143",ar:"فَلَمَّا تَجَلَّىٰ رَبُّهُ لِلْجَبَلِ جَعَلَهُ دَكًّا وَخَرَّ مُوسَىٰ صَعِقًا",en:"When his Lord manifested to the mountain, He leveled it, and Musa fell unconscious."}]},

{id:"p-safa-marwah",titleEn:"As-Safa & al-Marwah",titleAr:"الصفا والمروة",role:"The two hills of Hajar's run",summary:"A desperate mother's seven crossings became a pillar of pilgrimage: the only footsteps ritualized forever.",pattern:"pl-mountain",
details:`Two low hills flank the valley of {{p:p-kaaba|the House}}, and between them runs the only choreography in worship copied from a woman in crisis. When the water skin emptied and the infant Isma'il writhed, Hajar climbed as-Safa scanning the valley, crossed to al-Marwah, and back, seven times, until {{p:p-zamzam|the answer broke from the ground}} under the angel's strike. The Prophet ﷺ sealed the memory: "may Allah have mercy on the mother of Isma'il" (Bukhari 3364).

Revelation ratified her footsteps into law: "indeed, as-Safa and al-Marwah are among the symbols of Allah" (2:158); every pilgrim's sa'i walks her exact route, and the men jog the stretch where she ran. From as-Safa's top the Prophet later made {{n:29|his first public call}}, asking Makkah if they would believe a raider behind the hill, and receiving the answer his character had already earned: we have never known a lie from you. One hill holds the run of a trusting mother, the other the cry of a trusted son; between them, the religion says, walk.`,
facts:[{label:"Origin",value:"Hajar's seven crossings"},{label:"Law",value:"2:158, symbols of Allah"},{label:"Also",value:"First public call, from as-Safa"},{label:"Rite",value:"The sa'i, every Hajj & umrah"}],
quran:[{ref:"2:158",ar:"إِنَّ الصَّفَا وَالْمَرْوَةَ مِن شَعَائِرِ اللَّهِ",en:"Indeed, as-Safa and al-Marwah are among the symbols of Allah."}]},

{id:"p-arafat",titleEn:"The Plain of Arafat",titleAr:"عرفات",role:"The Hajj itself · Rehearsal of the Standing",summary:"One afternoon a year, one plain, and more emancipations from the Fire than any other day grants.",pattern:"pl-mountain",
details:`"The Hajj is Arafah" (Tirmidhi 889, sahih): the Prophet ﷺ reduced the entire pilgrimage to one afternoon of standing on this plain east of {{p:p-makkah|Makkah}}. Here he delivered {{n:44|the Farewell Sermon}} from al-Qaswa's back, here the verse of completion descended on a Friday, and here he taught that the finest thing he and the prophets before him ever said was said on this ground: {{w:w-shahada|la ilaha illallah}}.

The day's economy is mercy at scale: "there is no day on which Allah frees more servants from the Fire than the day of Arafah; He draws near and boasts of them to the angels: what do these want?" (Muslim 1348). Fasting the day, for the non-pilgrim, expiates two years (Muslim 1162). And the plain is a rehearsal with the props of the real performance: multitudes in two unstitched cloths, standing exposed under one sun, asking. {{n:59|The Mawqif of the Last Day}} will feel familiar to whoever stood here well; the Codex maps Arafat as the only place on earth where the Hereafter holds annual auditions.`,
facts:[{label:"Rule",value:"“The Hajj is Arafah”"},{label:"Mercy",value:"Most freed from the Fire"},{label:"Sermon & 5:3",value:"Delivered here, 10 AH"},{label:"Fast (non-pilgrim)",value:"Expiates two years"}],
hadith:[{text:"There is no day on which Allah frees more servants from the Fire than the day of Arafah.",source:"Muslim 1348"}]},

{id:"p-mina",titleEn:"Mina & the Jamarat",titleAr:"منى والجمرات",role:"Valley of the sacrifice · Days of Tashriq",summary:"Where the knife was stopped and the ram descended; the pilgrims' tent city of dhikr, eating, and stoning the old whisperer.",pattern:"pl-mountain",
details:`East of Makkah, the valley of Mina holds the oldest completed test in the Codex: here, by the dominant reading, {{n:10|Ibrahim laid his son down}}, and here the ransom descended, "We ransomed him with a great sacrifice" (37:107). Every Eid al-Adha since is this valley's anniversary, wherever the believer's sacrifice is made.

The tradition maps the whisperer onto the geography: at these stations Shaytan appeared to Ibrahim urging him to fail the test, and at each the Friend of Allah drove him off with stones; the three Jamarat pillars mark the campaign, and every pilgrim re-enacts the contempt, seven pebbles at a time, takbir with each throw. The Prophet ﷺ spent the days of Tashriq here and defined them: "days of eating, drinking, and remembrance of Allah" (Muslim 1141); from here {{n:44|the sermon of the days of Tashriq}} declared no Arab above a non-Arab except by taqwa. A tent city with no permanent resident, assembled for obedience and folded away: Mina is the Codex's architecture lesson that some places exist purely as verbs.`,
facts:[{label:"The test",value:"The sacrifice, ransomed"},{label:"Jamarat",value:"Three stations of refusal"},{label:"Days of Tashriq",value:"Eating, drinking, dhikr"},{label:"Nature",value:"A city that exists as a verb"}],
quran:[{ref:"37:107",ar:"وَفَدَيْنَاهُ بِذِبْحٍ عَظِيمٍ",en:"And We ransomed him with a great sacrifice."}]}
],

cities:[
{id:"p-makkah",titleEn:"Makkah · Umm al-Qura",titleAr:"مكة المكرمة",role:"Mother of cities · Sanctuary since the heavens",summary:"“By Allah, you are the best of Allah's earth… had I not been driven out of you, I would not have left.”",pattern:"pl-city",
details:`An uncultivated valley given a future by one du'a: {{n:11|Ibrahim}} settled his family "in a valley without vegetation, by Your Sacred House," and asked for hearts to incline and fruits to arrive (14:37). Both requests are still being fulfilled daily. Its sanctity is not municipal but cosmic: "this city was made sacred by Allah the day He created the heavens and the earth" (Bukhari 1834), its game unhunted, its trees uncut, its ground the only place on earth where the rules were written before the residents.

It birthed the final Prophet ﷺ, {{n:26|in the Year of the Elephant}}, resisted him for thirteen years, {{n:30|stoned his message}}, {{n:33|exiled him}}, and was conquered by him {{n:41|with almost no blood}} and total amnesty. His feelings on leaving are on record, addressed to the city itself: "by Allah, you are the best of Allah's earth, and the most beloved of Allah's earth to Allah; had I not been driven out of you, I would not have left" (Tirmidhi 3925, sahih). Guarded by angels from {{c:e-dajjal|the Dajjal}}, host of {{p:p-kaaba|the House}}, {{p:p-safa-marwah|the two hills}}, and {{p:p-hira|the cave of light}}: the mother of cities holds a third of the Codex inside her valley.`,
facts:[{label:"Title",value:"Umm al-Qura (6:92)"},{label:"Sanctity",value:"Since the heavens and earth"},{label:"His word ﷺ",value:"“Best of Allah's earth”"},{label:"Dajjal",value:"Cannot enter"}],
hadith:[{text:"By Allah, you are the best of Allah's earth and the most beloved of Allah's earth to Allah; had I not been driven out of you, I would not have left.",source:"Tirmidhi 3925 (sahih)"}]},

{id:"p-madinah",titleEn:"Madinah · Tabah",titleAr:"المدينة المنورة",role:"The city that expels its dross",summary:"Renamed by heaven, guarded at every pass, and loved with a du'a for double the blessing of Makkah.",pattern:"pl-city",
details:`Yathrib died as a name the day {{n:36|the emigrant arrived}}; "it is Tabah," he ﷺ said, the good one, a city Allah renamed (Muslim 1385). Its charter of sanctity parallels its elder sister's: sacred between its two lava fields, its game and trees protected (Muslim 1362). Its quality control is active: "it is like the bellows, expelling its impurity and brightening its good" (Bukhari 1871), and in {{c:e-dajjal|the Dajjal's}} hour it will shake three times and shake the hypocrites out.

He ﷺ prayed for it competitively: "O Allah, place in Madinah double the blessing You placed in Makkah" (Bukhari 1885), and taught the patience-contract of residence: whoever endures its hardship, "I will be an intercessor or witness for him on the Day of Rising" (Muslim 1374, 1378). Angels hold its passes so that neither plague nor the Dajjal enters (Bukhari 1880). It received the Hijrah, ratified {{n:32|the pledges}}, built {{p:p-madinah-masjid|the mosque}}, buried {{n:45|the Prophet ﷺ}} and most of his companions in al-Baqi, and remains what he made it: the capital city of the sunnah, where dying is itself a du'a he taught {{c:c-umar|Umar}} to make.`,
facts:[{label:"Renamed",value:"Tabah, by heaven"},{label:"Defense",value:"Angels at every pass"},{label:"Du'a",value:"Double Makkah's blessing"},{label:"Mechanism",value:"The bellows: expels dross"}],
hadith:[{text:"Madinah is like the bellows: it expels its impurity and brightens its good.",source:"Bukhari 1871 · Muslim 1383"}]},

{id:"p-taif",titleEn:"Ta'if",titleAr:"الطائف",role:"The city of stones that became a city of Islam",summary:"It bloodied the sandals of the best of creation; a generation later its children filled the mosques he hoped for.",pattern:"pl-city",
details:`A garden city on the heights south of Makkah, cool, walled, and proud, Ta'if received {{n:30|the Prophet's ﷺ quietest mission}} and returned the Seerah's cruelest afternoon: chiefs who mocked, and a street of slaves and boys set loose with stones until blood filled his sandals. In the orchard outside its wall he made {{w:w-taif-dua|the complaint of the weak}}, and above it he declined {{c:a-mountains|the Angel of the Mountains'}} offer with the hope that named this city's future: from their loins, worshippers of Allah alone.

The hope compounded fast. Ta'if sent its fighters against {{n:42|Hunayn}} and lost; the Muslims besieged its wall and lifted the siege with the du'a the city never knew it received: "O Allah, guide Thaqif and bring them" (Tirmidhi 3942). Within the year its delegation arrived, negotiated, submitted, and the idol of al-Lat was pulled down by the city's own hands. The boy who carried grapes to the bleeding Prophet in that orchard, Addas, had asked the right question a decade early. The Codex keeps Ta'if as the patron city of long games: nowhere in the Seerah is the distance between a wound and its healing measured so exactly.`,
facts:[{label:"The afternoon",value:"Stones, blood in the sandals"},{label:"The refusal",value:"Two mountains, declined"},{label:"The du'a",value:"“Guide Thaqif and bring them”"},{label:"The return",value:"Delegation, within a year of Hunayn"}],
hadith:[{text:"O Allah, guide Thaqif and bring them.",source:"Tirmidhi 3942 (hasan)"}]},

{id:"p-jerusalem",titleEn:"Al-Quds · The Blessed Land",titleAr:"القدس والأرض المباركة",role:"Land of the prophets · Second of the sanctuaries' story",summary:"Promised to Musa's people if they entered striving, opened to this ummah by a caliph on foot.",pattern:"pl-city",
details:`The Qur'an calls its region "the land We blessed for the worlds" (21:71): {{n:9|Ibrahim's}} destination out of the fire, {{n:23|Maryam's}} chamber and Zakariya's mihrab, the holy land Musa's generation refused to enter and wandered forty years outside (5:21-26). At its heart stands {{p:p-aqsa|al-Aqsa}}, the second mosque placed on earth.

Its role in this ummah's story is a chain of solemn handovers: first qiblah; terminus of {{n:31|the Isra}}; opened without sack in the caliphate of {{c:c-umar|Umar}}, who entered leading his camel in turn with his servant and cleaned the neglected rock with his own garment; and named by the Prophet ﷺ among the six signs he told {{c:c-hudhayfah|the companions}} to count: "the conquest of Bayt al-Maqdis" (Bukhari 3176). The end of the story returns here as the beginning did: the era of {{n:49|Isa's justice}} runs through this land, and the hadith of the fitan calls it the land of the muster. The Codex holds al-Quds the way the tradition does: not as a prize but as an amanah, a trust whose keeping measures the ummah holding it.`,
facts:[{label:"Verse",value:"Blessed for the worlds (21:71)"},{label:"Holds",value:"Al-Aqsa, the second mosque"},{label:"Opened",value:"By Umar, on foot, no sack"},{label:"Counted",value:"Among the six signs (Bukhari 3176)"}],
quran:[{ref:"21:71",ar:"وَنَجَّيْنَاهُ وَلُوطًا إِلَى الْأَرْضِ الَّتِي بَارَكْنَا فِيهَا لِلْعَالَمِينَ",en:"We delivered him and Lut to the land We blessed for the worlds."}]},

{id:"p-egypt",titleEn:"Egypt of the Pharaohs",titleAr:"مصر",role:"Stage of Yusuf's rise and Musa's exodus",summary:"Granary of Yusuf, furnace of Bani Israel, and the estate Allah transferred overnight.",pattern:"pl-city",
details:`Two of the Qur'an's longest dramas play out on Egypt's stage. {{n:13|Yusuf}} entered it in chains from the caravan, survived its palace and its prison, and rose over "the storehouses of the land" (12:55) to feed the region through seven locked years; his family's migration at his invitation planted Bani Israel by the Nile. Generations later the hospitality had become {{n:15|a machinery of infanticide}}: "Pharaoh exalted himself in the land and made its people factions" (28:4).

Egypt then hosted the longest argument between heaven and a throne: nine signs, {{n:23|the duel of the magicians}} in which the professionals prostrated first, the plagues, and the night flight that ended at {{p:p-parted-sea|the sea}}. The estate transfer was recorded with the coldness of a deed: "how many gardens and springs they left behind… thus We caused another people to inherit them" (44:25-28). The Prophet ﷺ later commended Egypt to his ummah by kinship and covenant: be good to its people, "for they have protection (dhimmah) and kinship" (Muslim 2543), Hajar and Maryam's ties running through it. Opened under {{c:c-amr|Amr ibn al-As}}, it became a fortress of the religion, as it had been a fortress against it.`,
facts:[{label:"Yusuf",value:"Over its storehouses"},{label:"Pharaoh",value:"Factions & infanticide (28:4)"},{label:"Transfer",value:"44:25-28, overnight"},{label:"His counsel ﷺ",value:"Kinship & dhimmah (Muslim 2543)"}],
quran:[{ref:"43:51",ar:"وَنَادَىٰ فِرْعَوْنُ فِي قَوْمِهِ قَالَ يَا قَوْمِ أَلَيْسَ لِي مُلْكُ مِصْرَ",en:"Pharaoh called out among his people: O my people, does not the kingdom of Egypt belong to me…?"}]},

{id:"p-madyan",titleEn:"Madyan",titleAr:"مدين",role:"The refuge that hired the fugitive",summary:"A well, two sisters, ten years of shepherd's wages: where Musa learned everything Pharaoh's palace never taught.",pattern:"pl-city",
details:`Northwest Arabia's caravan country, home of {{n:16|the people Shu'ayb warned}} about scales and measures, and later the sanctuary where {{n:16|Musa}} arrived with nothing but the du'a of the emptied: "my Lord, I am, for whatever good You send down to me, in need" (28:24). Its well is the Qur'an's classic scene of strength serving instead of taking: the crowding shepherds, the two held-back sisters, the stranger who watered for them and asked for nothing.

The city's elder, often identified with Shu'ayb in tafsir though the Book leaves him unnamed, ran the interview on his daughter's two-word resume for the stranger, "the strong, the trustworthy" (26:26), and structured the marriage contract as employment: eight years, completed as ten. Madyan gave Musa what {{p:p-egypt|Egypt}} could not: obscurity, honest labor, a family, and a decade of flocks under open sky, the apprenticeship the Prophet ﷺ said every prophet served: "Allah sent no prophet but that he herded sheep" (Bukhari 2262). From its quiet the road led to {{p:p-tuwa|the burning tree}}. The Codex files Madyan under the geography of preparation: some places exist to make you ready for the place after them.`,
facts:[{label:"People of",value:"Shu'ayb's warning"},{label:"The well",value:"Strength that serves"},{label:"Contract",value:"8 years, completed 10"},{label:"Function",value:"The apprenticeship decade"}],
quran:[{ref:"28:24",ar:"رَبِّ إِنِّي لِمَا أَنزَلْتَ إِلَيَّ مِنْ خَيْرٍ فَقِيرٌ",en:"My Lord, I am, for whatever good You send down to me, in need."}]},

{id:"p-saba",titleEn:"Saba · Ma'rib",titleAr:"سبأ ومأرب",role:"Two gardens, one dam, and a queen",summary:"The kingdom the hoopoe reported, the throne that crossed the world, and the flood that audited ingratitude.",pattern:"pl-city",
details:`Yemen's Saba was the Qur'an's showcase of engineered abundance: "two gardens, on the right and the left; eat of your Lord's provision and thank Him: a good land, and a forgiving Lord" (34:15). The great dam at Ma'rib watered a civilization; its queen ruled from "a mighty throne," and her people bowed to the sun until {{c:an-hoopoe|a bird}} filed the report that changed the kingdom's religion.

{{n:22|Sulayman's}} letter opened with Bismillah; the queen's counsel chose diplomacy over her generals' appetite; her throne arrived in his court before her, carried by "one with knowledge of the Book" in the return of a glance; and at the glass floor she surrendered her empire's error with the cleanest conversion formula in scripture: "my Lord, I have wronged myself, and I submit with Sulayman to Allah, Lord of the worlds" (27:44). Generations later the gratitude lapsed, and the audit came through the dam: "We sent upon them the flood of al-Arim" (34:16), two gardens downgraded to thorn and tamarisk, a people scattered into a proverb. Saba's twin files, the queen's rise and the dam's fall, teach one ledger: kingdoms run on shukr, and default on it structurally.`,
facts:[{label:"Showcase",value:"Two gardens (34:15)"},{label:"The queen",value:"Bilqis: converted at the glass floor"},{label:"The throne",value:"Moved in a glance's return"},{label:"The audit",value:"Flood of al-Arim (34:16)"}],
quran:[{ref:"27:44",ar:"رَبِّ إِنِّي ظَلَمْتُ نَفْسِي وَأَسْلَمْتُ مَعَ سُلَيْمَانَ لِلَّهِ رَبِّ الْعَالَمِينَ",en:"My Lord, I have wronged myself, and I submit with Sulayman to Allah, Lord of the worlds."}]},

{id:"p-babylon",titleEn:"Babylon",titleAr:"بابل",role:"City of the two angels' test",summary:"Where sorcery was marketed under a prophet's name, and two angels taught with a warning label.",pattern:"pl-city",
details:`Mesopotamia's ancient capital enters the Qur'an in exactly one verse, attached to exactly one file: "and what was sent down upon the two angels at Babylon, {{c:a-harut-marut|Harut and Marut}}" (2:102). In the generations after {{n:22|Sulayman}}, the shayatin retailed sorcery under his royal brand, claiming the great kingdom had run on magic; revelation cleared the prophet and located the test in this city, where the two angels taught no one without the disclaimer: we are only a fitnah, so do not disbelieve.

Babylon's broader biography in the tradition is the biography of organized bewilderment: the city of confounded tongues in the older scriptures' memory, of ziggurat ambition, of {{n:9|Nimrod's}} debate by the dominant tafsir geography, where a king answered "I give life and cause death" and was silenced by a sunrise. The Codex keeps one municipal lesson from it: every city sells some knowledge that costs the buyer his Hereafter, "and they knew that whoever purchased it has no share in the next life" (2:102). Babylon is merely the verse's named branch of a franchise that never closed.`,
facts:[{label:"Verse",value:"2:102, the only mention"},{label:"The test",value:"Taught with a warning label"},{label:"Cleared",value:"Sulayman, of sorcery"},{label:"Tafsir site",value:"Nimrod's debate (2:258)"}],
quran:[{ref:"2:102",ar:"وَمَا أُنزِلَ عَلَى الْمَلَكَيْنِ بِبَابِلَ هَارُوتَ وَمَارُوتَ",en:"…and what was sent down upon the two angels at Babylon, Harut and Marut."}]},

{id:"p-badr",titleEn:"The Wells of Badr",titleAr:"آبار بدر",role:"Yawm al-Furqan · The first criterion",summary:"A watering stop on the caravan road where 313 met a thousand, and the angels wore turbans.",pattern:"pl-city",
details:`Badr was nothing before 2 AH: wells, a market season, a stop on the Syria road southwest of {{p:p-madinah|Madinah}}. Then two columns converged on its water, and the place became a word: "the day of the criterion, the day the two forces met" (8:41). At these wells {{n:37|the 313}} camped by the counsel of a companion who asked whether the position was revelation or war-craft, and the rain firmed the sand under their feet.

Here the Prophet ﷺ stretched his hands until his cloak fell, {{c:a-badr|a thousand angels}} arrived "following one another" (8:9), and the chiefs of Quraysh who had tortured the weak of Makkah were laid in one of its dry pits, their Prophet standing over it at night asking whether they had found their Lord's promise true. The men of this field became Islam's aristocracy: "perhaps Allah looked upon the people of Badr and said: do as you wish, for I have forgiven you" (Bukhari 3007), the sentence that saved a man's gravest slip. The Codex marks the site as the Path's proof that geography is made by what obedience does on it: wells, then a criterion.`,
facts:[{label:"Date",value:"17 Ramadan, 2 AH"},{label:"Name",value:"Yawm al-Furqan (8:41)"},{label:"Guests",value:"1,000 angels"},{label:"Its men",value:"“Do as you wish: forgiven”"}],
quran:[{ref:"3:123",ar:"وَلَقَدْ نَصَرَكُمُ اللَّهُ بِبَدْرٍ وَأَنتُمْ أَذِلَّةٌ",en:"Allah had already given you victory at Badr while you were few."}]},

{id:"p-hudaybiyyah",titleEn:"Al-Hudaybiyyah",titleAr:"الحديبية",role:"The tree of the pledge · The clear victory",summary:"A dry campsite at the sanctuary's edge where a stalled pilgrimage became the treaty that won the world.",pattern:"pl-city",
details:`On the edge of the Haram west of Makkah, al-Qaswa knelt and would not rise, and the Prophet ﷺ read her: "the One who held back the elephant has held her back" (Bukhari 2731). At this campsite of little water, which his ﷺ arrow-stirred well made abundant, the ummah's hardest diplomatic hour played out: {{n:40|the treaty}} whose clauses read like defeat and computed like conquest.

Under an acacia here, on the rumor of {{c:c-uthman|Uthman's}} death, some 1,400 hands took {{n:40|the Pledge of Ridwan}}, and heaven published its audit: "Allah was pleased with the believers when they pledged allegiance to you under the tree" (48:18), with the seal no court can lift: "none who pledged under the tree will enter the Fire" (Muslim 2496). The campsite's name titles the whole file: on the road home Surah al-Fath descended, "indeed We have granted you a clear opening" (48:1), dearer to him ﷺ than all the sun rises on. Umar later removed the tree's successor from veneration; the pledge was to Allah, not to wood. The Codex keeps Hudaybiyyah as the geography of patience: the site where losing the argument won the era.`,
facts:[{label:"Al-Qaswa",value:"Knelt, read as the elephant's kneeling"},{label:"The pledge",value:"~1,400, under the tree"},{label:"Heaven's audit",value:"48:18 · Muslim 2496"},{label:"Named by",value:"Surah al-Fath, on the road home"}],
quran:[{ref:"48:18",ar:"لَّقَدْ رَضِيَ اللَّهُ عَنِ الْمُؤْمِنِينَ إِذْ يُبَايِعُونَكَ تَحْتَ الشَّجَرَةِ",en:"Allah was pleased with the believers when they pledged allegiance to you under the tree."}]},

{id:"p-khaybar",titleEn:"Khaybar",titleAr:"خيبر",role:"The oasis of fortresses",summary:"Eight strongholds, a banner given to the one Allah loves, and a gate that became a byword for strength.",pattern:"pl-city",
details:`North of Madinah, Khaybar's volcanic ridges carried the strongest fortress chain in the Hijaz, and the wealth that had bankrolled {{n:39|the Confederates}}. In 7 AH, after {{n:40|Hudaybiyyah}} froze the southern front, the Prophet ﷺ marched at dawn and gave the siege its rule of engagement mercy-first: when he heard the morning adhan rise from a settlement he held back the attack.

Fortress by fortress the oasis closed, until the day he announced: "tomorrow I will give the banner to a man who loves Allah and His Messenger, and whom Allah and His Messenger love." The camp barely slept; {{c:c-ali|Ali}} was summoned from an eye ailment, cured by the Prophet's own spittle, and instructed that one man guided through him outweighed red camels (Bukhari 3701, Muslim 2406). Khaybar fell, its lands settled by treaty on half-shares, and its aftermath threaded the Seerah: {{c:c-safiyyah|Safiyyah}} became a mother of the believers, the poisoned sheep tested at its table left its long mark, and {{c:c-jafar|Ja'far}} arrived from Abyssinia the same day, doubling one joy with another. The Codex files Khaybar as the geography of the banner: strongholds fall on schedule; love's certificate was the news.`,
facts:[{label:"Chain",value:"Eight fortresses"},{label:"Rule",value:"Adhan heard = no attack"},{label:"The banner",value:"To Ali, cured and loved"},{label:"Same day",value:"Ja'far's return"}],
hadith:[{text:"Tomorrow I will give the banner to a man who loves Allah and His Messenger, and whom Allah and His Messenger love.",source:"Bukhari 3701 · Muslim 2406"}]},

{id:"p-hunayn",titleEn:"The Valley of Hunayn",titleAr:"وادي حنين",role:"The defile where numbers failed",summary:"A dawn ambush between rock walls taught the largest Muslim army ever mustered where victory is stored.",pattern:"pl-city",
details:`A stony defile on the road from {{p:p-makkah|Makkah}} to {{p:p-taif|Ta'if}}, Hunayn was chosen by Malik ibn Awf precisely for what it does to a column: compresses it, blinds its flanks, and hands the high walls to whoever arrives first. Into it at first light marched {{n:42|twelve thousand}}, the largest force Islam had fielded, carrying the one supply the Qur'an later confiscated: "your great number pleased you, but it availed you nothing, and the earth, vast as it is, narrowed upon you" (9:25).

The arrow-storm broke the vanguard; the valley became a river running backward; and the battle contracted to the width of one mule: the Prophet ﷺ pressing forward alone, announcing himself in verse, {{c:c-abbas|Abbas's}} great voice recalling the men of the tree. The reversal came as reinforcement of the unseen: "then Allah sent down His tranquility upon His Messenger and upon the believers, and sent down soldiers you did not see" (9:26). Hawazin's camp, herds, and captives fell entire, and at Ji'ranah the captives went home free. The Codex maps Hunayn as the audit of confidence: the one valley where the ummah's largest army met its smallest hour, and learned the inventory again.`,
facts:[{label:"Terrain",value:"A compressing defile"},{label:"Confiscated",value:"Confidence in numbers (9:25)"},{label:"The rally",value:"One mule + one voice"},{label:"Aftermath",value:"~6,000 captives freed"}],
quran:[{ref:"9:25",ar:"وَيَوْمَ حُنَيْنٍ إِذْ أَعْجَبَتْكُمْ كَثْرَتُكُمْ فَلَمْ تُغْنِ عَنكُمْ شَيْئًا",en:"…and on the day of Hunayn, when your great number pleased you, but it availed you nothing."}]},

{id:"p-tabuk",titleEn:"Tabuk",titleAr:"تبوك",role:"The far frontier of the hour of hardship",summary:"Six hundred miles of summer for a battle that never happened, and the sorting of every heart that marched or stayed.",pattern:"pl-city",
details:`On the Syrian frontier, twenty nights' march north of Madinah, Tabuk was {{n:43|the destination announced openly}} for the only time in the Prophet's ﷺ campaigns: the distance and the season allowed no ambiguity. High summer, ripe orchards left behind, and a Byzantine rumor ahead: the expedition existed, the Qur'an says, to weigh hearts, and it weighed them publicly. {{c:c-uthman|Uthman}} poured out a fortune; weepers were turned away for lack of mounts; the excuse-makers manufactured fatwas about the heat and were answered from heaven: "the fire of Jahannam is more intense in heat" (9:81).

At the wells of Tabuk the army camped twenty days, signed the frontier treaties, and fought no one; the sorting was the campaign. On the road back stood the mosque of harm, demolished by revelation's order, and ahead lay the fifty days of {{c:c-kab|Ka'b's}} silence until forgiveness descended. Passing al-Hijr's ruins the Prophet covered his face and commanded tears or haste. The Codex keeps Tabuk as the geography of cost: the place itself did nothing; the road to it did everything.`,
facts:[{label:"Distance",value:"~20 nights, high summer"},{label:"Battle",value:"None; hearts were the field"},{label:"Financier",value:"Uthman's thousand dinars"},{label:"Aftermath",value:"The three, and 9:118"}],
quran:[{ref:"9:81",ar:"وَقَالُوا لَا تَنفِرُوا فِي الْحَرِّ ۗ قُلْ نَارُ جَهَنَّمَ أَشَدُّ حَرًّا",en:"They said: do not march in the heat. Say: the fire of Jahannam is more intense in heat."}]}
],

waters:[
{id:"p-zamzam",titleEn:"The Well of Zamzam",titleAr:"بئر زمزم",role:"The spring that answered a mother",summary:"Struck open by an angel for a crying infant; still flowing, still drunk for whatever it is drunk for.",pattern:"pl-water",
details:`When Hajar's waterskin emptied in the valley with no vegetation, and {{p:p-safa-marwah|her seventh crossing}} ended, the angel struck the ground by the infant {{n:11|Isma'il}}, and water rose in the driest real estate on earth. The Prophet ﷺ replayed the scene with affection and a counterfactual: "may Allah have mercy on the mother of Isma'il; had she left it, Zamzam would have been a flowing spring" (Bukhari 3364). Her practical instinct, walling the water with her hands, contained the spring into a well, and the well built the city: caravans settled by the water, and {{p:p-makkah|Makkah}} exists because a mother trusted and a baby cried.

Its water washed {{n:27|the Prophet's chest}} before the ascent; his grandfather's rediscovery of the buried well restored his house's honor; and his ﷺ standing verdict grades it beyond geology: "it is blessed; it is food that satisfies" (Muslim 2473), with the sunan adding: "and a cure for illness." The ummah drinks it standing or seated, facing the House, asking, on the report that "the water of Zamzam is for whatever it is drunk for" (Ibn Majah 3062, hasan). Four millennia of pilgrims have not emptied a well opened for one child's thirst.`,
facts:[{label:"Opened for",value:"Isma'il's thirst"},{label:"Contained by",value:"Hajar's hands"},{label:"His verdict ﷺ",value:"Blessed; food that satisfies"},{label:"Drunk for",value:"Whatever it is drunk for"}],
hadith:[{text:"It is blessed; it is food that satisfies.",source:"Muslim 2473"}]},

{id:"p-nile",titleEn:"The Nile",titleAr:"النيل",role:"The river that carried a basket",summary:"Pharaoh taxed it as his own; heaven used it as a courier for the infant who would end him.",pattern:"pl-water",
details:`"Does not the kingdom of Egypt belong to me, and these rivers flowing beneath me?" (43:51): Pharaoh's title deed to the Nile was the centerpiece of his theology. The river he claimed was already under contract to the other side. On its current traveled {{n:15|the basket}}, steered past crocodiles and currents into the one dock in Egypt where the state's infanticide could not reach: the tyrant's own bathing steps, into the arms of Asiya.

The Qur'an's staging of the Nile is deliberate irony throughout: the river of the boast becomes the road of the rescue; the water that received murdered infants delivers the avenger of the infants; and when the argument ends, water again gives the verdict, {{p:p-parted-sea|a sea standing in walls}} and closing. The tradition adds the epilogue of ownership: in Umar's caliphate, Egypt's old custom of adorning a bride for the river was answered with a note thrown into the current, addressing the Nile as a servant: if you flowed from yourself, do not flow; if Allah makes you flow, flow. It has flowed since. Rivers, the file concludes, have one Owner, and He lends them to no throne.`,
facts:[{label:"The boast",value:"43:51, rivers beneath me"},{label:"The cargo",value:"One basket, one future"},{label:"The dock",value:"Pharaoh's own household"},{label:"Ownership",value:"Settled; never his"}],
quran:[{ref:"28:7",ar:"فَإِذَا خِفْتِ عَلَيْهِ فَأَلْقِيهِ فِي الْيَمِّ وَلَا تَخَافِي وَلَا تَحْزَنِي",en:"When you fear for him, cast him into the river, and do not fear and do not grieve."}]},

{id:"p-parted-sea",titleEn:"The Parted Sea",titleAr:"البحر المفلوق",role:"Water standing at attention",summary:"Struck once with a staff: each side a mountain, a nation between them, and the pursuit sealed behind.",pattern:"pl-water",
details:`At the dead end of the exodus, army behind and water ahead, the panicked arithmetic of Bani Israel ("we are surely overtaken") met {{n:18|Musa's}} certainty: {{w:w-inna-maiya|"no indeed; my Lord is with me; He will guide me"}} (26:62). The command was one strike of the staff, and the physics of the planet stepped aside: "it parted, and each portion was like a great towering mountain" (26:63), corridors of seabed walled with standing water.

A nation crossed between the water-walls; the pursuit entered the same corridors and received the other half of the miracle: the walls dismissed. "And We drowned the others" (26:66). {{n:19|Pharaoh's}} last-second creed was declined, his body retained as an exhibit. The Prophet ﷺ bound this water into the ummah's calendar on arrival in Madinah: finding Ashura fasted for the deliverance, he said "we have more right to Musa than you," fasted it, and commanded it (Bukhari 2004). Every Ashura fast since is this sea's anniversary. The Codex keeps the site unnamed on the map, as the Book left it: the coordinates that matter are "my Lord is with me," reachable from anywhere.`,
facts:[{label:"The strike",value:"One staff, twelve corridors (tafsir)"},{label:"Each side",value:"“Like a towering mountain”"},{label:"Anniversary",value:"The fast of Ashura"},{label:"Coordinates",value:"“My Lord is with me”"}],
quran:[{ref:"26:63",ar:"فَانفَلَقَ فَكَانَ كُلُّ فِرْقٍ كَالطَّوْدِ الْعَظِيمِ",en:"It parted, and each portion was like a great towering mountain."}]},

{id:"p-tuwa",titleEn:"The Sacred Valley of Tuwa",titleAr:"الوادي المقدس طوى",role:"Where sandals come off",summary:"A nameless mountainside valley, twice called sacred by its Owner, where a shepherd was commissioned against an empire.",pattern:"pl-water",
details:`Tuwa is the Qur'an's smallest sanctified geography: a valley by {{p:p-tur|the Mount}}, unknown to any map of pilgrimage, sacred for one reason only: what was said there. "Indeed, I am your Lord, so remove your sandals; you are in the sacred valley of Tuwa" (20:12). The command established the etiquette of holy ground for all scripture: the place where Allah speaks is entered barefoot.

Here {{n:17|Musa}} came for an ember and left with a mission; here the two signs were issued, {{c:an-staff|the staff}} and the white hand; here the assignment "go to Pharaoh, he has transgressed" (20:24) was answered with the du'a of the overwhelmed, {{w:w-rabbishrah|"my Lord, expand for me my chest"}}, and granted in full. The valley is invoked again in Surah an-Nazi'at as the site of the summons (79:16), a double mention for a place with no shrine, no rite, and no address. The Codex maps Tuwa as the theology of place perfected: ground is made sacred by the word spoken on it, and a burning tree in a nameless valley outranks every palace on the planet.`,
facts:[{label:"Status",value:"“The sacred valley” ×2"},{label:"Etiquette",value:"Sandals off (20:12)"},{label:"Issued here",value:"Mission + two signs"},{label:"Address",value:"None; the word is the address"}],
quran:[{ref:"20:12",ar:"إِنِّي أَنَا رَبُّكَ فَاخْلَعْ نَعْلَيْكَ ۖ إِنَّكَ بِالْوَادِ الْمُقَدَّسِ طُوًى",en:"Indeed, I am your Lord, so remove your sandals; you are in the sacred valley of Tuwa."}]},

{id:"p-tiberias",titleEn:"Lake Tiberias",titleAr:"بحيرة طبرية",role:"The end-time water gauge",summary:"A chained giant asks sailors about its water level; the hordes will one day drink it dry.",pattern:"pl-water",
details:`The freshwater lake of the Jordan valley holds the strangest portfolio in the Codex's geography: it is the Hereafter's water gauge. In the hadith of {{c:e-jassasa|al-Jassasah}} (Muslim 2942), the shackled colossus on the island runs down his checklist with Tamim's crew: tell me about the lake of Tiberias, does it hold water? It does, they said. He said: its water is about to go. {{c:e-dajjal|The chained one}} tracks his release against a shoreline.

The second appointment drains it entirely: when {{n:50|Yajuj and Majuj}} pour down "from every height," Muslim 2937 records their vanguard passing the lake and drinking it, so that the rearguard arrives and says: there was once water here. A body of water assigned two cameo roles across two hadith, both as a countdown instrument. The Codex keeps Tiberias on the map for the discipline it teaches about signs: the end of time is not scheduled in riddles only; some of its clocks are ordinary places, checkable by anyone, which is precisely why the tradition named them. Water levels, like hearts, are being read.`,
facts:[{label:"Role",value:"Countdown instrument"},{label:"Asked about by",value:"The chained one (Muslim 2942)"},{label:"Drunk dry by",value:"The hordes' vanguard"},{label:"Rearguard's line",value:"“There was once water here”"}],
hadith:[{text:"Their first ranks pass the lake of Tiberias and drink what is in it, and the last of them pass and say: there was once water here.",source:"Muslim 2937"}]},

{id:"p-euphrates",titleEn:"The Euphrates",titleAr:"نهر الفرات",role:"The river hiding a mountain of gold",summary:"One of the rivers of mercy in the hadith, and the site of the last gold rush, which the wise are ordered to skip.",pattern:"pl-water",
details:`Mesopotamia's great river carries two entries in the sound tradition, one gentle and one grim. The gentle: on {{n:31|the Night Journey}} the Prophet ﷺ saw four rivers issuing from the base of the Lote Tree, "two hidden and two apparent," and the two apparent were identified as the Nile and the Euphrates (Muslim 164): rivers of this world honored with a heavenly source-marking, which the scholars read as blessing, not plumbing.

The grim entry is a checkable prophecy: "the Hour will not rise until the Euphrates uncovers a mountain of gold, over which the people will fight, and of every hundred, ninety-nine will be killed, each of them saying: perhaps I will be the one who survives" (Bukhari 7119, Muslim 2894). The instruction attached is rare in eschatology, a direct order for the finder: "whoever is present, let him take nothing from it." A retreating river, an exposed treasure, and a fatality rate of ninety-nine percent driven by one sentence of private optimism. {{n:46|The minor signs node}} carries it in sequence; the Codex maps the river itself as the tradition's monument to the last thing the dying world will fight over, and the first thing the believer is told to walk past.`,
facts:[{label:"Honored",value:"Seen at the Lote Tree (Muslim 164)"},{label:"Will uncover",value:"A mountain of gold"},{label:"Casualty rate",value:"99 of every 100"},{label:"The order",value:"Take nothing from it"}],
hadith:[{text:"The Hour will not rise until the Euphrates uncovers a mountain of gold over which the people fight… whoever is present, let him take nothing from it.",source:"Bukhari 7119 · Muslim 2894"}]}
],

endtimes:[
{id:"p-damascus-minaret",titleEn:"The White Minaret · Damascus",titleAr:"المنارة البيضاء بدمشق",role:"The landing site of the Descent",summary:"The one address in eschatology given to the meter: east of Damascus, at dawn, mid-iqamah.",pattern:"pl-end",
details:`Prophecy is usually a compass; here it is a street address. "He will descend at the white minaret, east of Damascus, in two saffron garments, his hands resting on the wings of two angels" (Muslim 2937). Sham holds the ummah's end-time capital in the sound corpus: the Prophet ﷺ prayed for its blessing, "O Allah, bless us in our Sham" (Bukhari 1037), called it the land of the muster, and located the final believers' cohesion there: "a party of my ummah will remain manifest upon the truth… and they are in Sham" (Muslim 1924, with Bukhari 3641 unlocated).

The scene the minaret anchors is {{n:49|the Descent}}: Fajr assembled, the iqamah called, {{c:e-mahdi|the imam}} stepping back, and {{c:e-isa-return|the son of Maryam}} declining the mihrab to pray as a follower. From this coordinate the pursuit runs south to {{p:p-ludd|Ludd}}. Damascus's Umayyad mosque has carried a white minaret named for Isa for centuries; the Codex, like the careful scholars, pins its certainty to the hadith's words rather than to any current structure: the address is guaranteed; the architecture will be there when needed.`,
facts:[{label:"Address",value:"East of Damascus"},{label:"Time",value:"Fajr, mid-iqamah"},{label:"Garments",value:"Two, saffron-dyed"},{label:"Then",value:"The pursuit to Ludd"}],
hadith:[{text:"He will descend at the white minaret east of Damascus… his hands on the wings of two angels.",source:"Muslim 2937"}]},

{id:"p-ludd",titleEn:"The Gate of Ludd",titleAr:"باب لد",role:"Where the great deception ends",summary:"A town gate in Palestine, named fourteen centuries early as the coordinates of the Dajjal's death.",pattern:"pl-end",
details:`Ludd, ancient Lydda on the Palestinian plain, would be an unremarkable dot on the Codex's map except for one appointment fixed in Sahih Muslim: "the son of Maryam will pursue him and overtake him at the gate of Ludd, and kill him" (Muslim 2937). The longest-running fraud in history, {{c:e-dajjal|the one-eyed claimant}} with his mountains of bread and his inverted paradise, ends at a specific municipal gate.

The staging is deliberate humiliation by geography: the being who claimed divinity over the whole earth is run down at the edge of a small town, dissolving "as salt dissolves in water" at the true {{c:e-isa-return|Masih's}} breath, finished on a spear whose blood is shown to the believers as evidence. The scholars savored the symmetry: the false messiah dies within sight of the land where the true one's story began, in the blessed region his fraud parodied. For the Codex's reader the gate teaches the end-times' deepest comfort in one image: deception has a street address for its expiry, filed in the record before the deceiver was released. Every lie, this map says, is pre-assigned its gate.`,
facts:[{label:"Location",value:"Lydda, the Palestinian plain"},{label:"Event",value:"Death of the Dajjal"},{label:"Method",value:"Dissolves, then the spear"},{label:"Evidence",value:"His blood, shown to believers"}],
hadith:[{text:"The son of Maryam will overtake him at the gate of Ludd and kill him.",source:"Muslim 2937"}]},

{id:"p-bayda",titleEn:"Al-Bayda · The Swallowing Plain",titleAr:"البيداء",role:"Where an army enters the earth",summary:"A featureless stretch between Makkah and Madinah with one future event on file: intake.",pattern:"pl-end",
details:`Al-Bayda is the tradition's name for open, empty ground on the Makkah road, and its file contains a single future transaction, recorded from {{c:c-umm-salamah|Umm Salamah}} in Sahih Muslim: an army will march against the House to seize {{c:e-mahdi|a man taking refuge}} there, "and when they are at a bayda of the earth, it will swallow their first and their last" (Muslim 2882).

The Prophet's ﷺ questioner asked the enduring legal question: among them are the coerced and the mere traveler who joined the road. The answer wrote the jurisprudence of company forever: "they are swallowed together, then raised on the Day of Rising according to their intentions." The ground files no exemptions; the resurrection does the sorting. The Codex has met this verb before, under {{n:54|Qarun's house}} and in the three landslides of the Ten, but al-Bayda's entry is the most operationally specific: one plain, one army, one intake. As with {{p:p-ludd|Ludd}}, the map's lesson is jurisdictional: the earth is not neutral terrain in the last days; it is deputized. Choose your caravan, the plain advises, as carefully as your creed.`,
facts:[{label:"Event",value:"An army swallowed whole"},{label:"Target of the army",value:"The man at the House"},{label:"The coerced",value:"Raised by intention"},{label:"Verb",value:"Khasf: the earth deputized"}],
hadith:[{text:"When they are at a bayda of the earth, it will swallow their first and their last… then they are raised according to their intentions.",source:"Muslim 2882"}]},

{id:"p-mahshar",titleEn:"The Land of the Gathering",titleAr:"أرض المحشر",role:"The white plain of the Standing",summary:"Not any country: a new earth, flat as pressed flour, with no landmark for anyone to claim.",pattern:"pl-end",
details:`The last place every human being will stand is a place none has seen. "The Day the earth will be exchanged for another earth, and the heavens" (14:48): the Prophet ﷺ described the replacement surface with a baker's image: "mankind will be gathered on a white plain, tinged with redness, like a pure wheat loaf, with no landmark on it for anyone" (Bukhari 6521, Muslim 2790).

No landmark for anyone: the phrase carries the theology. No hill to rally at, no border to defend, no monument to hide behind, no address to inherit; the geography of privilege abolished by resurfacing. Toward this plain {{n:56|the fire drives}} the last generation, "and Sham is the land of the muster" in the direction-language of this world's map; on it {{n:59|the sun descends to a mile}}, the sweat rises by deeds, and the only elevations are moral: the shade of the Throne, the pulpits of light for the just, the high ground of {{w:w-subhan|remembered words}}. The Codex ends its atlas here deliberately: every place in these five sections was a test or a mercy; the last place is only a floor, and what stands tall on it arrives inside the standing people.`,
facts:[{label:"Surface",value:"White, like pressed flour"},{label:"Landmarks",value:"None, for anyone"},{label:"Verse",value:"14:48, the exchanged earth"},{label:"Elevation",value:"Moral only: shade & light"}],
quran:[{ref:"14:48",ar:"يَوْمَ تُبَدَّلُ الْأَرْضُ غَيْرَ الْأَرْضِ وَالسَّمَاوَاتُ",en:"The Day the earth will be exchanged for another earth, and the heavens…"}],
hadith:[{text:"Mankind will be gathered on a white plain tinged with redness, like a pure loaf, with no landmark on it for anyone.",source:"Bukhari 6521 · Muslim 2790"}]}
]
};
