// NOOR · one library object, on command, as a full content package.
//
// GET /api/package?id=<content_id or a site path>
//   id examples: /light/quran-guards-itself, verse:2-255, /dictionary/tawhid,
//   /prophet/musa, /companion/c-bilal, /place/p-badr, /path/8, /surah/19,
//   /name/1 or name:al-rahman (the graph's own slug, the id a package
//   itself prints for a Name, is accepted back as input). Answers the
//   object (its own title, text, sources, Arabic), its derivatives (reel,
//   film, related rooms, with a gap named plainly where one is missing),
//   and one deterministic draft per platform -- YouTube, Instagram,
//   Facebook, Threads, Pinterest, an X thread, Reddit -- built from the
//   object's own words by api/_package.js. Nothing is generated by a
//   model, nothing is posted, and running this twice for the same object
//   answers the same package both times.
//
// ?id= over 200 characters, or a site-path id whose %-escape cannot be
// read, is refused (400) rather than crashed on or echoed back whole;
// api/_package.js's own buildPackage() carries the status it earned
// (400, 404 or 200) so this file never has to re-decide it.
//
// Owner-gated exactly like api/insights.js: the console's cookie, or the
// admin secret in a header or query for a hand run. The resolving and the
// shaping live in api/_package.js so they can be tested without a server.

import { ownerGate } from "./_owner.js";
import { buildPackage } from "./_package.js";

const json = (res, code, obj) => {
  res.setHeader("Content-Type", "application/json; charset=utf-8");
  res.setHeader("Cache-Control", "no-store");
  return res.status(code).json(obj);
};

export default async function handler(req, res) {
  const gate = ownerGate(req);
  if (!gate.ok) return json(res, gate.code, { error: gate.reason });
  const id = (req.query || {}).id;
  if (!id) return json(res, 400, { ok: false, error: "?id=<content_id or a site path> is required" });
  try {
    const out = await buildPackage(String(id));
    return json(res, out.status || (out.ok ? 200 : 404), out);
  } catch (e) {
    return json(res, 500, { ok: false, error: String(e && e.message || e).slice(0, 200) });
  }
}
